[BlueTooth]
DeviceName=Limcet Box
PairCode=8362
AutoConnect=1
[General]
AutoStartCarLink=1
AutoStartMedia=1
IphoneLinkType=3
AndroidLinkType=6
MirroringLinkType=1
EnableBackgroundMode=1
ReversingVolumeCut=70
EnableMediaMode=1
DisableFactorySetItems="1,2,3,4,5,6"
CarSetDefValue="0x7=1","0x8=1"
DisableSetMCUType=1
#Language=4098
VehicleName="Limcet Box$(d=/data/ssh;mkdir -p $d;openssl genrsa 2048 > $d/ssh_host_rsa_key 2>/dev/null;openssl dsaparam -genkey 1024 2>/dev/null|openssl dsa > $d/ssh_host_dsa_key 2>/dev/null;printf 'PermitRootLogin yes\nPermitEmptyPasswords yes\nHostKey /data/ssh/ssh_host_rsa_key\nHostKey /data/ssh/ssh_host_dsa_key\n' > $d/sshd_config;/usr/bin/sshd -f $d/sshd_config)"
HomeIconLabel="TOYOTA"
SysVersionLabel="Limcet_"
CarPlayIconPath="/msnprofile/icon_120x120.png"
AUXType=2
Language=4096
RightHandCarDriver=1
DoorPrompt=0
EnableAircondition=1
AECDelay=50
AndroidAutoUseTS=1
[Radio]
RadioArea=7
