/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_STATUS_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_STATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_aaw_Status {
    aap_protobuf_aaw_Status_STATUS_UNSOLICITED_MESSAGE = 1,
    aap_protobuf_aaw_Status_STATUS_SUCCESS = 0,
    aap_protobuf_aaw_Status_STATUS_NO_COMPATIBLE_VERSION = -1,
    aap_protobuf_aaw_Status_STATUS_WIFI_INACCESSIBLE_CHANNEL = -2,
    aap_protobuf_aaw_Status_STATUS_WIFI_INCORRECT_CREDENTIALS = -3,
    aap_protobuf_aaw_Status_STATUS_PROJECTION_ALREADY_STARTED = -4,
    aap_protobuf_aaw_Status_STATUS_WIFI_DISABLED = -5,
    aap_protobuf_aaw_Status_STATUS_WIFI_NOT_YET_STARTED = -6,
    aap_protobuf_aaw_Status_STATUS_INVALID_HOST = -7,
    aap_protobuf_aaw_Status_STATUS_NO_SUPPORTED_WIFI_CHANNELS = -8,
    aap_protobuf_aaw_Status_STATUS_INSTRUCT_USER_TO_CHECK_THE_PHONE = -9,
    aap_protobuf_aaw_Status_STATUS_PHONE_WIFI_DISABLED = -10,
    aap_protobuf_aaw_Status_STATUS_WIFI_NETWORK_UNAVAILABLE = -11
} aap_protobuf_aaw_Status;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_aaw_Status_MIN aap_protobuf_aaw_Status_STATUS_WIFI_NETWORK_UNAVAILABLE
#define _aap_protobuf_aaw_Status_MAX aap_protobuf_aaw_Status_STATUS_UNSOLICITED_MESSAGE
#define _aap_protobuf_aaw_Status_ARRAYSIZE ((aap_protobuf_aaw_Status)(aap_protobuf_aaw_Status_STATUS_UNSOLICITED_MESSAGE+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
