/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFISTARTREQUEST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFISTARTREQUEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_aaw_WifiStartRequest {
    char ip_address[64];
    uint32_t port;
} aap_protobuf_aaw_WifiStartRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_aaw_WifiStartRequest_init_default {"", 0}
#define aap_protobuf_aaw_WifiStartRequest_init_zero {"", 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_aaw_WifiStartRequest_ip_address_tag 1
#define aap_protobuf_aaw_WifiStartRequest_port_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_aaw_WifiStartRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   ip_address,        1) \
X(a, STATIC,   REQUIRED, UINT32,   port,              2)
#define aap_protobuf_aaw_WifiStartRequest_CALLBACK NULL
#define aap_protobuf_aaw_WifiStartRequest_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_aaw_WifiStartRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_aaw_WifiStartRequest_fields &aap_protobuf_aaw_WifiStartRequest_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFISTARTREQUEST_PB_H_MAX_SIZE aap_protobuf_aaw_WifiStartRequest_size
#define aap_protobuf_aaw_WifiStartRequest_size   71

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
