/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFISTARTRESPONSE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFISTARTRESPONSE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/aaw/Status.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_aaw_WifiStartResponse {
    bool has_ip_address;
    char ip_address[64];
    bool has_port;
    uint32_t port;
    aap_protobuf_aaw_Status status;
} aap_protobuf_aaw_WifiStartResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_aaw_WifiStartResponse_init_default {false, "", false, 0, _aap_protobuf_aaw_Status_MIN}
#define aap_protobuf_aaw_WifiStartResponse_init_zero {false, "", false, 0, _aap_protobuf_aaw_Status_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_aaw_WifiStartResponse_ip_address_tag 1
#define aap_protobuf_aaw_WifiStartResponse_port_tag 2
#define aap_protobuf_aaw_WifiStartResponse_status_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_aaw_WifiStartResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   ip_address,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   port,              2) \
X(a, STATIC,   REQUIRED, ENUM,     status,            3)
#define aap_protobuf_aaw_WifiStartResponse_CALLBACK NULL
#define aap_protobuf_aaw_WifiStartResponse_DEFAULT (const pb_byte_t*)"\x18\x01\x00"

extern const pb_msgdesc_t aap_protobuf_aaw_WifiStartResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_aaw_WifiStartResponse_fields &aap_protobuf_aaw_WifiStartResponse_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFISTARTRESPONSE_PB_H_MAX_SIZE aap_protobuf_aaw_WifiStartResponse_size
#define aap_protobuf_aaw_WifiStartResponse_size  82

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
