/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFIINFORESPONSE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFIINFORESPONSE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/wifiprojection/message/AccessPointType.pb.h"
#include "aap_protobuf/service/wifiprojection/message/WifiSecurityMode.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_aaw_WifiInfoResponse {
    char ssid[64];
    char password[64];
    char bssid[64];
    aap_protobuf_service_wifiprojection_message_WifiSecurityMode security_mode;
    bool has_access_point_type;
    aap_protobuf_service_wifiprojection_message_AccessPointType access_point_type;
} aap_protobuf_aaw_WifiInfoResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_aaw_WifiInfoResponse_init_default {"", "", "", _aap_protobuf_service_wifiprojection_message_WifiSecurityMode_MIN, false, _aap_protobuf_service_wifiprojection_message_AccessPointType_MIN}
#define aap_protobuf_aaw_WifiInfoResponse_init_zero {"", "", "", _aap_protobuf_service_wifiprojection_message_WifiSecurityMode_MIN, false, _aap_protobuf_service_wifiprojection_message_AccessPointType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_aaw_WifiInfoResponse_ssid_tag 1
#define aap_protobuf_aaw_WifiInfoResponse_password_tag 2
#define aap_protobuf_aaw_WifiInfoResponse_bssid_tag 3
#define aap_protobuf_aaw_WifiInfoResponse_security_mode_tag 4
#define aap_protobuf_aaw_WifiInfoResponse_access_point_type_tag 5

/* Struct field encoding specification for nanopb */
#define aap_protobuf_aaw_WifiInfoResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   ssid,              1) \
X(a, STATIC,   REQUIRED, STRING,   password,          2) \
X(a, STATIC,   REQUIRED, STRING,   bssid,             3) \
X(a, STATIC,   REQUIRED, UENUM,    security_mode,     4) \
X(a, STATIC,   OPTIONAL, UENUM,    access_point_type,   5)
#define aap_protobuf_aaw_WifiInfoResponse_CALLBACK NULL
#define aap_protobuf_aaw_WifiInfoResponse_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_aaw_WifiInfoResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_aaw_WifiInfoResponse_fields &aap_protobuf_aaw_WifiInfoResponse_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFIINFORESPONSE_PB_H_MAX_SIZE aap_protobuf_aaw_WifiInfoResponse_size
#define aap_protobuf_aaw_WifiInfoResponse_size   199

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
