/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFIINFOREQUEST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFIINFOREQUEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_aaw_WifiInfoRequest {
    char dummy_field;
} aap_protobuf_aaw_WifiInfoRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_aaw_WifiInfoRequest_init_default {0}
#define aap_protobuf_aaw_WifiInfoRequest_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */

/* Struct field encoding specification for nanopb */
#define aap_protobuf_aaw_WifiInfoRequest_FIELDLIST(X, a) \

#define aap_protobuf_aaw_WifiInfoRequest_CALLBACK NULL
#define aap_protobuf_aaw_WifiInfoRequest_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_aaw_WifiInfoRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_aaw_WifiInfoRequest_fields &aap_protobuf_aaw_WifiInfoRequest_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFIINFOREQUEST_PB_H_MAX_SIZE aap_protobuf_aaw_WifiInfoRequest_size
#define aap_protobuf_aaw_WifiInfoRequest_size    0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
