/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFIVERSIONRESPONSE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFIVERSIONRESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_aaw_WifiVersionResponse {
    uint32_t unknown_value_a;
    uint32_t unknown_value_b;
    bool has_unknown_value_c;
    char unknown_value_c[64];
    uint32_t unknown_value_d;
} aap_protobuf_aaw_WifiVersionResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_aaw_WifiVersionResponse_init_default {0, 0, false, "", 0}
#define aap_protobuf_aaw_WifiVersionResponse_init_zero {0, 0, false, "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_aaw_WifiVersionResponse_unknown_value_a_tag 1
#define aap_protobuf_aaw_WifiVersionResponse_unknown_value_b_tag 2
#define aap_protobuf_aaw_WifiVersionResponse_unknown_value_c_tag 3
#define aap_protobuf_aaw_WifiVersionResponse_unknown_value_d_tag 4

/* Struct field encoding specification for nanopb */
#define aap_protobuf_aaw_WifiVersionResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   unknown_value_a,   1) \
X(a, STATIC,   REQUIRED, UINT32,   unknown_value_b,   2) \
X(a, STATIC,   OPTIONAL, STRING,   unknown_value_c,   3) \
X(a, STATIC,   REQUIRED, UINT32,   unknown_value_d,   4)
#define aap_protobuf_aaw_WifiVersionResponse_CALLBACK NULL
#define aap_protobuf_aaw_WifiVersionResponse_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_aaw_WifiVersionResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_aaw_WifiVersionResponse_fields &aap_protobuf_aaw_WifiVersionResponse_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_AAW_AAP_PROTOBUF_AAW_WIFIVERSIONRESPONSE_PB_H_MAX_SIZE aap_protobuf_aaw_WifiVersionResponse_size
#define aap_protobuf_aaw_WifiVersionResponse_size 83

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
