/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_INPUTSOURCESERVICE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_INPUTSOURCESERVICE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/inputsource/message/FeedbackEvent.pb.h"
#include "aap_protobuf/service/inputsource/message/TouchScreenType.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_inputsource_InputSourceService_TouchScreen {
    int32_t width;
    int32_t height;
    bool has_type;
    aap_protobuf_service_inputsource_message_TouchScreenType type;
    bool has_is_secondary;
    bool is_secondary;
} aap_protobuf_service_inputsource_InputSourceService_TouchScreen;

typedef struct _aap_protobuf_service_inputsource_InputSourceService_TouchPad {
    int32_t width;
    int32_t height;
    bool has_ui_navigation;
    bool ui_navigation;
    bool has_physical_width;
    int32_t physical_width;
    bool has_physical_height;
    int32_t physical_height;
    bool has_ui_absolute;
    bool ui_absolute;
    bool has_tap_as_select;
    bool tap_as_select;
    bool has_sensitivity;
    int32_t sensitivity;
} aap_protobuf_service_inputsource_InputSourceService_TouchPad;

typedef struct _aap_protobuf_service_inputsource_InputSourceService {
    pb_size_t keycodes_supported_count;
    int32_t keycodes_supported[8];
    pb_size_t touchscreen_count;
    aap_protobuf_service_inputsource_InputSourceService_TouchScreen touchscreen[8];
    pb_size_t touchpad_count;
    aap_protobuf_service_inputsource_InputSourceService_TouchPad touchpad[8];
    pb_size_t feedback_events_supported_count;
    aap_protobuf_service_inputsource_message_FeedbackEvent feedback_events_supported[8];
    bool has_display_id;
    uint32_t display_id;
} aap_protobuf_service_inputsource_InputSourceService;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_inputsource_InputSourceService_init_default {0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_default}, 0, {aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_default, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_default}, 0, {_aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN}, false, 0}
#define aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_default {0, 0, false, _aap_protobuf_service_inputsource_message_TouchScreenType_MIN, false, 0}
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_default {0, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define aap_protobuf_service_inputsource_InputSourceService_init_zero {0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_zero}, 0, {aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_zero, aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_zero}, 0, {_aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN}, false, 0}
#define aap_protobuf_service_inputsource_InputSourceService_TouchScreen_init_zero {0, 0, false, _aap_protobuf_service_inputsource_message_TouchScreenType_MIN, false, 0}
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_init_zero {0, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_inputsource_InputSourceService_TouchScreen_width_tag 1
#define aap_protobuf_service_inputsource_InputSourceService_TouchScreen_height_tag 2
#define aap_protobuf_service_inputsource_InputSourceService_TouchScreen_type_tag 3
#define aap_protobuf_service_inputsource_InputSourceService_TouchScreen_is_secondary_tag 4
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_width_tag 1
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_height_tag 2
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_ui_navigation_tag 3
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_physical_width_tag 4
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_physical_height_tag 5
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_ui_absolute_tag 6
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_tap_as_select_tag 7
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_sensitivity_tag 8
#define aap_protobuf_service_inputsource_InputSourceService_keycodes_supported_tag 1
#define aap_protobuf_service_inputsource_InputSourceService_touchscreen_tag 2
#define aap_protobuf_service_inputsource_InputSourceService_touchpad_tag 3
#define aap_protobuf_service_inputsource_InputSourceService_feedback_events_supported_tag 4
#define aap_protobuf_service_inputsource_InputSourceService_display_id_tag 5

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_inputsource_InputSourceService_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, INT32,    keycodes_supported,   1) \
X(a, STATIC,   REPEATED, MESSAGE,  touchscreen,       2) \
X(a, STATIC,   REPEATED, MESSAGE,  touchpad,          3) \
X(a, STATIC,   REPEATED, UENUM,    feedback_events_supported,   4) \
X(a, STATIC,   OPTIONAL, UINT32,   display_id,        5)
#define aap_protobuf_service_inputsource_InputSourceService_CALLBACK NULL
#define aap_protobuf_service_inputsource_InputSourceService_DEFAULT NULL
#define aap_protobuf_service_inputsource_InputSourceService_touchscreen_MSGTYPE aap_protobuf_service_inputsource_InputSourceService_TouchScreen
#define aap_protobuf_service_inputsource_InputSourceService_touchpad_MSGTYPE aap_protobuf_service_inputsource_InputSourceService_TouchPad

#define aap_protobuf_service_inputsource_InputSourceService_TouchScreen_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    width,             1) \
X(a, STATIC,   REQUIRED, INT32,    height,            2) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              3) \
X(a, STATIC,   OPTIONAL, BOOL,     is_secondary,      4)
#define aap_protobuf_service_inputsource_InputSourceService_TouchScreen_CALLBACK NULL
#define aap_protobuf_service_inputsource_InputSourceService_TouchScreen_DEFAULT (const pb_byte_t*)"\x18\x01\x00"

#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    width,             1) \
X(a, STATIC,   REQUIRED, INT32,    height,            2) \
X(a, STATIC,   OPTIONAL, BOOL,     ui_navigation,     3) \
X(a, STATIC,   OPTIONAL, INT32,    physical_width,    4) \
X(a, STATIC,   OPTIONAL, INT32,    physical_height,   5) \
X(a, STATIC,   OPTIONAL, BOOL,     ui_absolute,       6) \
X(a, STATIC,   OPTIONAL, BOOL,     tap_as_select,     7) \
X(a, STATIC,   OPTIONAL, INT32,    sensitivity,       8)
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_CALLBACK NULL
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_inputsource_InputSourceService_msg;
extern const pb_msgdesc_t aap_protobuf_service_inputsource_InputSourceService_TouchScreen_msg;
extern const pb_msgdesc_t aap_protobuf_service_inputsource_InputSourceService_TouchPad_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_inputsource_InputSourceService_fields &aap_protobuf_service_inputsource_InputSourceService_msg
#define aap_protobuf_service_inputsource_InputSourceService_TouchScreen_fields &aap_protobuf_service_inputsource_InputSourceService_TouchScreen_msg
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_fields &aap_protobuf_service_inputsource_InputSourceService_TouchPad_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_INPUTSOURCE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_INPUTSOURCESERVICE_PB_H_MAX_SIZE aap_protobuf_service_inputsource_InputSourceService_size
#define aap_protobuf_service_inputsource_InputSourceService_TouchPad_size 61
#define aap_protobuf_service_inputsource_InputSourceService_TouchScreen_size 26
#define aap_protobuf_service_inputsource_InputSourceService_size 838

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
