/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "aap_protobuf/service/inputsource/InputSourceService.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aap_protobuf_service_inputsource_InputSourceService, aap_protobuf_service_inputsource_InputSourceService, 2)


PB_BIND(aap_protobuf_service_inputsource_InputSourceService_TouchScreen, aap_protobuf_service_inputsource_InputSourceService_TouchScreen, AUTO)


PB_BIND(aap_protobuf_service_inputsource_InputSourceService_TouchPad, aap_protobuf_service_inputsource_InputSourceService_TouchPad, AUTO)



