/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_INPUTMESSAGEID_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_INPUTMESSAGEID_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_inputsource_InputMessageId {
    aap_protobuf_service_inputsource_InputMessageId_INPUT_MESSAGE_INPUT_REPORT = 32769,
    aap_protobuf_service_inputsource_InputMessageId_INPUT_MESSAGE_KEY_BINDING_REQUEST = 32770,
    aap_protobuf_service_inputsource_InputMessageId_INPUT_MESSAGE_KEY_BINDING_RESPONSE = 32771,
    aap_protobuf_service_inputsource_InputMessageId_INPUT_MESSAGE_INPUT_FEEDBACK = 32772
} aap_protobuf_service_inputsource_InputMessageId;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_inputsource_InputMessageId_MIN aap_protobuf_service_inputsource_InputMessageId_INPUT_MESSAGE_INPUT_REPORT
#define _aap_protobuf_service_inputsource_InputMessageId_MAX aap_protobuf_service_inputsource_InputMessageId_INPUT_MESSAGE_INPUT_FEEDBACK
#define _aap_protobuf_service_inputsource_InputMessageId_ARRAYSIZE ((aap_protobuf_service_inputsource_InputMessageId)(aap_protobuf_service_inputsource_InputMessageId_INPUT_MESSAGE_INPUT_FEEDBACK+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
