/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONDESTINATIONDISTANCE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONDESTINATIONDISTANCE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/navigationstatus/message/NavigationDistance.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance {
    bool has_distance;
    aap_protobuf_service_navigationstatus_message_NavigationDistance distance;
    bool has_estimated_time_at_arrival;
    char estimated_time_at_arrival[64];
    bool has_time_to_arrival_seconds;
    int64_t time_to_arrival_seconds;
} aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_init_default {false, aap_protobuf_service_navigationstatus_message_NavigationDistance_init_default, false, "", false, 0}
#define aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_init_zero {false, aap_protobuf_service_navigationstatus_message_NavigationDistance_init_zero, false, "", false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_distance_tag 1
#define aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_estimated_time_at_arrival_tag 2
#define aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_time_to_arrival_seconds_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  distance,          1) \
X(a, STATIC,   OPTIONAL, STRING,   estimated_time_at_arrival,   2) \
X(a, STATIC,   OPTIONAL, INT64,    time_to_arrival_seconds,   3)
#define aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_CALLBACK NULL
#define aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_DEFAULT NULL
#define aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_distance_MSGTYPE aap_protobuf_service_navigationstatus_message_NavigationDistance

extern const pb_msgdesc_t aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_fields &aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONDESTINATIONDISTANCE_PB_H_MAX_SIZE aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_size
#define aap_protobuf_service_navigationstatus_message_NavigationDestinationDistance_size 156

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
