/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONNEXTTURNEVENT_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONNEXTTURNEVENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide {
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide_LEFT = 1,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide_RIGHT = 2,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide_UNSPECIFIED = 3
} aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide;

typedef enum _aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum {
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_UNKNOWN = 0,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_DEPART = 1,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_NAME_CHANGE = 2,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_SLIGHT_TURN = 3,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_TURN = 4,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_SHARP_TURN = 5,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_U_TURN = 6,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_ON_RAMP = 7,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_OFF_RAMP = 8,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_FORK = 9,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_MERGE = 10,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_ROUNDABOUT_ENTER = 11,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_ROUNDABOUT_EXIT = 12,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_ROUNDABOUT_ENTER_AND_EXIT = 13,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_STRAIGHT = 14,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_FERRY_BOAT = 16,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_FERRY_TRAIN = 17,
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_DESTINATION = 19
} aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_image_t;
typedef struct _aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent {
    char road[64];
    bool has_turn_side;
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide turn_side;
    bool has_event;
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum event;
    bool has_image;
    aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_image_t image;
    bool has_turn_number;
    int32_t turn_number;
    bool has_turn_angle;
    int32_t turn_angle;
} aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide_MIN aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide_LEFT
#define _aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide_MAX aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide_UNSPECIFIED
#define _aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide_ARRAYSIZE ((aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide)(aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide_UNSPECIFIED+1))

#define _aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_MIN aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_UNKNOWN
#define _aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_MAX aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_DESTINATION
#define _aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_ARRAYSIZE ((aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum)(aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_DESTINATION+1))

#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_turn_side_ENUMTYPE aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_event_ENUMTYPE aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum


/* Initializer values for message structs */
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_init_default {"", false, _aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide_MIN, false, _aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_MIN, false, {0, {0}}, false, 0, false, 0}
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_init_zero {"", false, _aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_TurnSide_MIN, false, _aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_NextTurnEnum_MIN, false, {0, {0}}, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_road_tag 1
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_turn_side_tag 2
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_event_tag 3
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_image_tag 4
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_turn_number_tag 5
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_turn_angle_tag 6

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   road,              1) \
X(a, STATIC,   OPTIONAL, UENUM,    turn_side,         2) \
X(a, STATIC,   OPTIONAL, UENUM,    event,             3) \
X(a, STATIC,   OPTIONAL, BYTES,    image,             4) \
X(a, STATIC,   OPTIONAL, INT32,    turn_number,       5) \
X(a, STATIC,   OPTIONAL, INT32,    turn_angle,        6)
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_CALLBACK NULL
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_DEFAULT (const pb_byte_t*)"\x10\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_fields &aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONNEXTTURNEVENT_PB_H_MAX_SIZE aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_size
#define aap_protobuf_service_navigationstatus_message_NavigationNextTurnEvent_size 157

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
