/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONDISTANCE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONDISTANCE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits {
    aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_UNKNOWN_DISTANCE_UNIT = 0,
    aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_METERS = 1,
    aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_KILOMETERS = 2,
    aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_KILOMETERS_P1 = 3,
    aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_MILES = 4,
    aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_MILES_P1 = 5,
    aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_FEET = 6,
    aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_YARDS = 7
} aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits;

/* Struct definitions */
typedef struct _aap_protobuf_service_navigationstatus_message_NavigationDistance {
    bool has_meters;
    int32_t meters;
    bool has_display_value;
    char display_value[64];
    bool has_display_units;
    aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits display_units;
} aap_protobuf_service_navigationstatus_message_NavigationDistance;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_MIN aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_UNKNOWN_DISTANCE_UNIT
#define _aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_MAX aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_YARDS
#define _aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_ARRAYSIZE ((aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits)(aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_YARDS+1))

#define aap_protobuf_service_navigationstatus_message_NavigationDistance_display_units_ENUMTYPE aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits


/* Initializer values for message structs */
#define aap_protobuf_service_navigationstatus_message_NavigationDistance_init_default {false, 0, false, "", false, _aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_MIN}
#define aap_protobuf_service_navigationstatus_message_NavigationDistance_init_zero {false, 0, false, "", false, _aap_protobuf_service_navigationstatus_message_NavigationDistance_DistanceUnits_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_navigationstatus_message_NavigationDistance_meters_tag 1
#define aap_protobuf_service_navigationstatus_message_NavigationDistance_display_value_tag 2
#define aap_protobuf_service_navigationstatus_message_NavigationDistance_display_units_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_navigationstatus_message_NavigationDistance_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    meters,            1) \
X(a, STATIC,   OPTIONAL, STRING,   display_value,     2) \
X(a, STATIC,   OPTIONAL, UENUM,    display_units,     3)
#define aap_protobuf_service_navigationstatus_message_NavigationDistance_CALLBACK NULL
#define aap_protobuf_service_navigationstatus_message_NavigationDistance_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_navigationstatus_message_NavigationDistance_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_navigationstatus_message_NavigationDistance_fields &aap_protobuf_service_navigationstatus_message_NavigationDistance_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONDISTANCE_PB_H_MAX_SIZE aap_protobuf_service_navigationstatus_message_NavigationDistance_size
#define aap_protobuf_service_navigationstatus_message_NavigationDistance_size 78

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
