/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONROAD_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONROAD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_navigationstatus_message_NavigationRoad {
    bool has_name;
    char name[64];
} aap_protobuf_service_navigationstatus_message_NavigationRoad;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_navigationstatus_message_NavigationRoad_init_default {false, ""}
#define aap_protobuf_service_navigationstatus_message_NavigationRoad_init_zero {false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_navigationstatus_message_NavigationRoad_name_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_navigationstatus_message_NavigationRoad_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   name,              1)
#define aap_protobuf_service_navigationstatus_message_NavigationRoad_CALLBACK NULL
#define aap_protobuf_service_navigationstatus_message_NavigationRoad_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_navigationstatus_message_NavigationRoad_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_navigationstatus_message_NavigationRoad_fields &aap_protobuf_service_navigationstatus_message_NavigationRoad_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONROAD_PB_H_MAX_SIZE aap_protobuf_service_navigationstatus_message_NavigationRoad_size
#define aap_protobuf_service_navigationstatus_message_NavigationRoad_size 65

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
