/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONCUE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONCUE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_navigationstatus_message_NavigationCue {
    pb_size_t alternate_text_count;
    char alternate_text[8][64];
} aap_protobuf_service_navigationstatus_message_NavigationCue;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_navigationstatus_message_NavigationCue_init_default {0, {"", "", "", "", "", "", "", ""}}
#define aap_protobuf_service_navigationstatus_message_NavigationCue_init_zero {0, {"", "", "", "", "", "", "", ""}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_navigationstatus_message_NavigationCue_alternate_text_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_navigationstatus_message_NavigationCue_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, STRING,   alternate_text,    1)
#define aap_protobuf_service_navigationstatus_message_NavigationCue_CALLBACK NULL
#define aap_protobuf_service_navigationstatus_message_NavigationCue_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_navigationstatus_message_NavigationCue_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_navigationstatus_message_NavigationCue_fields &aap_protobuf_service_navigationstatus_message_NavigationCue_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_MESSAGE_NAVIGATIONCUE_PB_H_MAX_SIZE aap_protobuf_service_navigationstatus_message_NavigationCue_size
#define aap_protobuf_service_navigationstatus_message_NavigationCue_size 520

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
