[General]
ProductId=Limcet-P200
ProductType=2
ResourceName=Box-P200
ScreenType=1
ResolutionType=1
McuType=6
#BlueToothType=5
BlueToothType=6
RadioType=0
CanType=0
#SoundType=0
SoundType=3
MSNEryPortName="/dev/ttyS2"
MCUPortName="/dev/ttyHS0"
