/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_SOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SOURCE_MESSAGE_ACK_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_SOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SOURCE_MESSAGE_ACK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_media_source_message_Ack {
    int32_t session_id;
    bool has_ack;
    uint32_t ack;
    pb_size_t receive_timestamp_ns_count;
    uint64_t receive_timestamp_ns[8];
} aap_protobuf_service_media_source_message_Ack;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_media_source_message_Ack_init_default {0, false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define aap_protobuf_service_media_source_message_Ack_init_zero {0, false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_media_source_message_Ack_session_id_tag 1
#define aap_protobuf_service_media_source_message_Ack_ack_tag 2
#define aap_protobuf_service_media_source_message_Ack_receive_timestamp_ns_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_media_source_message_Ack_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    session_id,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   ack,               2) \
X(a, STATIC,   REPEATED, UINT64,   receive_timestamp_ns,   3)
#define aap_protobuf_service_media_source_message_Ack_CALLBACK NULL
#define aap_protobuf_service_media_source_message_Ack_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_media_source_message_Ack_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_media_source_message_Ack_fields &aap_protobuf_service_media_source_message_Ack_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIA_SOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SOURCE_MESSAGE_ACK_PB_H_MAX_SIZE aap_protobuf_service_media_source_message_Ack_size
#define aap_protobuf_service_media_source_message_Ack_size 105

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
