/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_SOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SOURCE_MESSAGE_MICROPHONERESPONSE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_SOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SOURCE_MESSAGE_MICROPHONERESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_media_source_message_MicrophoneResponse {
    int32_t status;
    bool has_session_id;
    int32_t session_id;
} aap_protobuf_service_media_source_message_MicrophoneResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_media_source_message_MicrophoneResponse_init_default {0, false, 0}
#define aap_protobuf_service_media_source_message_MicrophoneResponse_init_zero {0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_media_source_message_MicrophoneResponse_status_tag 1
#define aap_protobuf_service_media_source_message_MicrophoneResponse_session_id_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_media_source_message_MicrophoneResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    status,            1) \
X(a, STATIC,   OPTIONAL, INT32,    session_id,        2)
#define aap_protobuf_service_media_source_message_MicrophoneResponse_CALLBACK NULL
#define aap_protobuf_service_media_source_message_MicrophoneResponse_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_media_source_message_MicrophoneResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_media_source_message_MicrophoneResponse_fields &aap_protobuf_service_media_source_message_MicrophoneResponse_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIA_SOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SOURCE_MESSAGE_MICROPHONERESPONSE_PB_H_MAX_SIZE aap_protobuf_service_media_source_message_MicrophoneResponse_size
#define aap_protobuf_service_media_source_message_MicrophoneResponse_size 22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
