/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_ACCESSPOINTTYPE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_ACCESSPOINTTYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_wifiprojection_message_AccessPointType {
    aap_protobuf_service_wifiprojection_message_AccessPointType_STATIC = 0,
    aap_protobuf_service_wifiprojection_message_AccessPointType_DYNAMIC = 1
} aap_protobuf_service_wifiprojection_message_AccessPointType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_wifiprojection_message_AccessPointType_MIN aap_protobuf_service_wifiprojection_message_AccessPointType_STATIC
#define _aap_protobuf_service_wifiprojection_message_AccessPointType_MAX aap_protobuf_service_wifiprojection_message_AccessPointType_DYNAMIC
#define _aap_protobuf_service_wifiprojection_message_AccessPointType_ARRAYSIZE ((aap_protobuf_service_wifiprojection_message_AccessPointType)(aap_protobuf_service_wifiprojection_message_AccessPointType_DYNAMIC+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
