/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_WIFISECURITYMODE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_WIFISECURITYMODE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_wifiprojection_message_WifiSecurityMode {
    aap_protobuf_service_wifiprojection_message_WifiSecurityMode_UNKNOWN_SECURITY_MODE = 0,
    aap_protobuf_service_wifiprojection_message_WifiSecurityMode_OPEN = 1,
    aap_protobuf_service_wifiprojection_message_WifiSecurityMode_WEP_64 = 2,
    aap_protobuf_service_wifiprojection_message_WifiSecurityMode_WEP_128 = 3,
    aap_protobuf_service_wifiprojection_message_WifiSecurityMode_WPA_PERSONAL = 4,
    aap_protobuf_service_wifiprojection_message_WifiSecurityMode_WPA2_PERSONAL = 5,
    aap_protobuf_service_wifiprojection_message_WifiSecurityMode_WPA_WPA2_PERSONAL = 6,
    aap_protobuf_service_wifiprojection_message_WifiSecurityMode_WPA_ENTERPRISE = 7,
    aap_protobuf_service_wifiprojection_message_WifiSecurityMode_WPA2_ENTERPRISE = 8,
    aap_protobuf_service_wifiprojection_message_WifiSecurityMode_WPA_WPA2_ENTERPRISE = 9
} aap_protobuf_service_wifiprojection_message_WifiSecurityMode;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_wifiprojection_message_WifiSecurityMode_MIN aap_protobuf_service_wifiprojection_message_WifiSecurityMode_UNKNOWN_SECURITY_MODE
#define _aap_protobuf_service_wifiprojection_message_WifiSecurityMode_MAX aap_protobuf_service_wifiprojection_message_WifiSecurityMode_WPA_WPA2_ENTERPRISE
#define _aap_protobuf_service_wifiprojection_message_WifiSecurityMode_ARRAYSIZE ((aap_protobuf_service_wifiprojection_message_WifiSecurityMode)(aap_protobuf_service_wifiprojection_message_WifiSecurityMode_WPA_WPA2_ENTERPRISE+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
