/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_WIFICREDENTIALSRESPONSE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_WIFICREDENTIALSRESPONSE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/wifiprojection/message/AccessPointType.pb.h"
#include "aap_protobuf/service/wifiprojection/message/WifiSecurityMode.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse {
    bool has_car_wifi_password;
    char car_wifi_password[64];
    bool has_car_wifi_security_mode;
    aap_protobuf_service_wifiprojection_message_WifiSecurityMode car_wifi_security_mode;
    bool has_car_wifi_ssid;
    char car_wifi_ssid[64];
    pb_size_t supported_wifi_channels_count;
    int32_t supported_wifi_channels[8];
    bool has_access_point_type;
    aap_protobuf_service_wifiprojection_message_AccessPointType access_point_type;
} aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_init_default {false, "", false, _aap_protobuf_service_wifiprojection_message_WifiSecurityMode_MIN, false, "", 0, {0, 0, 0, 0, 0, 0, 0, 0}, false, _aap_protobuf_service_wifiprojection_message_AccessPointType_MIN}
#define aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_init_zero {false, "", false, _aap_protobuf_service_wifiprojection_message_WifiSecurityMode_MIN, false, "", 0, {0, 0, 0, 0, 0, 0, 0, 0}, false, _aap_protobuf_service_wifiprojection_message_AccessPointType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_car_wifi_password_tag 1
#define aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_car_wifi_security_mode_tag 2
#define aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_car_wifi_ssid_tag 3
#define aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_supported_wifi_channels_tag 4
#define aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_access_point_type_tag 5

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   car_wifi_password,   1) \
X(a, STATIC,   OPTIONAL, UENUM,    car_wifi_security_mode,   2) \
X(a, STATIC,   OPTIONAL, STRING,   car_wifi_ssid,     3) \
X(a, STATIC,   REPEATED, INT32,    supported_wifi_channels,   4) \
X(a, STATIC,   OPTIONAL, UENUM,    access_point_type,   5)
#define aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_CALLBACK NULL
#define aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_fields &aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_MESSAGE_WIFICREDENTIALSRESPONSE_PB_H_MAX_SIZE aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_size
#define aap_protobuf_service_wifiprojection_message_WifiCredentialsResponse_size 222

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
