/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_NAVIGATIONSTATUSSERVICE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_NAVIGATIONSTATUSSERVICE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType {
    aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType_IMAGE = 1,
    aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType_ENUM = 2
} aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType;

/* Struct definitions */
typedef struct _aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions {
    int32_t height;
    int32_t width;
    int32_t colour_depth_bits;
} aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions;

typedef struct _aap_protobuf_service_navigationstatus_NavigationStatusService {
    int32_t minimum_interval_ms;
    aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType type;
    bool has_image_options;
    aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions image_options;
} aap_protobuf_service_navigationstatus_NavigationStatusService;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType_MIN aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType_IMAGE
#define _aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType_MAX aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType_ENUM
#define _aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType_ARRAYSIZE ((aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType)(aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType_ENUM+1))

#define aap_protobuf_service_navigationstatus_NavigationStatusService_type_ENUMTYPE aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType



/* Initializer values for message structs */
#define aap_protobuf_service_navigationstatus_NavigationStatusService_init_default {0, _aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType_MIN, false, aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_init_default}
#define aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_init_default {0, 0, 0}
#define aap_protobuf_service_navigationstatus_NavigationStatusService_init_zero {0, _aap_protobuf_service_navigationstatus_NavigationStatusService_InstrumentClusterType_MIN, false, aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_init_zero}
#define aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_init_zero {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_height_tag 1
#define aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_width_tag 2
#define aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_colour_depth_bits_tag 3
#define aap_protobuf_service_navigationstatus_NavigationStatusService_minimum_interval_ms_tag 1
#define aap_protobuf_service_navigationstatus_NavigationStatusService_type_tag 2
#define aap_protobuf_service_navigationstatus_NavigationStatusService_image_options_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_navigationstatus_NavigationStatusService_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    minimum_interval_ms,   1) \
X(a, STATIC,   REQUIRED, UENUM,    type,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  image_options,     3)
#define aap_protobuf_service_navigationstatus_NavigationStatusService_CALLBACK NULL
#define aap_protobuf_service_navigationstatus_NavigationStatusService_DEFAULT (const pb_byte_t*)"\x10\x01\x00"
#define aap_protobuf_service_navigationstatus_NavigationStatusService_image_options_MSGTYPE aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions

#define aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    height,            1) \
X(a, STATIC,   REQUIRED, INT32,    width,             2) \
X(a, STATIC,   REQUIRED, INT32,    colour_depth_bits,   3)
#define aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_CALLBACK NULL
#define aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_navigationstatus_NavigationStatusService_msg;
extern const pb_msgdesc_t aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_navigationstatus_NavigationStatusService_fields &aap_protobuf_service_navigationstatus_NavigationStatusService_msg
#define aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_fields &aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_AAP_PROTOBUF_SERVICE_NAVIGATIONSTATUS_NAVIGATIONSTATUSSERVICE_PB_H_MAX_SIZE aap_protobuf_service_navigationstatus_NavigationStatusService_size
#define aap_protobuf_service_navigationstatus_NavigationStatusService_ImageOptions_size 33
#define aap_protobuf_service_navigationstatus_NavigationStatusService_size 48

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
