/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_COMPASSDATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_COMPASSDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_CompassData {
    int32_t bearing_e6;
    bool has_pitch_e6;
    int32_t pitch_e6;
    bool has_roll_e6;
    int32_t roll_e6;
} aap_protobuf_service_sensorsource_message_CompassData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_CompassData_init_default {0, false, 0, false, 0}
#define aap_protobuf_service_sensorsource_message_CompassData_init_zero {0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_CompassData_bearing_e6_tag 1
#define aap_protobuf_service_sensorsource_message_CompassData_pitch_e6_tag 2
#define aap_protobuf_service_sensorsource_message_CompassData_roll_e6_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_CompassData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    bearing_e6,        1) \
X(a, STATIC,   OPTIONAL, INT32,    pitch_e6,          2) \
X(a, STATIC,   OPTIONAL, INT32,    roll_e6,           3)
#define aap_protobuf_service_sensorsource_message_CompassData_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_CompassData_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_CompassData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_CompassData_fields &aap_protobuf_service_sensorsource_message_CompassData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_COMPASSDATA_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_CompassData_size
#define aap_protobuf_service_sensorsource_message_CompassData_size 33

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
