/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_DOORDATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_DOORDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_DoorData {
    bool has_hood_open;
    bool hood_open;
    bool has_trunk_open;
    bool trunk_open;
    pb_size_t door_open_count;
    bool door_open[8];
} aap_protobuf_service_sensorsource_message_DoorData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_DoorData_init_default {false, 0, false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define aap_protobuf_service_sensorsource_message_DoorData_init_zero {false, 0, false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_DoorData_hood_open_tag 1
#define aap_protobuf_service_sensorsource_message_DoorData_trunk_open_tag 2
#define aap_protobuf_service_sensorsource_message_DoorData_door_open_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_DoorData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     hood_open,         1) \
X(a, STATIC,   OPTIONAL, BOOL,     trunk_open,        2) \
X(a, STATIC,   REPEATED, BOOL,     door_open,         3)
#define aap_protobuf_service_sensorsource_message_DoorData_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_DoorData_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_DoorData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_DoorData_fields &aap_protobuf_service_sensorsource_message_DoorData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_DOORDATA_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_DoorData_size
#define aap_protobuf_service_sensorsource_message_DoorData_size 20

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
