/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_DRIVINGSTATUS_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_DRIVINGSTATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_sensorsource_message_DrivingStatus {
    aap_protobuf_service_sensorsource_message_DrivingStatus_DRIVE_STATUS_UNRESTRICTED = 0,
    aap_protobuf_service_sensorsource_message_DrivingStatus_DRIVE_STATUS_NO_VIDEO = 1,
    aap_protobuf_service_sensorsource_message_DrivingStatus_DRIVE_STATUS_NO_KEYBOARD_INPUT = 2,
    aap_protobuf_service_sensorsource_message_DrivingStatus_DRIVE_STATUS_NO_VOICE_INPUT = 4,
    aap_protobuf_service_sensorsource_message_DrivingStatus_DRIVE_STATUS_NO_CONFIG = 8,
    aap_protobuf_service_sensorsource_message_DrivingStatus_DRIVE_STATUS_LIMIT_MESSAGE_LEN = 16
} aap_protobuf_service_sensorsource_message_DrivingStatus;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_sensorsource_message_DrivingStatus_MIN aap_protobuf_service_sensorsource_message_DrivingStatus_DRIVE_STATUS_UNRESTRICTED
#define _aap_protobuf_service_sensorsource_message_DrivingStatus_MAX aap_protobuf_service_sensorsource_message_DrivingStatus_DRIVE_STATUS_LIMIT_MESSAGE_LEN
#define _aap_protobuf_service_sensorsource_message_DrivingStatus_ARRAYSIZE ((aap_protobuf_service_sensorsource_message_DrivingStatus)(aap_protobuf_service_sensorsource_message_DrivingStatus_DRIVE_STATUS_LIMIT_MESSAGE_LEN+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
