/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_EVCONNECTORTYPE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_EVCONNECTORTYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_sensorsource_message_EvConnectorType {
    aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_UNKNOWN = 0,
    aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_J1772 = 1,
    aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_MENNEKES = 2,
    aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_CHADEMO = 3,
    aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_COMBO_1 = 4,
    aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_COMBO_2 = 5,
    aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_TESLA_ROADSTER = 6,
    aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_TESLA_HPWC = 7,
    aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_TESLA_SUPERCHARGER = 8,
    aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_GBT = 9,
    aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_OTHER = 101
} aap_protobuf_service_sensorsource_message_EvConnectorType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_sensorsource_message_EvConnectorType_MIN aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_UNKNOWN
#define _aap_protobuf_service_sensorsource_message_EvConnectorType_MAX aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_OTHER
#define _aap_protobuf_service_sensorsource_message_EvConnectorType_ARRAYSIZE ((aap_protobuf_service_sensorsource_message_EvConnectorType)(aap_protobuf_service_sensorsource_message_EvConnectorType_EV_CONNECTOR_TYPE_OTHER+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
