/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_FUELTYPE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_FUELTYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_sensorsource_message_FuelType {
    aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_UNKNOWN = 0,
    aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_UNLEADED = 1,
    aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_LEADED = 2,
    aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_DIESEL_1 = 3,
    aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_DIESEL_2 = 4,
    aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_BIODIESEL = 5,
    aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_E85 = 6,
    aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_LPG = 7,
    aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_CNG = 8,
    aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_LNG = 9,
    aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_ELECTRIC = 10,
    aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_HYDROGEN = 11,
    aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_OTHER = 12
} aap_protobuf_service_sensorsource_message_FuelType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_sensorsource_message_FuelType_MIN aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_UNKNOWN
#define _aap_protobuf_service_sensorsource_message_FuelType_MAX aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_OTHER
#define _aap_protobuf_service_sensorsource_message_FuelType_ARRAYSIZE ((aap_protobuf_service_sensorsource_message_FuelType)(aap_protobuf_service_sensorsource_message_FuelType_FUEL_TYPE_OTHER+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
