/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_FUELDATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_FUELDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_FuelData {
    bool has_fuel_level;
    int32_t fuel_level;
    bool has_range;
    int32_t range;
    bool has_low_fuel_warning;
    bool low_fuel_warning;
} aap_protobuf_service_sensorsource_message_FuelData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_FuelData_init_default {false, 0, false, 0, false, 0}
#define aap_protobuf_service_sensorsource_message_FuelData_init_zero {false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_FuelData_fuel_level_tag 1
#define aap_protobuf_service_sensorsource_message_FuelData_range_tag 2
#define aap_protobuf_service_sensorsource_message_FuelData_low_fuel_warning_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_FuelData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    fuel_level,        1) \
X(a, STATIC,   OPTIONAL, INT32,    range,             2) \
X(a, STATIC,   OPTIONAL, BOOL,     low_fuel_warning,   3)
#define aap_protobuf_service_sensorsource_message_FuelData_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_FuelData_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_FuelData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_FuelData_fields &aap_protobuf_service_sensorsource_message_FuelData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_FUELDATA_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_FuelData_size
#define aap_protobuf_service_sensorsource_message_FuelData_size 24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
