/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_GEARDATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_GEARDATA_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/sensorsource/message/Gear.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_GearData {
    aap_protobuf_service_sensorsource_message_Gear gear;
} aap_protobuf_service_sensorsource_message_GearData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_GearData_init_default {_aap_protobuf_service_sensorsource_message_Gear_MIN}
#define aap_protobuf_service_sensorsource_message_GearData_init_zero {_aap_protobuf_service_sensorsource_message_Gear_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_GearData_gear_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_GearData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    gear,              1)
#define aap_protobuf_service_sensorsource_message_GearData_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_GearData_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_GearData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_GearData_fields &aap_protobuf_service_sensorsource_message_GearData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_GEARDATA_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_GearData_size
#define aap_protobuf_service_sensorsource_message_GearData_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
