/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_GPSSATELLITE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_GPSSATELLITE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_GpsSatellite {
    int32_t prn;
    int32_t snr_e3;
    bool used_in_fix;
    bool has_azimuth_e3;
    int32_t azimuth_e3;
    bool has_elevation_e3;
    int32_t elevation_e3;
} aap_protobuf_service_sensorsource_message_GpsSatellite;

typedef struct _aap_protobuf_service_sensorsource_message_GpsSatelliteData {
    int32_t number_in_use;
    bool has_number_in_view;
    int32_t number_in_view;
    pb_size_t satellites_count;
    aap_protobuf_service_sensorsource_message_GpsSatellite satellites[8];
} aap_protobuf_service_sensorsource_message_GpsSatelliteData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_GpsSatellite_init_default {0, 0, 0, false, 0, false, 0}
#define aap_protobuf_service_sensorsource_message_GpsSatelliteData_init_default {0, false, 0, 0, {aap_protobuf_service_sensorsource_message_GpsSatellite_init_default, aap_protobuf_service_sensorsource_message_GpsSatellite_init_default, aap_protobuf_service_sensorsource_message_GpsSatellite_init_default, aap_protobuf_service_sensorsource_message_GpsSatellite_init_default, aap_protobuf_service_sensorsource_message_GpsSatellite_init_default, aap_protobuf_service_sensorsource_message_GpsSatellite_init_default, aap_protobuf_service_sensorsource_message_GpsSatellite_init_default, aap_protobuf_service_sensorsource_message_GpsSatellite_init_default}}
#define aap_protobuf_service_sensorsource_message_GpsSatellite_init_zero {0, 0, 0, false, 0, false, 0}
#define aap_protobuf_service_sensorsource_message_GpsSatelliteData_init_zero {0, false, 0, 0, {aap_protobuf_service_sensorsource_message_GpsSatellite_init_zero, aap_protobuf_service_sensorsource_message_GpsSatellite_init_zero, aap_protobuf_service_sensorsource_message_GpsSatellite_init_zero, aap_protobuf_service_sensorsource_message_GpsSatellite_init_zero, aap_protobuf_service_sensorsource_message_GpsSatellite_init_zero, aap_protobuf_service_sensorsource_message_GpsSatellite_init_zero, aap_protobuf_service_sensorsource_message_GpsSatellite_init_zero, aap_protobuf_service_sensorsource_message_GpsSatellite_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_GpsSatellite_prn_tag 1
#define aap_protobuf_service_sensorsource_message_GpsSatellite_snr_e3_tag 2
#define aap_protobuf_service_sensorsource_message_GpsSatellite_used_in_fix_tag 3
#define aap_protobuf_service_sensorsource_message_GpsSatellite_azimuth_e3_tag 4
#define aap_protobuf_service_sensorsource_message_GpsSatellite_elevation_e3_tag 5
#define aap_protobuf_service_sensorsource_message_GpsSatelliteData_number_in_use_tag 1
#define aap_protobuf_service_sensorsource_message_GpsSatelliteData_number_in_view_tag 2
#define aap_protobuf_service_sensorsource_message_GpsSatelliteData_satellites_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_GpsSatellite_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    prn,               1) \
X(a, STATIC,   REQUIRED, INT32,    snr_e3,            2) \
X(a, STATIC,   REQUIRED, BOOL,     used_in_fix,       3) \
X(a, STATIC,   OPTIONAL, INT32,    azimuth_e3,        4) \
X(a, STATIC,   OPTIONAL, INT32,    elevation_e3,      5)
#define aap_protobuf_service_sensorsource_message_GpsSatellite_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_GpsSatellite_DEFAULT NULL

#define aap_protobuf_service_sensorsource_message_GpsSatelliteData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    number_in_use,     1) \
X(a, STATIC,   OPTIONAL, INT32,    number_in_view,    2) \
X(a, STATIC,   REPEATED, MESSAGE,  satellites,        3)
#define aap_protobuf_service_sensorsource_message_GpsSatelliteData_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_GpsSatelliteData_DEFAULT NULL
#define aap_protobuf_service_sensorsource_message_GpsSatelliteData_satellites_MSGTYPE aap_protobuf_service_sensorsource_message_GpsSatellite

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_GpsSatellite_msg;
extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_GpsSatelliteData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_GpsSatellite_fields &aap_protobuf_service_sensorsource_message_GpsSatellite_msg
#define aap_protobuf_service_sensorsource_message_GpsSatelliteData_fields &aap_protobuf_service_sensorsource_message_GpsSatelliteData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_GPSSATELLITE_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_GpsSatelliteData_size
#define aap_protobuf_service_sensorsource_message_GpsSatelliteData_size 406
#define aap_protobuf_service_sensorsource_message_GpsSatellite_size 46

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
