/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_GYROSCOPEDATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_GYROSCOPEDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_GyroscopeData {
    bool has_rotation_speed_x_e3;
    int32_t rotation_speed_x_e3;
    bool has_rotation_speed_y_e3;
    int32_t rotation_speed_y_e3;
    bool has_rotation_speed_z_e3;
    int32_t rotation_speed_z_e3;
} aap_protobuf_service_sensorsource_message_GyroscopeData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_GyroscopeData_init_default {false, 0, false, 0, false, 0}
#define aap_protobuf_service_sensorsource_message_GyroscopeData_init_zero {false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_GyroscopeData_rotation_speed_x_e3_tag 1
#define aap_protobuf_service_sensorsource_message_GyroscopeData_rotation_speed_y_e3_tag 2
#define aap_protobuf_service_sensorsource_message_GyroscopeData_rotation_speed_z_e3_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_GyroscopeData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    rotation_speed_x_e3,   1) \
X(a, STATIC,   OPTIONAL, INT32,    rotation_speed_y_e3,   2) \
X(a, STATIC,   OPTIONAL, INT32,    rotation_speed_z_e3,   3)
#define aap_protobuf_service_sensorsource_message_GyroscopeData_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_GyroscopeData_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_GyroscopeData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_GyroscopeData_fields &aap_protobuf_service_sensorsource_message_GyroscopeData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_GYROSCOPEDATA_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_GyroscopeData_size
#define aap_protobuf_service_sensorsource_message_GyroscopeData_size 33

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
