/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_HEADLIGHTSTATE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_HEADLIGHTSTATE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_sensorsource_message_HeadLightState {
    aap_protobuf_service_sensorsource_message_HeadLightState_HEAD_LIGHT_STATE_OFF = 1,
    aap_protobuf_service_sensorsource_message_HeadLightState_HEAD_LIGHT_STATE_ON = 2,
    aap_protobuf_service_sensorsource_message_HeadLightState_HEAD_LIGHT_STATE_HIGH = 3
} aap_protobuf_service_sensorsource_message_HeadLightState;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_sensorsource_message_HeadLightState_MIN aap_protobuf_service_sensorsource_message_HeadLightState_HEAD_LIGHT_STATE_OFF
#define _aap_protobuf_service_sensorsource_message_HeadLightState_MAX aap_protobuf_service_sensorsource_message_HeadLightState_HEAD_LIGHT_STATE_HIGH
#define _aap_protobuf_service_sensorsource_message_HeadLightState_ARRAYSIZE ((aap_protobuf_service_sensorsource_message_HeadLightState)(aap_protobuf_service_sensorsource_message_HeadLightState_HEAD_LIGHT_STATE_HIGH+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
