/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_LIGHTDATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_LIGHTDATA_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/sensorsource/message/HeadLightState.pb.h"
#include "aap_protobuf/service/sensorsource/message/TurnIndicatorState.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_LightData {
    bool has_head_light_state;
    aap_protobuf_service_sensorsource_message_HeadLightState head_light_state;
    bool has_turn_indicator_state;
    aap_protobuf_service_sensorsource_message_TurnIndicatorState turn_indicator_state;
    bool has_hazard_lights_on;
    bool hazard_lights_on;
} aap_protobuf_service_sensorsource_message_LightData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_LightData_init_default {false, _aap_protobuf_service_sensorsource_message_HeadLightState_MIN, false, _aap_protobuf_service_sensorsource_message_TurnIndicatorState_MIN, false, 0}
#define aap_protobuf_service_sensorsource_message_LightData_init_zero {false, _aap_protobuf_service_sensorsource_message_HeadLightState_MIN, false, _aap_protobuf_service_sensorsource_message_TurnIndicatorState_MIN, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_LightData_head_light_state_tag 1
#define aap_protobuf_service_sensorsource_message_LightData_turn_indicator_state_tag 2
#define aap_protobuf_service_sensorsource_message_LightData_hazard_lights_on_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_LightData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    head_light_state,   1) \
X(a, STATIC,   OPTIONAL, UENUM,    turn_indicator_state,   2) \
X(a, STATIC,   OPTIONAL, BOOL,     hazard_lights_on,   3)
#define aap_protobuf_service_sensorsource_message_LightData_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_LightData_DEFAULT (const pb_byte_t*)"\x08\x01\x10\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_LightData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_LightData_fields &aap_protobuf_service_sensorsource_message_LightData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_LIGHTDATA_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_LightData_size
#define aap_protobuf_service_sensorsource_message_LightData_size 6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
