/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_LOCATIONDATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_LOCATIONDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_LocationData {
    bool has_timestamp;
    uint64_t timestamp;
    int32_t latitude_e7;
    int32_t longitude_e7;
    bool has_accuracy_e3;
    uint32_t accuracy_e3;
    bool has_altitude_e2;
    int32_t altitude_e2;
    bool has_speed_e3;
    int32_t speed_e3;
    bool has_bearing_e6;
    int32_t bearing_e6;
} aap_protobuf_service_sensorsource_message_LocationData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_LocationData_init_default {false, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}
#define aap_protobuf_service_sensorsource_message_LocationData_init_zero {false, 0, 0, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_LocationData_timestamp_tag 1
#define aap_protobuf_service_sensorsource_message_LocationData_latitude_e7_tag 2
#define aap_protobuf_service_sensorsource_message_LocationData_longitude_e7_tag 3
#define aap_protobuf_service_sensorsource_message_LocationData_accuracy_e3_tag 4
#define aap_protobuf_service_sensorsource_message_LocationData_altitude_e2_tag 5
#define aap_protobuf_service_sensorsource_message_LocationData_speed_e3_tag 6
#define aap_protobuf_service_sensorsource_message_LocationData_bearing_e6_tag 7

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_LocationData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, INT32,    latitude_e7,       2) \
X(a, STATIC,   REQUIRED, INT32,    longitude_e7,      3) \
X(a, STATIC,   OPTIONAL, UINT32,   accuracy_e3,       4) \
X(a, STATIC,   OPTIONAL, INT32,    altitude_e2,       5) \
X(a, STATIC,   OPTIONAL, INT32,    speed_e3,          6) \
X(a, STATIC,   OPTIONAL, INT32,    bearing_e6,        7)
#define aap_protobuf_service_sensorsource_message_LocationData_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_LocationData_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_LocationData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_LocationData_fields &aap_protobuf_service_sensorsource_message_LocationData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_LOCATIONDATA_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_LocationData_size
#define aap_protobuf_service_sensorsource_message_LocationData_size 72

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
