/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_NIGHTMODEDATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_NIGHTMODEDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_NightModeData {
    bool has_night_mode;
    bool night_mode;
} aap_protobuf_service_sensorsource_message_NightModeData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_NightModeData_init_default {false, 0}
#define aap_protobuf_service_sensorsource_message_NightModeData_init_zero {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_NightModeData_night_mode_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_NightModeData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     night_mode,        1)
#define aap_protobuf_service_sensorsource_message_NightModeData_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_NightModeData_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_NightModeData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_NightModeData_fields &aap_protobuf_service_sensorsource_message_NightModeData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_NIGHTMODEDATA_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_NightModeData_size
#define aap_protobuf_service_sensorsource_message_NightModeData_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
