/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_ODOMETERDATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_ODOMETERDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_OdometerData {
    int32_t kms_e1;
    bool has_trip_kms_e1;
    int32_t trip_kms_e1;
} aap_protobuf_service_sensorsource_message_OdometerData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_OdometerData_init_default {0, false, 0}
#define aap_protobuf_service_sensorsource_message_OdometerData_init_zero {0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_OdometerData_kms_e1_tag 1
#define aap_protobuf_service_sensorsource_message_OdometerData_trip_kms_e1_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_OdometerData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    kms_e1,            1) \
X(a, STATIC,   OPTIONAL, INT32,    trip_kms_e1,       2)
#define aap_protobuf_service_sensorsource_message_OdometerData_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_OdometerData_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_OdometerData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_OdometerData_fields &aap_protobuf_service_sensorsource_message_OdometerData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_ODOMETERDATA_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_OdometerData_size
#define aap_protobuf_service_sensorsource_message_OdometerData_size 22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
