/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_PARKINGBRAKEDATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_PARKINGBRAKEDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_ParkingBrakeData {
    bool parking_brake;
} aap_protobuf_service_sensorsource_message_ParkingBrakeData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_ParkingBrakeData_init_default {0}
#define aap_protobuf_service_sensorsource_message_ParkingBrakeData_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_ParkingBrakeData_parking_brake_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_ParkingBrakeData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     parking_brake,     1)
#define aap_protobuf_service_sensorsource_message_ParkingBrakeData_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_ParkingBrakeData_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_ParkingBrakeData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_ParkingBrakeData_fields &aap_protobuf_service_sensorsource_message_ParkingBrakeData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_PARKINGBRAKEDATA_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_ParkingBrakeData_size
#define aap_protobuf_service_sensorsource_message_ParkingBrakeData_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
