/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_SENSORERROR_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_SENSORERROR_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/sensorsource/message/SensorType.pb.h"
#include "aap_protobuf/service/sensorsource/message/SensorErrorType.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_SensorError {
    aap_protobuf_service_sensorsource_message_SensorType sensor_type;
    aap_protobuf_service_sensorsource_message_SensorErrorType sensor_error_type;
} aap_protobuf_service_sensorsource_message_SensorError;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_SensorError_init_default {_aap_protobuf_service_sensorsource_message_SensorType_MIN, _aap_protobuf_service_sensorsource_message_SensorErrorType_MIN}
#define aap_protobuf_service_sensorsource_message_SensorError_init_zero {_aap_protobuf_service_sensorsource_message_SensorType_MIN, _aap_protobuf_service_sensorsource_message_SensorErrorType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_SensorError_sensor_type_tag 1
#define aap_protobuf_service_sensorsource_message_SensorError_sensor_error_type_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_SensorError_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    sensor_type,       1) \
X(a, STATIC,   REQUIRED, UENUM,    sensor_error_type,   2)
#define aap_protobuf_service_sensorsource_message_SensorError_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_SensorError_DEFAULT (const pb_byte_t*)"\x08\x01\x10\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_SensorError_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_SensorError_fields &aap_protobuf_service_sensorsource_message_SensorError_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_SENSORERROR_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_SensorError_size
#define aap_protobuf_service_sensorsource_message_SensorError_size 4

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
