/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_SENSORREQUEST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_SENSORREQUEST_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/sensorsource/message/SensorType.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_SensorRequest {
    aap_protobuf_service_sensorsource_message_SensorType type;
    int64_t min_update_period;
} aap_protobuf_service_sensorsource_message_SensorRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_SensorRequest_init_default {_aap_protobuf_service_sensorsource_message_SensorType_MIN, 0}
#define aap_protobuf_service_sensorsource_message_SensorRequest_init_zero {_aap_protobuf_service_sensorsource_message_SensorType_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_SensorRequest_type_tag 1
#define aap_protobuf_service_sensorsource_message_SensorRequest_min_update_period_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_SensorRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, STATIC,   REQUIRED, INT64,    min_update_period,   2)
#define aap_protobuf_service_sensorsource_message_SensorRequest_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_SensorRequest_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_SensorRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_SensorRequest_fields &aap_protobuf_service_sensorsource_message_SensorRequest_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_SENSORREQUEST_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_SensorRequest_size
#define aap_protobuf_service_sensorsource_message_SensorRequest_size 13

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
