/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_SENSORERRORTYPE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_SENSORERRORTYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_sensorsource_message_SensorErrorType {
    aap_protobuf_service_sensorsource_message_SensorErrorType_SENSOR_OK = 1,
    aap_protobuf_service_sensorsource_message_SensorErrorType_SENSOR_ERROR_TRANSIENT = 2,
    aap_protobuf_service_sensorsource_message_SensorErrorType_SENSOR_ERROR_PERMANENT = 3
} aap_protobuf_service_sensorsource_message_SensorErrorType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_sensorsource_message_SensorErrorType_MIN aap_protobuf_service_sensorsource_message_SensorErrorType_SENSOR_OK
#define _aap_protobuf_service_sensorsource_message_SensorErrorType_MAX aap_protobuf_service_sensorsource_message_SensorErrorType_SENSOR_ERROR_PERMANENT
#define _aap_protobuf_service_sensorsource_message_SensorErrorType_ARRAYSIZE ((aap_protobuf_service_sensorsource_message_SensorErrorType)(aap_protobuf_service_sensorsource_message_SensorErrorType_SENSOR_ERROR_PERMANENT+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
