/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_SPEEDDATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_SPEEDDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_SpeedData {
    int32_t speed_e3;
    bool has_cruise_engaged;
    bool cruise_engaged;
    bool has_cruise_set_speed;
    int32_t cruise_set_speed;
} aap_protobuf_service_sensorsource_message_SpeedData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_SpeedData_init_default {0, false, 0, false, 0}
#define aap_protobuf_service_sensorsource_message_SpeedData_init_zero {0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_SpeedData_speed_e3_tag 1
#define aap_protobuf_service_sensorsource_message_SpeedData_cruise_engaged_tag 2
#define aap_protobuf_service_sensorsource_message_SpeedData_cruise_set_speed_tag 4

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_SpeedData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    speed_e3,          1) \
X(a, STATIC,   OPTIONAL, BOOL,     cruise_engaged,    2) \
X(a, STATIC,   OPTIONAL, INT32,    cruise_set_speed,   4)
#define aap_protobuf_service_sensorsource_message_SpeedData_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_SpeedData_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_SpeedData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_SpeedData_fields &aap_protobuf_service_sensorsource_message_SpeedData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_SPEEDDATA_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_SpeedData_size
#define aap_protobuf_service_sensorsource_message_SpeedData_size 24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
