/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_TIREPRESSUREDATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_TIREPRESSUREDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_sensorsource_message_TirePressureData {
    pb_size_t tire_pressures_e2_count;
    int32_t tire_pressures_e2[8];
} aap_protobuf_service_sensorsource_message_TirePressureData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_sensorsource_message_TirePressureData_init_default {0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define aap_protobuf_service_sensorsource_message_TirePressureData_init_zero {0, {0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_sensorsource_message_TirePressureData_tire_pressures_e2_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_sensorsource_message_TirePressureData_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, INT32,    tire_pressures_e2,   1)
#define aap_protobuf_service_sensorsource_message_TirePressureData_CALLBACK NULL
#define aap_protobuf_service_sensorsource_message_TirePressureData_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_sensorsource_message_TirePressureData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_sensorsource_message_TirePressureData_fields &aap_protobuf_service_sensorsource_message_TirePressureData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_TIREPRESSUREDATA_PB_H_MAX_SIZE aap_protobuf_service_sensorsource_message_TirePressureData_size
#define aap_protobuf_service_sensorsource_message_TirePressureData_size 88

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
