/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_TURNINDICATORSTATE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_SENSORSOURCE_MESSAGE_TURNINDICATORSTATE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_sensorsource_message_TurnIndicatorState {
    aap_protobuf_service_sensorsource_message_TurnIndicatorState_TURN_INDICATOR_NONE = 1,
    aap_protobuf_service_sensorsource_message_TurnIndicatorState_TURN_INDICATOR_LEFT = 2,
    aap_protobuf_service_sensorsource_message_TurnIndicatorState_TURN_INDICATOR_RIGHT = 3
} aap_protobuf_service_sensorsource_message_TurnIndicatorState;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_sensorsource_message_TurnIndicatorState_MIN aap_protobuf_service_sensorsource_message_TurnIndicatorState_TURN_INDICATOR_NONE
#define _aap_protobuf_service_sensorsource_message_TurnIndicatorState_MAX aap_protobuf_service_sensorsource_message_TurnIndicatorState_TURN_INDICATOR_RIGHT
#define _aap_protobuf_service_sensorsource_message_TurnIndicatorState_ARRAYSIZE ((aap_protobuf_service_sensorsource_message_TurnIndicatorState)(aap_protobuf_service_sensorsource_message_TurnIndicatorState_TURN_INDICATOR_RIGHT+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
