/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIALIST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIALIST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_mediabrowser_message_MediaList_Type {
    aap_protobuf_service_mediabrowser_message_MediaList_Type_UNKNOWN = 0,
    aap_protobuf_service_mediabrowser_message_MediaList_Type_PLAYLIST = 1,
    aap_protobuf_service_mediabrowser_message_MediaList_Type_ALBUM = 2,
    aap_protobuf_service_mediabrowser_message_MediaList_Type_ARTIST = 3,
    aap_protobuf_service_mediabrowser_message_MediaList_Type_STATION = 4,
    aap_protobuf_service_mediabrowser_message_MediaList_Type_GENRE = 5
} aap_protobuf_service_mediabrowser_message_MediaList_Type;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_mediabrowser_message_MediaList_album_art_t;
typedef struct _aap_protobuf_service_mediabrowser_message_MediaList {
    char path[64];
    aap_protobuf_service_mediabrowser_message_MediaList_Type type;
    bool has_name;
    char name[64];
    bool has_album_art;
    aap_protobuf_service_mediabrowser_message_MediaList_album_art_t album_art;
} aap_protobuf_service_mediabrowser_message_MediaList;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_mediabrowser_message_MediaList_Type_MIN aap_protobuf_service_mediabrowser_message_MediaList_Type_UNKNOWN
#define _aap_protobuf_service_mediabrowser_message_MediaList_Type_MAX aap_protobuf_service_mediabrowser_message_MediaList_Type_GENRE
#define _aap_protobuf_service_mediabrowser_message_MediaList_Type_ARRAYSIZE ((aap_protobuf_service_mediabrowser_message_MediaList_Type)(aap_protobuf_service_mediabrowser_message_MediaList_Type_GENRE+1))

#define aap_protobuf_service_mediabrowser_message_MediaList_type_ENUMTYPE aap_protobuf_service_mediabrowser_message_MediaList_Type


/* Initializer values for message structs */
#define aap_protobuf_service_mediabrowser_message_MediaList_init_default {"", _aap_protobuf_service_mediabrowser_message_MediaList_Type_MIN, false, "", false, {0, {0}}}
#define aap_protobuf_service_mediabrowser_message_MediaList_init_zero {"", _aap_protobuf_service_mediabrowser_message_MediaList_Type_MIN, false, "", false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_mediabrowser_message_MediaList_path_tag 1
#define aap_protobuf_service_mediabrowser_message_MediaList_type_tag 2
#define aap_protobuf_service_mediabrowser_message_MediaList_name_tag 3
#define aap_protobuf_service_mediabrowser_message_MediaList_album_art_tag 4

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_mediabrowser_message_MediaList_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   path,              1) \
X(a, STATIC,   REQUIRED, UENUM,    type,              2) \
X(a, STATIC,   OPTIONAL, STRING,   name,              3) \
X(a, STATIC,   OPTIONAL, BYTES,    album_art,         4)
#define aap_protobuf_service_mediabrowser_message_MediaList_CALLBACK NULL
#define aap_protobuf_service_mediabrowser_message_MediaList_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_mediabrowser_message_MediaList_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_mediabrowser_message_MediaList_fields &aap_protobuf_service_mediabrowser_message_MediaList_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIALIST_PB_H_MAX_SIZE aap_protobuf_service_mediabrowser_message_MediaList_size
#define aap_protobuf_service_mediabrowser_message_MediaList_size 198

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
