/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIASONGNODE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIASONGNODE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/mediabrowser/message/MediaSong.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_mediabrowser_message_MediaSongNode_album_art_t;
typedef struct _aap_protobuf_service_mediabrowser_message_MediaSongNode {
    aap_protobuf_service_mediabrowser_message_MediaSong song;
    bool has_album_art;
    aap_protobuf_service_mediabrowser_message_MediaSongNode_album_art_t album_art;
    bool has_duration_seconds;
    uint32_t duration_seconds;
} aap_protobuf_service_mediabrowser_message_MediaSongNode;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_mediabrowser_message_MediaSongNode_init_default {aap_protobuf_service_mediabrowser_message_MediaSong_init_default, false, {0, {0}}, false, 0}
#define aap_protobuf_service_mediabrowser_message_MediaSongNode_init_zero {aap_protobuf_service_mediabrowser_message_MediaSong_init_zero, false, {0, {0}}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_mediabrowser_message_MediaSongNode_song_tag 1
#define aap_protobuf_service_mediabrowser_message_MediaSongNode_album_art_tag 2
#define aap_protobuf_service_mediabrowser_message_MediaSongNode_duration_seconds_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_mediabrowser_message_MediaSongNode_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  song,              1) \
X(a, STATIC,   OPTIONAL, BYTES,    album_art,         2) \
X(a, STATIC,   OPTIONAL, UINT32,   duration_seconds,   3)
#define aap_protobuf_service_mediabrowser_message_MediaSongNode_CALLBACK NULL
#define aap_protobuf_service_mediabrowser_message_MediaSongNode_DEFAULT NULL
#define aap_protobuf_service_mediabrowser_message_MediaSongNode_song_MSGTYPE aap_protobuf_service_mediabrowser_message_MediaSong

extern const pb_msgdesc_t aap_protobuf_service_mediabrowser_message_MediaSongNode_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_mediabrowser_message_MediaSongNode_fields &aap_protobuf_service_mediabrowser_message_MediaSongNode_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIASONGNODE_PB_H_MAX_SIZE aap_protobuf_service_mediabrowser_message_MediaSongNode_size
#define aap_protobuf_service_mediabrowser_message_MediaSongNode_size 335

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
