/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIAGETNODE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIAGETNODE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_mediabrowser_message_MediaGetNode {
    char path[64];
    bool has_start;
    int32_t start;
    bool has_get_album_art;
    bool get_album_art;
} aap_protobuf_service_mediabrowser_message_MediaGetNode;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_mediabrowser_message_MediaGetNode_init_default {"", false, 0, false, true}
#define aap_protobuf_service_mediabrowser_message_MediaGetNode_init_zero {"", false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_mediabrowser_message_MediaGetNode_path_tag 1
#define aap_protobuf_service_mediabrowser_message_MediaGetNode_start_tag 2
#define aap_protobuf_service_mediabrowser_message_MediaGetNode_get_album_art_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_mediabrowser_message_MediaGetNode_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   path,              1) \
X(a, STATIC,   OPTIONAL, INT32,    start,             2) \
X(a, STATIC,   OPTIONAL, BOOL,     get_album_art,     3)
#define aap_protobuf_service_mediabrowser_message_MediaGetNode_CALLBACK NULL
#define aap_protobuf_service_mediabrowser_message_MediaGetNode_DEFAULT (const pb_byte_t*)"\x18\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_mediabrowser_message_MediaGetNode_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_mediabrowser_message_MediaGetNode_fields &aap_protobuf_service_mediabrowser_message_MediaGetNode_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIAGETNODE_PB_H_MAX_SIZE aap_protobuf_service_mediabrowser_message_MediaGetNode_size
#define aap_protobuf_service_mediabrowser_message_MediaGetNode_size 78

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
