/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIAROOTNODE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIAROOTNODE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/mediabrowser/message/MediaSource.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_mediabrowser_message_MediaRootNode {
    char path[64];
    pb_size_t media_sources_count;
    aap_protobuf_service_mediabrowser_message_MediaSource media_sources[8];
} aap_protobuf_service_mediabrowser_message_MediaRootNode;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_mediabrowser_message_MediaRootNode_init_default {"", 0, {aap_protobuf_service_mediabrowser_message_MediaSource_init_default, aap_protobuf_service_mediabrowser_message_MediaSource_init_default, aap_protobuf_service_mediabrowser_message_MediaSource_init_default, aap_protobuf_service_mediabrowser_message_MediaSource_init_default, aap_protobuf_service_mediabrowser_message_MediaSource_init_default, aap_protobuf_service_mediabrowser_message_MediaSource_init_default, aap_protobuf_service_mediabrowser_message_MediaSource_init_default, aap_protobuf_service_mediabrowser_message_MediaSource_init_default}}
#define aap_protobuf_service_mediabrowser_message_MediaRootNode_init_zero {"", 0, {aap_protobuf_service_mediabrowser_message_MediaSource_init_zero, aap_protobuf_service_mediabrowser_message_MediaSource_init_zero, aap_protobuf_service_mediabrowser_message_MediaSource_init_zero, aap_protobuf_service_mediabrowser_message_MediaSource_init_zero, aap_protobuf_service_mediabrowser_message_MediaSource_init_zero, aap_protobuf_service_mediabrowser_message_MediaSource_init_zero, aap_protobuf_service_mediabrowser_message_MediaSource_init_zero, aap_protobuf_service_mediabrowser_message_MediaSource_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_mediabrowser_message_MediaRootNode_path_tag 1
#define aap_protobuf_service_mediabrowser_message_MediaRootNode_media_sources_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_mediabrowser_message_MediaRootNode_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   path,              1) \
X(a, STATIC,   REPEATED, MESSAGE,  media_sources,     2)
#define aap_protobuf_service_mediabrowser_message_MediaRootNode_CALLBACK NULL
#define aap_protobuf_service_mediabrowser_message_MediaRootNode_DEFAULT NULL
#define aap_protobuf_service_mediabrowser_message_MediaRootNode_media_sources_MSGTYPE aap_protobuf_service_mediabrowser_message_MediaSource

extern const pb_msgdesc_t aap_protobuf_service_mediabrowser_message_MediaRootNode_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_mediabrowser_message_MediaRootNode_fields &aap_protobuf_service_mediabrowser_message_MediaRootNode_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIAROOTNODE_PB_H_MAX_SIZE aap_protobuf_service_mediabrowser_message_MediaRootNode_size
#define aap_protobuf_service_mediabrowser_message_MediaRootNode_size 1657

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
