/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIASONG_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIASONG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_mediabrowser_message_MediaSong {
    char path[64];
    char name[64];
    bool has_artist;
    char artist[64];
    bool has_album;
    char album[64];
} aap_protobuf_service_mediabrowser_message_MediaSong;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_mediabrowser_message_MediaSong_init_default {"", "", false, "", false, ""}
#define aap_protobuf_service_mediabrowser_message_MediaSong_init_zero {"", "", false, "", false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_mediabrowser_message_MediaSong_path_tag 1
#define aap_protobuf_service_mediabrowser_message_MediaSong_name_tag 2
#define aap_protobuf_service_mediabrowser_message_MediaSong_artist_tag 3
#define aap_protobuf_service_mediabrowser_message_MediaSong_album_tag 4

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_mediabrowser_message_MediaSong_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   path,              1) \
X(a, STATIC,   REQUIRED, STRING,   name,              2) \
X(a, STATIC,   OPTIONAL, STRING,   artist,            3) \
X(a, STATIC,   OPTIONAL, STRING,   album,             4)
#define aap_protobuf_service_mediabrowser_message_MediaSong_CALLBACK NULL
#define aap_protobuf_service_mediabrowser_message_MediaSong_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_mediabrowser_message_MediaSong_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_mediabrowser_message_MediaSong_fields &aap_protobuf_service_mediabrowser_message_MediaSong_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIASONG_PB_H_MAX_SIZE aap_protobuf_service_mediabrowser_message_MediaSong_size
#define aap_protobuf_service_mediabrowser_message_MediaSong_size 260

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
