/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIABROWSERINPUT_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIABROWSERINPUT_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/shared/InstrumentClusterInput.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_mediabrowser_message_MediaBrowserInput {
    aap_protobuf_shared_InstrumentClusterInput input;
    char path[64];
} aap_protobuf_service_mediabrowser_message_MediaBrowserInput;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_mediabrowser_message_MediaBrowserInput_init_default {aap_protobuf_shared_InstrumentClusterInput_init_default, ""}
#define aap_protobuf_service_mediabrowser_message_MediaBrowserInput_init_zero {aap_protobuf_shared_InstrumentClusterInput_init_zero, ""}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_mediabrowser_message_MediaBrowserInput_input_tag 1
#define aap_protobuf_service_mediabrowser_message_MediaBrowserInput_path_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_mediabrowser_message_MediaBrowserInput_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  input,             1) \
X(a, STATIC,   REQUIRED, STRING,   path,              2)
#define aap_protobuf_service_mediabrowser_message_MediaBrowserInput_CALLBACK NULL
#define aap_protobuf_service_mediabrowser_message_MediaBrowserInput_DEFAULT NULL
#define aap_protobuf_service_mediabrowser_message_MediaBrowserInput_input_MSGTYPE aap_protobuf_shared_InstrumentClusterInput

extern const pb_msgdesc_t aap_protobuf_service_mediabrowser_message_MediaBrowserInput_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_mediabrowser_message_MediaBrowserInput_fields &aap_protobuf_service_mediabrowser_message_MediaBrowserInput_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIABROWSER_MESSAGE_MEDIABROWSERINPUT_PB_H_MAX_SIZE aap_protobuf_service_mediabrowser_message_MediaBrowserInput_size
#define aap_protobuf_service_mediabrowser_message_MediaBrowserInput_size 69

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
