/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_ACTIVERADIONOTIFICATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_ACTIVERADIONOTIFICATION_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/shared/MessageStatus.pb.h"
#include "aap_protobuf/service/radio/message/RadioStationInfo.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_ActiveRadioNotification {
    bool has_status;
    aap_protobuf_shared_MessageStatus status;
    int32_t radio_id;
    bool has_station_info;
    aap_protobuf_service_radio_message_RadioStationInfo station_info;
} aap_protobuf_service_radio_message_ActiveRadioNotification;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_ActiveRadioNotification_init_default {false, _aap_protobuf_shared_MessageStatus_MIN, 0, false, aap_protobuf_service_radio_message_RadioStationInfo_init_default}
#define aap_protobuf_service_radio_message_ActiveRadioNotification_init_zero {false, _aap_protobuf_shared_MessageStatus_MIN, 0, false, aap_protobuf_service_radio_message_RadioStationInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_ActiveRadioNotification_status_tag 1
#define aap_protobuf_service_radio_message_ActiveRadioNotification_radio_id_tag 2
#define aap_protobuf_service_radio_message_ActiveRadioNotification_station_info_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_ActiveRadioNotification_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, ENUM,     status,            1) \
X(a, STATIC,   REQUIRED, INT32,    radio_id,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  station_info,      3)
#define aap_protobuf_service_radio_message_ActiveRadioNotification_CALLBACK NULL
#define aap_protobuf_service_radio_message_ActiveRadioNotification_DEFAULT (const pb_byte_t*)"\x08\x01\x00"
#define aap_protobuf_service_radio_message_ActiveRadioNotification_station_info_MSGTYPE aap_protobuf_service_radio_message_RadioStationInfo

extern const pb_msgdesc_t aap_protobuf_service_radio_message_ActiveRadioNotification_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_ActiveRadioNotification_fields &aap_protobuf_service_radio_message_ActiveRadioNotification_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_ACTIVERADIONOTIFICATION_PB_H_MAX_SIZE aap_protobuf_service_radio_message_ActiveRadioNotification_size
#define aap_protobuf_service_radio_message_ActiveRadioNotification_size 1586

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
