/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_CANCELRADIOOPERATIONSRESPONSE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_CANCELRADIOOPERATIONSRESPONSE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/shared/MessageStatus.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_CancelRadioOperationsResponse {
    aap_protobuf_shared_MessageStatus status;
    int32_t radio_id;
} aap_protobuf_service_radio_message_CancelRadioOperationsResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_CancelRadioOperationsResponse_init_default {_aap_protobuf_shared_MessageStatus_MIN, 0}
#define aap_protobuf_service_radio_message_CancelRadioOperationsResponse_init_zero {_aap_protobuf_shared_MessageStatus_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_CancelRadioOperationsResponse_status_tag 1
#define aap_protobuf_service_radio_message_CancelRadioOperationsResponse_radio_id_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_CancelRadioOperationsResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, ENUM,     status,            1) \
X(a, STATIC,   REQUIRED, INT32,    radio_id,          2)
#define aap_protobuf_service_radio_message_CancelRadioOperationsResponse_CALLBACK NULL
#define aap_protobuf_service_radio_message_CancelRadioOperationsResponse_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_radio_message_CancelRadioOperationsResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_CancelRadioOperationsResponse_fields &aap_protobuf_service_radio_message_CancelRadioOperationsResponse_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_CANCELRADIOOPERATIONSRESPONSE_PB_H_MAX_SIZE aap_protobuf_service_radio_message_CancelRadioOperationsResponse_size
#define aap_protobuf_service_radio_message_CancelRadioOperationsResponse_size 22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
