/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_GETTRAFFICUPDATERESPONSE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_GETTRAFFICUPDATERESPONSE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/shared/MessageStatus.pb.h"
#include "aap_protobuf/service/radio/message/TrafficIncident.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_GetTrafficUpdateResponse {
    aap_protobuf_shared_MessageStatus status;
    int32_t radio_id;
    pb_size_t incidents_count;
    aap_protobuf_service_radio_message_TrafficIncident incidents[8];
} aap_protobuf_service_radio_message_GetTrafficUpdateResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_GetTrafficUpdateResponse_init_default {_aap_protobuf_shared_MessageStatus_MIN, 0, 0, {aap_protobuf_service_radio_message_TrafficIncident_init_default, aap_protobuf_service_radio_message_TrafficIncident_init_default, aap_protobuf_service_radio_message_TrafficIncident_init_default, aap_protobuf_service_radio_message_TrafficIncident_init_default, aap_protobuf_service_radio_message_TrafficIncident_init_default, aap_protobuf_service_radio_message_TrafficIncident_init_default, aap_protobuf_service_radio_message_TrafficIncident_init_default, aap_protobuf_service_radio_message_TrafficIncident_init_default}}
#define aap_protobuf_service_radio_message_GetTrafficUpdateResponse_init_zero {_aap_protobuf_shared_MessageStatus_MIN, 0, 0, {aap_protobuf_service_radio_message_TrafficIncident_init_zero, aap_protobuf_service_radio_message_TrafficIncident_init_zero, aap_protobuf_service_radio_message_TrafficIncident_init_zero, aap_protobuf_service_radio_message_TrafficIncident_init_zero, aap_protobuf_service_radio_message_TrafficIncident_init_zero, aap_protobuf_service_radio_message_TrafficIncident_init_zero, aap_protobuf_service_radio_message_TrafficIncident_init_zero, aap_protobuf_service_radio_message_TrafficIncident_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_GetTrafficUpdateResponse_status_tag 1
#define aap_protobuf_service_radio_message_GetTrafficUpdateResponse_radio_id_tag 2
#define aap_protobuf_service_radio_message_GetTrafficUpdateResponse_incidents_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_GetTrafficUpdateResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, ENUM,     status,            1) \
X(a, STATIC,   REQUIRED, INT32,    radio_id,          2) \
X(a, STATIC,   REPEATED, MESSAGE,  incidents,         3)
#define aap_protobuf_service_radio_message_GetTrafficUpdateResponse_CALLBACK NULL
#define aap_protobuf_service_radio_message_GetTrafficUpdateResponse_DEFAULT (const pb_byte_t*)"\x08\x01\x00"
#define aap_protobuf_service_radio_message_GetTrafficUpdateResponse_incidents_MSGTYPE aap_protobuf_service_radio_message_TrafficIncident

extern const pb_msgdesc_t aap_protobuf_service_radio_message_GetTrafficUpdateResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_GetTrafficUpdateResponse_fields &aap_protobuf_service_radio_message_GetTrafficUpdateResponse_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_GETTRAFFICUPDATERESPONSE_PB_H_MAX_SIZE aap_protobuf_service_radio_message_GetTrafficUpdateResponse_size
#define aap_protobuf_service_radio_message_GetTrafficUpdateResponse_size 374

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
