/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOCOMMENT_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOCOMMENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_HdRadioComment {
    bool has_description;
    char description[64];
    bool has_text;
    char text[64];
} aap_protobuf_service_radio_message_HdRadioComment;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_HdRadioComment_init_default {false, "", false, ""}
#define aap_protobuf_service_radio_message_HdRadioComment_init_zero {false, "", false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_HdRadioComment_description_tag 1
#define aap_protobuf_service_radio_message_HdRadioComment_text_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_HdRadioComment_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   description,       1) \
X(a, STATIC,   OPTIONAL, STRING,   text,              2)
#define aap_protobuf_service_radio_message_HdRadioComment_CALLBACK NULL
#define aap_protobuf_service_radio_message_HdRadioComment_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_radio_message_HdRadioComment_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_HdRadioComment_fields &aap_protobuf_service_radio_message_HdRadioComment_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOCOMMENT_PB_H_MAX_SIZE aap_protobuf_service_radio_message_HdRadioComment_size
#define aap_protobuf_service_radio_message_HdRadioComment_size 130

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
