/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOSTATIONINFO_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOSTATIONINFO_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/radio/message/HdRadioSisData.pb.h"
#include "aap_protobuf/service/radio/message/HdRadioPsdData.pb.h"
#include "aap_protobuf/service/radio/message/HdAcquisionState.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_HdRadioStationInfo {
    bool has_acquisition_state;
    aap_protobuf_service_radio_message_HdAcquisionState acquisition_state;
    bool has_digital_signal_strength;
    int32_t digital_signal_strength;
    bool has_psd;
    aap_protobuf_service_radio_message_HdRadioPsdData psd;
    bool has_sis;
    aap_protobuf_service_radio_message_HdRadioSisData sis;
} aap_protobuf_service_radio_message_HdRadioStationInfo;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_HdRadioStationInfo_init_default {false, _aap_protobuf_service_radio_message_HdAcquisionState_MIN, false, 0, false, aap_protobuf_service_radio_message_HdRadioPsdData_init_default, false, aap_protobuf_service_radio_message_HdRadioSisData_init_default}
#define aap_protobuf_service_radio_message_HdRadioStationInfo_init_zero {false, _aap_protobuf_service_radio_message_HdAcquisionState_MIN, false, 0, false, aap_protobuf_service_radio_message_HdRadioPsdData_init_zero, false, aap_protobuf_service_radio_message_HdRadioSisData_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_HdRadioStationInfo_acquisition_state_tag 1
#define aap_protobuf_service_radio_message_HdRadioStationInfo_digital_signal_strength_tag 2
#define aap_protobuf_service_radio_message_HdRadioStationInfo_psd_tag 3
#define aap_protobuf_service_radio_message_HdRadioStationInfo_sis_tag 4

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_HdRadioStationInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    acquisition_state,   1) \
X(a, STATIC,   OPTIONAL, INT32,    digital_signal_strength,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  psd,               3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sis,               4)
#define aap_protobuf_service_radio_message_HdRadioStationInfo_CALLBACK NULL
#define aap_protobuf_service_radio_message_HdRadioStationInfo_DEFAULT NULL
#define aap_protobuf_service_radio_message_HdRadioStationInfo_psd_MSGTYPE aap_protobuf_service_radio_message_HdRadioPsdData
#define aap_protobuf_service_radio_message_HdRadioStationInfo_sis_MSGTYPE aap_protobuf_service_radio_message_HdRadioSisData

extern const pb_msgdesc_t aap_protobuf_service_radio_message_HdRadioStationInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_HdRadioStationInfo_fields &aap_protobuf_service_radio_message_HdRadioStationInfo_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOSTATIONINFO_PB_H_MAX_SIZE aap_protobuf_service_radio_message_HdRadioStationInfo_size
#define aap_protobuf_service_radio_message_HdRadioStationInfo_size 1186

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
