/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOARTISTEXPERIENCE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOARTISTEXPERIENCE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_radio_message_HdRadioArtistExperience_image_t;
typedef struct _aap_protobuf_service_radio_message_HdRadioArtistExperience {
    bool has_image;
    aap_protobuf_service_radio_message_HdRadioArtistExperience_image_t image;
} aap_protobuf_service_radio_message_HdRadioArtistExperience;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_HdRadioArtistExperience_init_default {false, {0, {0}}}
#define aap_protobuf_service_radio_message_HdRadioArtistExperience_init_zero {false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_HdRadioArtistExperience_image_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_HdRadioArtistExperience_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BYTES,    image,             1)
#define aap_protobuf_service_radio_message_HdRadioArtistExperience_CALLBACK NULL
#define aap_protobuf_service_radio_message_HdRadioArtistExperience_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_radio_message_HdRadioArtistExperience_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_HdRadioArtistExperience_fields &aap_protobuf_service_radio_message_HdRadioArtistExperience_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOARTISTEXPERIENCE_PB_H_MAX_SIZE aap_protobuf_service_radio_message_HdRadioArtistExperience_size
#define aap_protobuf_service_radio_message_HdRadioArtistExperience_size 66

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
