/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOPSDDATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOPSDDATA_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/radio/message/HdRadioComment.pb.h"
#include "aap_protobuf/service/radio/message/HdRadioCommercial.pb.h"
#include "aap_protobuf/service/radio/message/HdRadioArtistExperience.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_HdRadioPsdData {
    bool has_title;
    char title[64];
    bool has_artist;
    char artist[64];
    bool has_album;
    char album[64];
    bool has_genre;
    char genre[64];
    bool has_comment;
    aap_protobuf_service_radio_message_HdRadioComment comment;
    bool has_commercial;
    aap_protobuf_service_radio_message_HdRadioCommercial commercial;
    bool has_artist_experience;
    aap_protobuf_service_radio_message_HdRadioArtistExperience artist_experience;
} aap_protobuf_service_radio_message_HdRadioPsdData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_HdRadioPsdData_init_default {false, "", false, "", false, "", false, "", false, aap_protobuf_service_radio_message_HdRadioComment_init_default, false, aap_protobuf_service_radio_message_HdRadioCommercial_init_default, false, aap_protobuf_service_radio_message_HdRadioArtistExperience_init_default}
#define aap_protobuf_service_radio_message_HdRadioPsdData_init_zero {false, "", false, "", false, "", false, "", false, aap_protobuf_service_radio_message_HdRadioComment_init_zero, false, aap_protobuf_service_radio_message_HdRadioCommercial_init_zero, false, aap_protobuf_service_radio_message_HdRadioArtistExperience_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_HdRadioPsdData_title_tag 1
#define aap_protobuf_service_radio_message_HdRadioPsdData_artist_tag 2
#define aap_protobuf_service_radio_message_HdRadioPsdData_album_tag 3
#define aap_protobuf_service_radio_message_HdRadioPsdData_genre_tag 4
#define aap_protobuf_service_radio_message_HdRadioPsdData_comment_tag 5
#define aap_protobuf_service_radio_message_HdRadioPsdData_commercial_tag 6
#define aap_protobuf_service_radio_message_HdRadioPsdData_artist_experience_tag 7

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_HdRadioPsdData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   title,             1) \
X(a, STATIC,   OPTIONAL, STRING,   artist,            2) \
X(a, STATIC,   OPTIONAL, STRING,   album,             3) \
X(a, STATIC,   OPTIONAL, STRING,   genre,             4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  comment,           5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  commercial,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  artist_experience,   7)
#define aap_protobuf_service_radio_message_HdRadioPsdData_CALLBACK NULL
#define aap_protobuf_service_radio_message_HdRadioPsdData_DEFAULT NULL
#define aap_protobuf_service_radio_message_HdRadioPsdData_comment_MSGTYPE aap_protobuf_service_radio_message_HdRadioComment
#define aap_protobuf_service_radio_message_HdRadioPsdData_commercial_MSGTYPE aap_protobuf_service_radio_message_HdRadioCommercial
#define aap_protobuf_service_radio_message_HdRadioPsdData_artist_experience_MSGTYPE aap_protobuf_service_radio_message_HdRadioArtistExperience

extern const pb_msgdesc_t aap_protobuf_service_radio_message_HdRadioPsdData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_HdRadioPsdData_fields &aap_protobuf_service_radio_message_HdRadioPsdData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOPSDDATA_PB_H_MAX_SIZE aap_protobuf_service_radio_message_HdRadioPsdData_size
#define aap_protobuf_service_radio_message_HdRadioPsdData_size 811

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
