/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOCOMMERCIAL_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOCOMMERCIAL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_HdRadioCommercial {
    bool has_encoding;
    int32_t encoding;
    bool has_price;
    char price[64];
    bool has_valid;
    char valid[64];
    bool has_url;
    char url[64];
    bool has_received;
    int32_t received;
    bool has_seller;
    char seller[64];
    bool has_description;
    char description[64];
} aap_protobuf_service_radio_message_HdRadioCommercial;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_HdRadioCommercial_init_default {false, 0, false, "", false, "", false, "", false, 0, false, "", false, ""}
#define aap_protobuf_service_radio_message_HdRadioCommercial_init_zero {false, 0, false, "", false, "", false, "", false, 0, false, "", false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_HdRadioCommercial_encoding_tag 1
#define aap_protobuf_service_radio_message_HdRadioCommercial_price_tag 2
#define aap_protobuf_service_radio_message_HdRadioCommercial_valid_tag 3
#define aap_protobuf_service_radio_message_HdRadioCommercial_url_tag 4
#define aap_protobuf_service_radio_message_HdRadioCommercial_received_tag 5
#define aap_protobuf_service_radio_message_HdRadioCommercial_seller_tag 6
#define aap_protobuf_service_radio_message_HdRadioCommercial_description_tag 7

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_HdRadioCommercial_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    encoding,          1) \
X(a, STATIC,   OPTIONAL, STRING,   price,             2) \
X(a, STATIC,   OPTIONAL, STRING,   valid,             3) \
X(a, STATIC,   OPTIONAL, STRING,   url,               4) \
X(a, STATIC,   OPTIONAL, INT32,    received,          5) \
X(a, STATIC,   OPTIONAL, STRING,   seller,            6) \
X(a, STATIC,   OPTIONAL, STRING,   description,       7)
#define aap_protobuf_service_radio_message_HdRadioCommercial_CALLBACK NULL
#define aap_protobuf_service_radio_message_HdRadioCommercial_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_radio_message_HdRadioCommercial_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_HdRadioCommercial_fields &aap_protobuf_service_radio_message_HdRadioCommercial_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_HDRADIOCOMMERCIAL_PB_H_MAX_SIZE aap_protobuf_service_radio_message_HdRadioCommercial_size
#define aap_protobuf_service_radio_message_HdRadioCommercial_size 347

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
