/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_LOCATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_LOCATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_Location {
    double longitude;
    double latitude;
} aap_protobuf_service_radio_message_Location;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_Location_init_default {0, 0}
#define aap_protobuf_service_radio_message_Location_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_Location_longitude_tag 1
#define aap_protobuf_service_radio_message_Location_latitude_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_Location_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, DOUBLE,   longitude,         1) \
X(a, STATIC,   REQUIRED, DOUBLE,   latitude,          2)
#define aap_protobuf_service_radio_message_Location_CALLBACK NULL
#define aap_protobuf_service_radio_message_Location_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_radio_message_Location_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_Location_fields &aap_protobuf_service_radio_message_Location_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_LOCATION_PB_H_MAX_SIZE aap_protobuf_service_radio_message_Location_size
#define aap_protobuf_service_radio_message_Location_size 18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
