/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_MUTERADIOREQUEST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_MUTERADIOREQUEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_MuteRadioRequest {
    bool has_radio_id;
    int32_t radio_id;
    bool mute;
} aap_protobuf_service_radio_message_MuteRadioRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_MuteRadioRequest_init_default {false, 0, 0}
#define aap_protobuf_service_radio_message_MuteRadioRequest_init_zero {false, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_MuteRadioRequest_radio_id_tag 1
#define aap_protobuf_service_radio_message_MuteRadioRequest_mute_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_MuteRadioRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    radio_id,          1) \
X(a, STATIC,   REQUIRED, BOOL,     mute,              2)
#define aap_protobuf_service_radio_message_MuteRadioRequest_CALLBACK NULL
#define aap_protobuf_service_radio_message_MuteRadioRequest_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_radio_message_MuteRadioRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_MuteRadioRequest_fields &aap_protobuf_service_radio_message_MuteRadioRequest_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_MUTERADIOREQUEST_PB_H_MAX_SIZE aap_protobuf_service_radio_message_MuteRadioRequest_size
#define aap_protobuf_service_radio_message_MuteRadioRequest_size 13

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
