/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOSTATIONMETADATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOSTATIONMETADATA_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/radio/message/RdsData.pb.h"
#include "aap_protobuf/service/radio/message/HdRadioStationInfo.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_RadioStationMetaData {
    bool has_audio_channels;
    int32_t audio_channels;
    bool has_signal_quality;
    int32_t signal_quality;
    bool has_rds;
    aap_protobuf_service_radio_message_RdsData rds;
    bool has_hd_station_info;
    aap_protobuf_service_radio_message_HdRadioStationInfo hd_station_info;
} aap_protobuf_service_radio_message_RadioStationMetaData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_RadioStationMetaData_init_default {false, 0, false, 0, false, aap_protobuf_service_radio_message_RdsData_init_default, false, aap_protobuf_service_radio_message_HdRadioStationInfo_init_default}
#define aap_protobuf_service_radio_message_RadioStationMetaData_init_zero {false, 0, false, 0, false, aap_protobuf_service_radio_message_RdsData_init_zero, false, aap_protobuf_service_radio_message_HdRadioStationInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_RadioStationMetaData_audio_channels_tag 1
#define aap_protobuf_service_radio_message_RadioStationMetaData_signal_quality_tag 2
#define aap_protobuf_service_radio_message_RadioStationMetaData_rds_tag 3
#define aap_protobuf_service_radio_message_RadioStationMetaData_hd_station_info_tag 4

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_RadioStationMetaData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    audio_channels,    1) \
X(a, STATIC,   OPTIONAL, INT32,    signal_quality,    2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rds,               3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  hd_station_info,   4)
#define aap_protobuf_service_radio_message_RadioStationMetaData_CALLBACK NULL
#define aap_protobuf_service_radio_message_RadioStationMetaData_DEFAULT NULL
#define aap_protobuf_service_radio_message_RadioStationMetaData_rds_MSGTYPE aap_protobuf_service_radio_message_RdsData
#define aap_protobuf_service_radio_message_RadioStationMetaData_hd_station_info_MSGTYPE aap_protobuf_service_radio_message_HdRadioStationInfo

extern const pb_msgdesc_t aap_protobuf_service_radio_message_RadioStationMetaData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_RadioStationMetaData_fields &aap_protobuf_service_radio_message_RadioStationMetaData_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOSTATIONMETADATA_PB_H_MAX_SIZE aap_protobuf_service_radio_message_RadioStationMetaData_size
#define aap_protobuf_service_radio_message_RadioStationMetaData_size 1534

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
