/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOPROPERTIES_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOPROPERTIES_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/radio/message/RadioType.pb.h"
#include "aap_protobuf/service/radio/message/Range.pb.h"
#include "aap_protobuf/service/radio/message/RdsType.pb.h"
#include "aap_protobuf/service/radio/message/TrafficServiceType.pb.h"
#include "aap_protobuf/service/radio/message/ItuRegion.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_RadioProperties {
    int32_t radio_id;
    aap_protobuf_service_radio_message_RadioType type;
    pb_size_t channel_range_count;
    aap_protobuf_service_radio_message_Range channel_range[8];
    pb_size_t channel_spacings_count;
    int32_t channel_spacings[8];
    int32_t channel_spacing;
    bool has_background_tuner;
    bool background_tuner;
    bool has_region;
    aap_protobuf_service_radio_ItuRegion region;
    bool has_rds;
    aap_protobuf_service_radio_message_RdsType rds;
    bool has_af_switch;
    bool af_switch;
    bool has_ta;
    bool ta;
    bool has_traffic_service;
    aap_protobuf_service_radio_message_TrafficServiceType traffic_service;
    bool has_audio_loopback;
    bool audio_loopback;
    bool has_mute_capability;
    bool mute_capability;
    bool has_station_presets_access;
    int32_t station_presets_access;
} aap_protobuf_service_radio_message_RadioProperties;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_RadioProperties_init_default {0, _aap_protobuf_service_radio_message_RadioType_MIN, 0, {aap_protobuf_service_radio_message_Range_init_default, aap_protobuf_service_radio_message_Range_init_default, aap_protobuf_service_radio_message_Range_init_default, aap_protobuf_service_radio_message_Range_init_default, aap_protobuf_service_radio_message_Range_init_default, aap_protobuf_service_radio_message_Range_init_default, aap_protobuf_service_radio_message_Range_init_default, aap_protobuf_service_radio_message_Range_init_default}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, false, 0, false, _aap_protobuf_service_radio_ItuRegion_MIN, false, _aap_protobuf_service_radio_message_RdsType_MIN, false, 0, false, 0, false, _aap_protobuf_service_radio_message_TrafficServiceType_MIN, false, 0, false, 0, false, 0}
#define aap_protobuf_service_radio_message_RadioProperties_init_zero {0, _aap_protobuf_service_radio_message_RadioType_MIN, 0, {aap_protobuf_service_radio_message_Range_init_zero, aap_protobuf_service_radio_message_Range_init_zero, aap_protobuf_service_radio_message_Range_init_zero, aap_protobuf_service_radio_message_Range_init_zero, aap_protobuf_service_radio_message_Range_init_zero, aap_protobuf_service_radio_message_Range_init_zero, aap_protobuf_service_radio_message_Range_init_zero, aap_protobuf_service_radio_message_Range_init_zero}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, false, 0, false, _aap_protobuf_service_radio_ItuRegion_MIN, false, _aap_protobuf_service_radio_message_RdsType_MIN, false, 0, false, 0, false, _aap_protobuf_service_radio_message_TrafficServiceType_MIN, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_RadioProperties_radio_id_tag 1
#define aap_protobuf_service_radio_message_RadioProperties_type_tag 2
#define aap_protobuf_service_radio_message_RadioProperties_channel_range_tag 3
#define aap_protobuf_service_radio_message_RadioProperties_channel_spacings_tag 4
#define aap_protobuf_service_radio_message_RadioProperties_channel_spacing_tag 5
#define aap_protobuf_service_radio_message_RadioProperties_background_tuner_tag 6
#define aap_protobuf_service_radio_message_RadioProperties_region_tag 7
#define aap_protobuf_service_radio_message_RadioProperties_rds_tag 8
#define aap_protobuf_service_radio_message_RadioProperties_af_switch_tag 9
#define aap_protobuf_service_radio_message_RadioProperties_ta_tag 10
#define aap_protobuf_service_radio_message_RadioProperties_traffic_service_tag 11
#define aap_protobuf_service_radio_message_RadioProperties_audio_loopback_tag 12
#define aap_protobuf_service_radio_message_RadioProperties_mute_capability_tag 13
#define aap_protobuf_service_radio_message_RadioProperties_station_presets_access_tag 14

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_RadioProperties_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    radio_id,          1) \
X(a, STATIC,   REQUIRED, UENUM,    type,              2) \
X(a, STATIC,   REPEATED, MESSAGE,  channel_range,     3) \
X(a, STATIC,   REPEATED, INT32,    channel_spacings,   4) \
X(a, STATIC,   REQUIRED, INT32,    channel_spacing,   5) \
X(a, STATIC,   OPTIONAL, BOOL,     background_tuner,   6) \
X(a, STATIC,   OPTIONAL, UENUM,    region,            7) \
X(a, STATIC,   OPTIONAL, UENUM,    rds,               8) \
X(a, STATIC,   OPTIONAL, BOOL,     af_switch,         9) \
X(a, STATIC,   OPTIONAL, BOOL,     ta,               10) \
X(a, STATIC,   OPTIONAL, UENUM,    traffic_service,  11) \
X(a, STATIC,   OPTIONAL, BOOL,     audio_loopback,   12) \
X(a, STATIC,   OPTIONAL, BOOL,     mute_capability,  13) \
X(a, STATIC,   OPTIONAL, INT32,    station_presets_access,  14)
#define aap_protobuf_service_radio_message_RadioProperties_CALLBACK NULL
#define aap_protobuf_service_radio_message_RadioProperties_DEFAULT NULL
#define aap_protobuf_service_radio_message_RadioProperties_channel_range_MSGTYPE aap_protobuf_service_radio_message_Range

extern const pb_msgdesc_t aap_protobuf_service_radio_message_RadioProperties_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_RadioProperties_fields &aap_protobuf_service_radio_message_RadioProperties_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOPROPERTIES_PB_H_MAX_SIZE aap_protobuf_service_radio_message_RadioProperties_size
#define aap_protobuf_service_radio_message_RadioProperties_size 331

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
