/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOSTATIONINFONOTIFICATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOSTATIONINFONOTIFICATION_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/radio/message/RadioStationInfo.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_RadioStationInfoNotification {
    int32_t radio_id;
    aap_protobuf_service_radio_message_RadioStationInfo station_info;
} aap_protobuf_service_radio_message_RadioStationInfoNotification;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_RadioStationInfoNotification_init_default {0, aap_protobuf_service_radio_message_RadioStationInfo_init_default}
#define aap_protobuf_service_radio_message_RadioStationInfoNotification_init_zero {0, aap_protobuf_service_radio_message_RadioStationInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_RadioStationInfoNotification_radio_id_tag 1
#define aap_protobuf_service_radio_message_RadioStationInfoNotification_station_info_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_RadioStationInfoNotification_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    radio_id,          1) \
X(a, STATIC,   REQUIRED, MESSAGE,  station_info,      2)
#define aap_protobuf_service_radio_message_RadioStationInfoNotification_CALLBACK NULL
#define aap_protobuf_service_radio_message_RadioStationInfoNotification_DEFAULT NULL
#define aap_protobuf_service_radio_message_RadioStationInfoNotification_station_info_MSGTYPE aap_protobuf_service_radio_message_RadioStationInfo

extern const pb_msgdesc_t aap_protobuf_service_radio_message_RadioStationInfoNotification_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_RadioStationInfoNotification_fields &aap_protobuf_service_radio_message_RadioStationInfoNotification_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOSTATIONINFONOTIFICATION_PB_H_MAX_SIZE aap_protobuf_service_radio_message_RadioStationInfoNotification_size
#define aap_protobuf_service_radio_message_RadioStationInfoNotification_size 1575

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
