/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOSOURCERESPONSE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOSOURCERESPONSE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/shared/MessageStatus.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_RadioSourceResponse {
    bool has_status;
    aap_protobuf_shared_MessageStatus status;
    bool radio_source_enabled;
} aap_protobuf_service_radio_message_RadioSourceResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_RadioSourceResponse_init_default {false, _aap_protobuf_shared_MessageStatus_MIN, 0}
#define aap_protobuf_service_radio_message_RadioSourceResponse_init_zero {false, _aap_protobuf_shared_MessageStatus_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_RadioSourceResponse_status_tag 1
#define aap_protobuf_service_radio_message_RadioSourceResponse_radio_source_enabled_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_RadioSourceResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, ENUM,     status,            1) \
X(a, STATIC,   REQUIRED, BOOL,     radio_source_enabled,   2)
#define aap_protobuf_service_radio_message_RadioSourceResponse_CALLBACK NULL
#define aap_protobuf_service_radio_message_RadioSourceResponse_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_radio_message_RadioSourceResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_RadioSourceResponse_fields &aap_protobuf_service_radio_message_RadioSourceResponse_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOSOURCERESPONSE_PB_H_MAX_SIZE aap_protobuf_service_radio_message_RadioSourceResponse_size
#define aap_protobuf_service_radio_message_RadioSourceResponse_size 13

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
