/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOSTATIONINFO_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOSTATIONINFO_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/radio/message/RadioType.pb.h"
#include "aap_protobuf/service/radio/message/RadioStationMetaData.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_RadioStationInfo {
    aap_protobuf_service_radio_message_RadioType type;
    int32_t channel;
    bool has_sub_channel;
    int32_t sub_channel;
    bool has_meta_data;
    aap_protobuf_service_radio_message_RadioStationMetaData meta_data;
} aap_protobuf_service_radio_message_RadioStationInfo;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_RadioStationInfo_init_default {_aap_protobuf_service_radio_message_RadioType_MIN, 0, false, 0, false, aap_protobuf_service_radio_message_RadioStationMetaData_init_default}
#define aap_protobuf_service_radio_message_RadioStationInfo_init_zero {_aap_protobuf_service_radio_message_RadioType_MIN, 0, false, 0, false, aap_protobuf_service_radio_message_RadioStationMetaData_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_RadioStationInfo_type_tag 1
#define aap_protobuf_service_radio_message_RadioStationInfo_channel_tag 2
#define aap_protobuf_service_radio_message_RadioStationInfo_sub_channel_tag 3
#define aap_protobuf_service_radio_message_RadioStationInfo_meta_data_tag 4

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_RadioStationInfo_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, STATIC,   REQUIRED, INT32,    channel,           2) \
X(a, STATIC,   OPTIONAL, INT32,    sub_channel,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  meta_data,         4)
#define aap_protobuf_service_radio_message_RadioStationInfo_CALLBACK NULL
#define aap_protobuf_service_radio_message_RadioStationInfo_DEFAULT NULL
#define aap_protobuf_service_radio_message_RadioStationInfo_meta_data_MSGTYPE aap_protobuf_service_radio_message_RadioStationMetaData

extern const pb_msgdesc_t aap_protobuf_service_radio_message_RadioStationInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_RadioStationInfo_fields &aap_protobuf_service_radio_message_RadioStationInfo_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RADIOSTATIONINFO_PB_H_MAX_SIZE aap_protobuf_service_radio_message_RadioStationInfo_size
#define aap_protobuf_service_radio_message_RadioStationInfo_size 1561

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
