/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RANGE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RANGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_Range {
    int32_t min;
    int32_t max;
} aap_protobuf_service_radio_message_Range;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_Range_init_default {0, 0}
#define aap_protobuf_service_radio_message_Range_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_Range_min_tag 1
#define aap_protobuf_service_radio_message_Range_max_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_Range_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    min,               1) \
X(a, STATIC,   REQUIRED, INT32,    max,               2)
#define aap_protobuf_service_radio_message_Range_CALLBACK NULL
#define aap_protobuf_service_radio_message_Range_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_radio_message_Range_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_Range_fields &aap_protobuf_service_radio_message_Range_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RANGE_PB_H_MAX_SIZE aap_protobuf_service_radio_message_Range_size
#define aap_protobuf_service_radio_message_Range_size 22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
