/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RDSTYPE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_RDSTYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_radio_message_RdsType {
    aap_protobuf_service_radio_message_RdsType_NO_RDS = 0,
    aap_protobuf_service_radio_message_RdsType_RDS = 1,
    aap_protobuf_service_radio_message_RdsType_RBDS = 2
} aap_protobuf_service_radio_message_RdsType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_radio_message_RdsType_MIN aap_protobuf_service_radio_message_RdsType_NO_RDS
#define _aap_protobuf_service_radio_message_RdsType_MAX aap_protobuf_service_radio_message_RdsType_RBDS
#define _aap_protobuf_service_radio_message_RdsType_ARRAYSIZE ((aap_protobuf_service_radio_message_RdsType)(aap_protobuf_service_radio_message_RdsType_RBDS+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
