/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_SCANSTATIONSREQUEST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_SCANSTATIONSREQUEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_ScanStationsRequest {
    int32_t radio_id;
    bool start;
    bool up;
    bool skip_sub_channel;
} aap_protobuf_service_radio_message_ScanStationsRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_ScanStationsRequest_init_default {0, 0, 0, 0}
#define aap_protobuf_service_radio_message_ScanStationsRequest_init_zero {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_ScanStationsRequest_radio_id_tag 1
#define aap_protobuf_service_radio_message_ScanStationsRequest_start_tag 2
#define aap_protobuf_service_radio_message_ScanStationsRequest_up_tag 3
#define aap_protobuf_service_radio_message_ScanStationsRequest_skip_sub_channel_tag 4

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_ScanStationsRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    radio_id,          1) \
X(a, STATIC,   REQUIRED, BOOL,     start,             2) \
X(a, STATIC,   REQUIRED, BOOL,     up,                3) \
X(a, STATIC,   REQUIRED, BOOL,     skip_sub_channel,   4)
#define aap_protobuf_service_radio_message_ScanStationsRequest_CALLBACK NULL
#define aap_protobuf_service_radio_message_ScanStationsRequest_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_radio_message_ScanStationsRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_ScanStationsRequest_fields &aap_protobuf_service_radio_message_ScanStationsRequest_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_SCANSTATIONSREQUEST_PB_H_MAX_SIZE aap_protobuf_service_radio_message_ScanStationsRequest_size
#define aap_protobuf_service_radio_message_ScanStationsRequest_size 17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
