/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_STATIONPRESET_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_STATIONPRESET_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/radio/message/RadioType.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_StationPreset {
    aap_protobuf_service_radio_message_RadioType type;
    int32_t channel;
    bool has_sub_channel;
    int32_t sub_channel;
} aap_protobuf_service_radio_message_StationPreset;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_StationPreset_init_default {_aap_protobuf_service_radio_message_RadioType_MIN, 0, false, 0}
#define aap_protobuf_service_radio_message_StationPreset_init_zero {_aap_protobuf_service_radio_message_RadioType_MIN, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_StationPreset_type_tag 1
#define aap_protobuf_service_radio_message_StationPreset_channel_tag 2
#define aap_protobuf_service_radio_message_StationPreset_sub_channel_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_StationPreset_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, STATIC,   REQUIRED, INT32,    channel,           2) \
X(a, STATIC,   OPTIONAL, INT32,    sub_channel,       3)
#define aap_protobuf_service_radio_message_StationPreset_CALLBACK NULL
#define aap_protobuf_service_radio_message_StationPreset_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_radio_message_StationPreset_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_StationPreset_fields &aap_protobuf_service_radio_message_StationPreset_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_STATIONPRESET_PB_H_MAX_SIZE aap_protobuf_service_radio_message_StationPreset_size
#define aap_protobuf_service_radio_message_StationPreset_size 24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
