/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_STATIONPRESETLIST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_STATIONPRESETLIST_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/radio/message/StationPreset.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_StationPresetList {
    bool has_name;
    char name[64];
    pb_size_t restricted_station_types_count;
    int32_t restricted_station_types[8];
    pb_size_t presets_count;
    aap_protobuf_service_radio_message_StationPreset presets[8];
} aap_protobuf_service_radio_message_StationPresetList;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_StationPresetList_init_default {false, "", 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {aap_protobuf_service_radio_message_StationPreset_init_default, aap_protobuf_service_radio_message_StationPreset_init_default, aap_protobuf_service_radio_message_StationPreset_init_default, aap_protobuf_service_radio_message_StationPreset_init_default, aap_protobuf_service_radio_message_StationPreset_init_default, aap_protobuf_service_radio_message_StationPreset_init_default, aap_protobuf_service_radio_message_StationPreset_init_default, aap_protobuf_service_radio_message_StationPreset_init_default}}
#define aap_protobuf_service_radio_message_StationPresetList_init_zero {false, "", 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {aap_protobuf_service_radio_message_StationPreset_init_zero, aap_protobuf_service_radio_message_StationPreset_init_zero, aap_protobuf_service_radio_message_StationPreset_init_zero, aap_protobuf_service_radio_message_StationPreset_init_zero, aap_protobuf_service_radio_message_StationPreset_init_zero, aap_protobuf_service_radio_message_StationPreset_init_zero, aap_protobuf_service_radio_message_StationPreset_init_zero, aap_protobuf_service_radio_message_StationPreset_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_StationPresetList_name_tag 1
#define aap_protobuf_service_radio_message_StationPresetList_restricted_station_types_tag 2
#define aap_protobuf_service_radio_message_StationPresetList_presets_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_StationPresetList_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   name,              1) \
X(a, STATIC,   REPEATED, INT32,    restricted_station_types,   2) \
X(a, STATIC,   REPEATED, MESSAGE,  presets,           3)
#define aap_protobuf_service_radio_message_StationPresetList_CALLBACK NULL
#define aap_protobuf_service_radio_message_StationPresetList_DEFAULT NULL
#define aap_protobuf_service_radio_message_StationPresetList_presets_MSGTYPE aap_protobuf_service_radio_message_StationPreset

extern const pb_msgdesc_t aap_protobuf_service_radio_message_StationPresetList_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_StationPresetList_fields &aap_protobuf_service_radio_message_StationPresetList_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_STATIONPRESETLIST_PB_H_MAX_SIZE aap_protobuf_service_radio_message_StationPresetList_size
#define aap_protobuf_service_radio_message_StationPresetList_size 361

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
