/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_TRAFFICINCIDENT_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_TRAFFICINCIDENT_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/radio/message/Location.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_radio_message_TrafficIncident {
    int32_t event_code;
    aap_protobuf_service_radio_message_Location location;
    int32_t expected_incident_duration;
} aap_protobuf_service_radio_message_TrafficIncident;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_radio_message_TrafficIncident_init_default {0, aap_protobuf_service_radio_message_Location_init_default, 0}
#define aap_protobuf_service_radio_message_TrafficIncident_init_zero {0, aap_protobuf_service_radio_message_Location_init_zero, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_radio_message_TrafficIncident_event_code_tag 1
#define aap_protobuf_service_radio_message_TrafficIncident_location_tag 2
#define aap_protobuf_service_radio_message_TrafficIncident_expected_incident_duration_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_radio_message_TrafficIncident_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    event_code,        1) \
X(a, STATIC,   REQUIRED, MESSAGE,  location,          2) \
X(a, STATIC,   REQUIRED, INT32,    expected_incident_duration,   3)
#define aap_protobuf_service_radio_message_TrafficIncident_CALLBACK NULL
#define aap_protobuf_service_radio_message_TrafficIncident_DEFAULT NULL
#define aap_protobuf_service_radio_message_TrafficIncident_location_MSGTYPE aap_protobuf_service_radio_message_Location

extern const pb_msgdesc_t aap_protobuf_service_radio_message_TrafficIncident_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_radio_message_TrafficIncident_fields &aap_protobuf_service_radio_message_TrafficIncident_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_TRAFFICINCIDENT_PB_H_MAX_SIZE aap_protobuf_service_radio_message_TrafficIncident_size
#define aap_protobuf_service_radio_message_TrafficIncident_size 42

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
