/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_TRAFFICSERVICETYPE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_AAP_PROTOBUF_SERVICE_RADIO_MESSAGE_TRAFFICSERVICETYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_radio_message_TrafficServiceType {
    aap_protobuf_service_radio_message_TrafficServiceType_NO_TRAFFIC_SERVICE = 0,
    aap_protobuf_service_radio_message_TrafficServiceType_TMC_TRAFFIC_SERVICE = 1
} aap_protobuf_service_radio_message_TrafficServiceType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_radio_message_TrafficServiceType_MIN aap_protobuf_service_radio_message_TrafficServiceType_NO_TRAFFIC_SERVICE
#define _aap_protobuf_service_radio_message_TrafficServiceType_MAX aap_protobuf_service_radio_message_TrafficServiceType_TMC_TRAFFIC_SERVICE
#define _aap_protobuf_service_radio_message_TrafficServiceType_ARRAYSIZE ((aap_protobuf_service_radio_message_TrafficServiceType)(aap_protobuf_service_radio_message_TrafficServiceType_TMC_TRAFFIC_SERVICE+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
