[General]
AutoStartCarLink=1
IphoneLinkType=3
Volume=20
VehicleName="TOYOTA"
HomeIconLabel="TOYOTA"
CarPlayIconPath="/msnprofile/icon_120x120.png"
MCUUpdateName="toyotaCarplayFW2.0.bin"
EnablePhoto=0
AndroidLinkType=6
RightHandCarDriver=0
MirroringLinkType=2
DisablePhoneLinkAudio=1
#禁用转场动画
DisableWindowEffect=1
#禁用方控多媒体按键
IgnoreMediaKey=1
Language=4096
