/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AUDIOUNDERFLOWNOTIFICATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AUDIOUNDERFLOWNOTIFICATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_media_sink_message_AudioUnderflowNotification {
    int32_t session_id;
} aap_protobuf_service_media_sink_message_AudioUnderflowNotification;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_media_sink_message_AudioUnderflowNotification_init_default {0}
#define aap_protobuf_service_media_sink_message_AudioUnderflowNotification_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_media_sink_message_AudioUnderflowNotification_session_id_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_media_sink_message_AudioUnderflowNotification_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    session_id,        1)
#define aap_protobuf_service_media_sink_message_AudioUnderflowNotification_CALLBACK NULL
#define aap_protobuf_service_media_sink_message_AudioUnderflowNotification_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_media_sink_message_AudioUnderflowNotification_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_media_sink_message_AudioUnderflowNotification_fields &aap_protobuf_service_media_sink_message_AudioUnderflowNotification_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AUDIOUNDERFLOWNOTIFICATION_PB_H_MAX_SIZE aap_protobuf_service_media_sink_message_AudioUnderflowNotification_size
#define aap_protobuf_service_media_sink_message_AudioUnderflowNotification_size 11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
