/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "aap_protobuf/service/media/sink/message/AudioUnderflowNotification.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aap_protobuf_service_media_sink_message_AudioUnderflowNotification, aap_protobuf_service_media_sink_message_AudioUnderflowNotification, AUTO)



