/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AUDIOSTREAMTYPE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AUDIOSTREAMTYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_media_sink_message_AudioStreamType {
    aap_protobuf_service_media_sink_message_AudioStreamType_AUDIO_STREAM_GUIDANCE = 1,
    aap_protobuf_service_media_sink_message_AudioStreamType_AUDIO_STREAM_SYSTEM_AUDIO = 2,
    aap_protobuf_service_media_sink_message_AudioStreamType_AUDIO_STREAM_MEDIA = 3,
    aap_protobuf_service_media_sink_message_AudioStreamType_AUDIO_STREAM_TELEPHONY = 4
} aap_protobuf_service_media_sink_message_AudioStreamType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_media_sink_message_AudioStreamType_MIN aap_protobuf_service_media_sink_message_AudioStreamType_AUDIO_STREAM_GUIDANCE
#define _aap_protobuf_service_media_sink_message_AudioStreamType_MAX aap_protobuf_service_media_sink_message_AudioStreamType_AUDIO_STREAM_TELEPHONY
#define _aap_protobuf_service_media_sink_message_AudioStreamType_ARRAYSIZE ((aap_protobuf_service_media_sink_message_AudioStreamType)(aap_protobuf_service_media_sink_message_AudioStreamType_AUDIO_STREAM_TELEPHONY+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
