/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_DISPLAYTYPE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_DISPLAYTYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_media_sink_message_DisplayType {
    aap_protobuf_service_media_sink_message_DisplayType_DISPLAY_TYPE_MAIN = 0,
    aap_protobuf_service_media_sink_message_DisplayType_DISPLAY_TYPE_CLUSTER = 1,
    aap_protobuf_service_media_sink_message_DisplayType_DISPLAY_TYPE_AUXILIARY = 2
} aap_protobuf_service_media_sink_message_DisplayType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_media_sink_message_DisplayType_MIN aap_protobuf_service_media_sink_message_DisplayType_DISPLAY_TYPE_MAIN
#define _aap_protobuf_service_media_sink_message_DisplayType_MAX aap_protobuf_service_media_sink_message_DisplayType_DISPLAY_TYPE_AUXILIARY
#define _aap_protobuf_service_media_sink_message_DisplayType_ARRAYSIZE ((aap_protobuf_service_media_sink_message_DisplayType)(aap_protobuf_service_media_sink_message_DisplayType_DISPLAY_TYPE_AUXILIARY+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
