/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_KEYBINDINGREQUEST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_KEYBINDINGREQUEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_media_sink_message_KeyBindingRequest {
    pb_size_t keycodes_count;
    int32_t keycodes[8];
} aap_protobuf_service_media_sink_message_KeyBindingRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_media_sink_message_KeyBindingRequest_init_default {0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define aap_protobuf_service_media_sink_message_KeyBindingRequest_init_zero {0, {0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_media_sink_message_KeyBindingRequest_keycodes_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_media_sink_message_KeyBindingRequest_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, INT32,    keycodes,          1)
#define aap_protobuf_service_media_sink_message_KeyBindingRequest_CALLBACK NULL
#define aap_protobuf_service_media_sink_message_KeyBindingRequest_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_media_sink_message_KeyBindingRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_media_sink_message_KeyBindingRequest_fields &aap_protobuf_service_media_sink_message_KeyBindingRequest_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MESSAGE_KEYBINDINGREQUEST_PB_H_MAX_SIZE aap_protobuf_service_media_sink_message_KeyBindingRequest_size
#define aap_protobuf_service_media_sink_message_KeyBindingRequest_size 88

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
