/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_SINK_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MEDIASINKSERVICE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_SINK_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MEDIASINKSERVICE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/media/shared/message/MediaCodecType.pb.h"
#include "aap_protobuf/service/media/sink/message/AudioStreamType.pb.h"
#include "aap_protobuf/service/media/shared/message/AudioConfiguration.pb.h"
#include "aap_protobuf/service/media/sink/message/VideoConfiguration.pb.h"
#include "aap_protobuf/service/media/sink/message/DisplayType.pb.h"
#include "aap_protobuf/service/media/sink/message/KeyCode.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_media_sink_MediaSinkService {
    bool has_available_type;
    aap_protobuf_service_media_shared_message_MediaCodecType available_type;
    bool has_audio_type;
    aap_protobuf_service_media_sink_message_AudioStreamType audio_type;
    pb_size_t audio_configs_count;
    aap_protobuf_service_media_shared_message_AudioConfiguration audio_configs[8];
    pb_size_t video_configs_count;
    aap_protobuf_service_media_sink_message_VideoConfiguration video_configs[8];
    bool has_available_while_in_call;
    bool available_while_in_call;
    bool has_display_id;
    uint32_t display_id;
    bool has_display_type;
    aap_protobuf_service_media_sink_message_DisplayType display_type;
    bool has_initial_content_keycode;
    aap_protobuf_service_media_sink_message_KeyCode initial_content_keycode;
} aap_protobuf_service_media_sink_MediaSinkService;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_media_sink_MediaSinkService_init_default {false, aap_protobuf_service_media_shared_message_MediaCodecType_MEDIA_CODEC_AUDIO_PCM, false, _aap_protobuf_service_media_sink_message_AudioStreamType_MIN, 0, {aap_protobuf_service_media_shared_message_AudioConfiguration_init_default, aap_protobuf_service_media_shared_message_AudioConfiguration_init_default, aap_protobuf_service_media_shared_message_AudioConfiguration_init_default, aap_protobuf_service_media_shared_message_AudioConfiguration_init_default, aap_protobuf_service_media_shared_message_AudioConfiguration_init_default, aap_protobuf_service_media_shared_message_AudioConfiguration_init_default, aap_protobuf_service_media_shared_message_AudioConfiguration_init_default, aap_protobuf_service_media_shared_message_AudioConfiguration_init_default}, 0, {aap_protobuf_service_media_sink_message_VideoConfiguration_init_default, aap_protobuf_service_media_sink_message_VideoConfiguration_init_default, aap_protobuf_service_media_sink_message_VideoConfiguration_init_default, aap_protobuf_service_media_sink_message_VideoConfiguration_init_default, aap_protobuf_service_media_sink_message_VideoConfiguration_init_default, aap_protobuf_service_media_sink_message_VideoConfiguration_init_default, aap_protobuf_service_media_sink_message_VideoConfiguration_init_default, aap_protobuf_service_media_sink_message_VideoConfiguration_init_default}, false, 0, false, 0, false, _aap_protobuf_service_media_sink_message_DisplayType_MIN, false, _aap_protobuf_service_media_sink_message_KeyCode_MIN}
#define aap_protobuf_service_media_sink_MediaSinkService_init_zero {false, _aap_protobuf_service_media_shared_message_MediaCodecType_MIN, false, _aap_protobuf_service_media_sink_message_AudioStreamType_MIN, 0, {aap_protobuf_service_media_shared_message_AudioConfiguration_init_zero, aap_protobuf_service_media_shared_message_AudioConfiguration_init_zero, aap_protobuf_service_media_shared_message_AudioConfiguration_init_zero, aap_protobuf_service_media_shared_message_AudioConfiguration_init_zero, aap_protobuf_service_media_shared_message_AudioConfiguration_init_zero, aap_protobuf_service_media_shared_message_AudioConfiguration_init_zero, aap_protobuf_service_media_shared_message_AudioConfiguration_init_zero, aap_protobuf_service_media_shared_message_AudioConfiguration_init_zero}, 0, {aap_protobuf_service_media_sink_message_VideoConfiguration_init_zero, aap_protobuf_service_media_sink_message_VideoConfiguration_init_zero, aap_protobuf_service_media_sink_message_VideoConfiguration_init_zero, aap_protobuf_service_media_sink_message_VideoConfiguration_init_zero, aap_protobuf_service_media_sink_message_VideoConfiguration_init_zero, aap_protobuf_service_media_sink_message_VideoConfiguration_init_zero, aap_protobuf_service_media_sink_message_VideoConfiguration_init_zero, aap_protobuf_service_media_sink_message_VideoConfiguration_init_zero}, false, 0, false, 0, false, _aap_protobuf_service_media_sink_message_DisplayType_MIN, false, _aap_protobuf_service_media_sink_message_KeyCode_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_media_sink_MediaSinkService_available_type_tag 1
#define aap_protobuf_service_media_sink_MediaSinkService_audio_type_tag 2
#define aap_protobuf_service_media_sink_MediaSinkService_audio_configs_tag 3
#define aap_protobuf_service_media_sink_MediaSinkService_video_configs_tag 4
#define aap_protobuf_service_media_sink_MediaSinkService_available_while_in_call_tag 5
#define aap_protobuf_service_media_sink_MediaSinkService_display_id_tag 6
#define aap_protobuf_service_media_sink_MediaSinkService_display_type_tag 7
#define aap_protobuf_service_media_sink_MediaSinkService_initial_content_keycode_tag 8

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_media_sink_MediaSinkService_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    available_type,    1) \
X(a, STATIC,   OPTIONAL, UENUM,    audio_type,        2) \
X(a, STATIC,   REPEATED, MESSAGE,  audio_configs,     3) \
X(a, STATIC,   REPEATED, MESSAGE,  video_configs,     4) \
X(a, STATIC,   OPTIONAL, BOOL,     available_while_in_call,   5) \
X(a, STATIC,   OPTIONAL, UINT32,   display_id,        6) \
X(a, STATIC,   OPTIONAL, UENUM,    display_type,      7) \
X(a, STATIC,   OPTIONAL, UENUM,    initial_content_keycode,   8)
#define aap_protobuf_service_media_sink_MediaSinkService_CALLBACK NULL
#define aap_protobuf_service_media_sink_MediaSinkService_DEFAULT (const pb_byte_t*)"\x08\x01\x10\x01\x00"
#define aap_protobuf_service_media_sink_MediaSinkService_audio_configs_MSGTYPE aap_protobuf_service_media_shared_message_AudioConfiguration
#define aap_protobuf_service_media_sink_MediaSinkService_video_configs_MSGTYPE aap_protobuf_service_media_sink_message_VideoConfiguration

extern const pb_msgdesc_t aap_protobuf_service_media_sink_MediaSinkService_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_media_sink_MediaSinkService_fields &aap_protobuf_service_media_sink_MediaSinkService_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIA_SINK_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MEDIASINKSERVICE_PB_H_MAX_SIZE aap_protobuf_service_media_sink_MediaSinkService_size
#define aap_protobuf_service_media_sink_MediaSinkService_size 1242

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
