/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_SINK_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MEDIAMESSAGEID_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_SINK_AAP_PROTOBUF_SERVICE_MEDIA_SINK_MEDIAMESSAGEID_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_media_sink_MediaMessageId {
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_DATA = 0,
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_CODEC_CONFIG = 1,
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_SETUP = 32768,
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_START = 32769,
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_STOP = 32770,
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_CONFIG = 32771,
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_ACK = 32772,
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_MICROPHONE_REQUEST = 32773,
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_MICROPHONE_RESPONSE = 32774,
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_VIDEO_FOCUS_REQUEST = 32775,
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_VIDEO_FOCUS_NOTIFICATION = 32776,
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_UPDATE_UI_CONFIG_REQUEST = 32777,
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_UPDATE_UI_CONFIG_REPLY = 32778,
    aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_AUDIO_UNDERFLOW_NOTIFICATION = 32779
} aap_protobuf_service_media_sink_MediaMessageId;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_media_sink_MediaMessageId_MIN aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_DATA
#define _aap_protobuf_service_media_sink_MediaMessageId_MAX aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_AUDIO_UNDERFLOW_NOTIFICATION
#define _aap_protobuf_service_media_sink_MediaMessageId_ARRAYSIZE ((aap_protobuf_service_media_sink_MediaMessageId)(aap_protobuf_service_media_sink_MediaMessageId_MEDIA_MESSAGE_AUDIO_UNDERFLOW_NOTIFICATION+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
