/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AUDIOFOCUSREQUESTNOTIFICATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AUDIOFOCUSREQUESTNOTIFICATION_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/control/message/AudioFocusRequestType.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_AudioFocusRequestNotification {
    aap_protobuf_service_control_message_AudioFocusRequestType request;
} aap_protobuf_service_control_message_AudioFocusRequestNotification;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_AudioFocusRequestNotification_init_default {_aap_protobuf_service_control_message_AudioFocusRequestType_MIN}
#define aap_protobuf_service_control_message_AudioFocusRequestNotification_init_zero {_aap_protobuf_service_control_message_AudioFocusRequestType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_AudioFocusRequestNotification_request_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_AudioFocusRequestNotification_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    request,           1)
#define aap_protobuf_service_control_message_AudioFocusRequestNotification_CALLBACK NULL
#define aap_protobuf_service_control_message_AudioFocusRequestNotification_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_control_message_AudioFocusRequestNotification_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_AudioFocusRequestNotification_fields &aap_protobuf_service_control_message_AudioFocusRequestNotification_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AUDIOFOCUSREQUESTNOTIFICATION_PB_H_MAX_SIZE aap_protobuf_service_control_message_AudioFocusRequestNotification_size
#define aap_protobuf_service_control_message_AudioFocusRequestNotification_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
