/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AUDIOFOCUSREQUESTTYPE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AUDIOFOCUSREQUESTTYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_control_message_AudioFocusRequestType {
    aap_protobuf_service_control_message_AudioFocusRequestType_AUDIO_FOCUS_GAIN = 1,
    aap_protobuf_service_control_message_AudioFocusRequestType_AUDIO_FOCUS_GAIN_TRANSIENT = 2,
    aap_protobuf_service_control_message_AudioFocusRequestType_AUDIO_FOCUS_GAIN_TRANSIENT_MAY_DUCK = 3,
    aap_protobuf_service_control_message_AudioFocusRequestType_AUDIO_FOCUS_RELEASE = 4
} aap_protobuf_service_control_message_AudioFocusRequestType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_control_message_AudioFocusRequestType_MIN aap_protobuf_service_control_message_AudioFocusRequestType_AUDIO_FOCUS_GAIN
#define _aap_protobuf_service_control_message_AudioFocusRequestType_MAX aap_protobuf_service_control_message_AudioFocusRequestType_AUDIO_FOCUS_RELEASE
#define _aap_protobuf_service_control_message_AudioFocusRequestType_ARRAYSIZE ((aap_protobuf_service_control_message_AudioFocusRequestType)(aap_protobuf_service_control_message_AudioFocusRequestType_AUDIO_FOCUS_RELEASE+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
