/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AUDIOFOCUSSTATETYPE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AUDIOFOCUSSTATETYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_control_message_AudioFocusStateType {
    aap_protobuf_service_control_message_AudioFocusStateType_AUDIO_FOCUS_STATE_INVALID = 0,
    aap_protobuf_service_control_message_AudioFocusStateType_AUDIO_FOCUS_STATE_GAIN = 1,
    aap_protobuf_service_control_message_AudioFocusStateType_AUDIO_FOCUS_STATE_GAIN_TRANSIENT = 2,
    aap_protobuf_service_control_message_AudioFocusStateType_AUDIO_FOCUS_STATE_LOSS = 3,
    aap_protobuf_service_control_message_AudioFocusStateType_AUDIO_FOCUS_STATE_LOSS_TRANSIENT_CAN_DUCK = 4,
    aap_protobuf_service_control_message_AudioFocusStateType_AUDIO_FOCUS_STATE_LOSS_TRANSIENT = 5,
    aap_protobuf_service_control_message_AudioFocusStateType_AUDIO_FOCUS_STATE_GAIN_MEDIA_ONLY = 6,
    aap_protobuf_service_control_message_AudioFocusStateType_AUDIO_FOCUS_STATE_GAIN_TRANSIENT_GUIDANCE_ONLY = 7
} aap_protobuf_service_control_message_AudioFocusStateType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_control_message_AudioFocusStateType_MIN aap_protobuf_service_control_message_AudioFocusStateType_AUDIO_FOCUS_STATE_INVALID
#define _aap_protobuf_service_control_message_AudioFocusStateType_MAX aap_protobuf_service_control_message_AudioFocusStateType_AUDIO_FOCUS_STATE_GAIN_TRANSIENT_GUIDANCE_ONLY
#define _aap_protobuf_service_control_message_AudioFocusStateType_ARRAYSIZE ((aap_protobuf_service_control_message_AudioFocusStateType)(aap_protobuf_service_control_message_AudioFocusStateType_AUDIO_FOCUS_STATE_GAIN_TRANSIENT_GUIDANCE_ONLY+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
