/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_BATTERYSTATUSNOTIFICATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_BATTERYSTATUSNOTIFICATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_BatteryStatusNotification {
    uint32_t battery_level;
    bool has_time_remaining_s;
    uint32_t time_remaining_s;
    bool has_critical_battery;
    bool critical_battery;
} aap_protobuf_service_control_message_BatteryStatusNotification;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_BatteryStatusNotification_init_default {0, false, 0, false, 0}
#define aap_protobuf_service_control_message_BatteryStatusNotification_init_zero {0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_BatteryStatusNotification_battery_level_tag 1
#define aap_protobuf_service_control_message_BatteryStatusNotification_time_remaining_s_tag 2
#define aap_protobuf_service_control_message_BatteryStatusNotification_critical_battery_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_BatteryStatusNotification_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   battery_level,     1) \
X(a, STATIC,   OPTIONAL, UINT32,   time_remaining_s,   2) \
X(a, STATIC,   OPTIONAL, BOOL,     critical_battery,   3)
#define aap_protobuf_service_control_message_BatteryStatusNotification_CALLBACK NULL
#define aap_protobuf_service_control_message_BatteryStatusNotification_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_control_message_BatteryStatusNotification_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_BatteryStatusNotification_fields &aap_protobuf_service_control_message_BatteryStatusNotification_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_BATTERYSTATUSNOTIFICATION_PB_H_MAX_SIZE aap_protobuf_service_control_message_BatteryStatusNotification_size
#define aap_protobuf_service_control_message_BatteryStatusNotification_size 14

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
