/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_BYEBYEREASON_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_BYEBYEREASON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_control_message_ByeByeReason {
    aap_protobuf_service_control_message_ByeByeReason_USER_SELECTION = 1,
    aap_protobuf_service_control_message_ByeByeReason_DEVICE_SWITCH = 2,
    aap_protobuf_service_control_message_ByeByeReason_NOT_SUPPORTED = 3,
    aap_protobuf_service_control_message_ByeByeReason_NOT_CURRENTLY_SUPPORTED = 4,
    aap_protobuf_service_control_message_ByeByeReason_PROBE_SUPPORTED = 5
} aap_protobuf_service_control_message_ByeByeReason;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_control_message_ByeByeReason_MIN aap_protobuf_service_control_message_ByeByeReason_USER_SELECTION
#define _aap_protobuf_service_control_message_ByeByeReason_MAX aap_protobuf_service_control_message_ByeByeReason_PROBE_SUPPORTED
#define _aap_protobuf_service_control_message_ByeByeReason_ARRAYSIZE ((aap_protobuf_service_control_message_ByeByeReason)(aap_protobuf_service_control_message_ByeByeReason_PROBE_SUPPORTED+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
