/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_BYEBYEREQUEST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_BYEBYEREQUEST_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/control/message/ByeByeReason.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_ByeByeRequest {
    aap_protobuf_service_control_message_ByeByeReason reason;
} aap_protobuf_service_control_message_ByeByeRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_ByeByeRequest_init_default {_aap_protobuf_service_control_message_ByeByeReason_MIN}
#define aap_protobuf_service_control_message_ByeByeRequest_init_zero {_aap_protobuf_service_control_message_ByeByeReason_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_ByeByeRequest_reason_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_ByeByeRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    reason,            1)
#define aap_protobuf_service_control_message_ByeByeRequest_CALLBACK NULL
#define aap_protobuf_service_control_message_ByeByeRequest_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_control_message_ByeByeRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_ByeByeRequest_fields &aap_protobuf_service_control_message_ByeByeRequest_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_BYEBYEREQUEST_PB_H_MAX_SIZE aap_protobuf_service_control_message_ByeByeRequest_size
#define aap_protobuf_service_control_message_ByeByeRequest_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
