/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_CHANNELOPENREQUEST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_CHANNELOPENREQUEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_ChannelOpenRequest {
    int32_t priority;
    int32_t service_id;
} aap_protobuf_service_control_message_ChannelOpenRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_ChannelOpenRequest_init_default {0, 0}
#define aap_protobuf_service_control_message_ChannelOpenRequest_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_ChannelOpenRequest_priority_tag 1
#define aap_protobuf_service_control_message_ChannelOpenRequest_service_id_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_ChannelOpenRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, SINT32,   priority,          1) \
X(a, STATIC,   REQUIRED, INT32,    service_id,        2)
#define aap_protobuf_service_control_message_ChannelOpenRequest_CALLBACK NULL
#define aap_protobuf_service_control_message_ChannelOpenRequest_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_control_message_ChannelOpenRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_ChannelOpenRequest_fields &aap_protobuf_service_control_message_ChannelOpenRequest_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_CHANNELOPENREQUEST_PB_H_MAX_SIZE aap_protobuf_service_control_message_ChannelOpenRequest_size
#define aap_protobuf_service_control_message_ChannelOpenRequest_size 17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
