/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_CONNECTIONCONFIGURATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_CONNECTIONCONFIGURATION_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/control/message/PingConfiguration.pb.h"
#include "aap_protobuf/service/control/message/WirelessTcpConfiguration.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_ConnectionConfiguration {
    bool has_ping_configuration;
    aap_protobuf_service_control_message_PingConfiguration ping_configuration;
    bool has_wireless_tcp_configuration;
    aap_protobuf_service_control_message_WirelessTcpConfiguration wireless_tcp_configuration;
} aap_protobuf_service_control_message_ConnectionConfiguration;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_ConnectionConfiguration_init_default {false, aap_protobuf_service_control_message_PingConfiguration_init_default, false, aap_protobuf_service_control_message_WirelessTcpConfiguration_init_default}
#define aap_protobuf_service_control_message_ConnectionConfiguration_init_zero {false, aap_protobuf_service_control_message_PingConfiguration_init_zero, false, aap_protobuf_service_control_message_WirelessTcpConfiguration_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_ConnectionConfiguration_ping_configuration_tag 1
#define aap_protobuf_service_control_message_ConnectionConfiguration_wireless_tcp_configuration_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_ConnectionConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ping_configuration,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  wireless_tcp_configuration,   2)
#define aap_protobuf_service_control_message_ConnectionConfiguration_CALLBACK NULL
#define aap_protobuf_service_control_message_ConnectionConfiguration_DEFAULT NULL
#define aap_protobuf_service_control_message_ConnectionConfiguration_ping_configuration_MSGTYPE aap_protobuf_service_control_message_PingConfiguration
#define aap_protobuf_service_control_message_ConnectionConfiguration_wireless_tcp_configuration_MSGTYPE aap_protobuf_service_control_message_WirelessTcpConfiguration

extern const pb_msgdesc_t aap_protobuf_service_control_message_ConnectionConfiguration_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_ConnectionConfiguration_fields &aap_protobuf_service_control_message_ConnectionConfiguration_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_CONNECTIONCONFIGURATION_PB_H_MAX_SIZE aap_protobuf_service_control_message_ConnectionConfiguration_size
#define aap_protobuf_service_control_message_ConnectionConfiguration_size 46

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
