/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_DRIVERPOSITION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_DRIVERPOSITION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_control_message_DriverPosition {
    aap_protobuf_service_control_message_DriverPosition_DRIVER_POSITION_LEFT = 0,
    aap_protobuf_service_control_message_DriverPosition_DRIVER_POSITION_RIGHT = 1,
    aap_protobuf_service_control_message_DriverPosition_DRIVER_POSITION_CENTER = 2,
    aap_protobuf_service_control_message_DriverPosition_DRIVER_POSITION_UNKNOWN = 3
} aap_protobuf_service_control_message_DriverPosition;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_control_message_DriverPosition_MIN aap_protobuf_service_control_message_DriverPosition_DRIVER_POSITION_LEFT
#define _aap_protobuf_service_control_message_DriverPosition_MAX aap_protobuf_service_control_message_DriverPosition_DRIVER_POSITION_UNKNOWN
#define _aap_protobuf_service_control_message_DriverPosition_ARRAYSIZE ((aap_protobuf_service_control_message_DriverPosition)(aap_protobuf_service_control_message_DriverPosition_DRIVER_POSITION_UNKNOWN+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
