/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_FRAGINFO_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_FRAGINFO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_control_message_FragInfo {
    aap_protobuf_service_control_message_FragInfo_FRAG_CONTINUATION = 0,
    aap_protobuf_service_control_message_FragInfo_FRAG_FIRST = 1,
    aap_protobuf_service_control_message_FragInfo_FRAG_LAST = 2,
    aap_protobuf_service_control_message_FragInfo_FRAG_UNFRAGMENTED = 3
} aap_protobuf_service_control_message_FragInfo;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_control_message_FragInfo_MIN aap_protobuf_service_control_message_FragInfo_FRAG_CONTINUATION
#define _aap_protobuf_service_control_message_FragInfo_MAX aap_protobuf_service_control_message_FragInfo_FRAG_UNFRAGMENTED
#define _aap_protobuf_service_control_message_FragInfo_ARRAYSIZE ((aap_protobuf_service_control_message_FragInfo)(aap_protobuf_service_control_message_FragInfo_FRAG_UNFRAGMENTED+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
