/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_HEADUNITINFO_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_HEADUNITINFO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_HeadUnitInfo {
    bool has_make;
    char make[64];
    bool has_model;
    char model[64];
    bool has_year;
    char year[64];
    bool has_vehicle_id;
    char vehicle_id[64];
    bool has_head_unit_make;
    char head_unit_make[64];
    bool has_head_unit_model;
    char head_unit_model[64];
    bool has_head_unit_software_build;
    char head_unit_software_build[64];
    bool has_head_unit_software_version;
    char head_unit_software_version[64];
} aap_protobuf_service_control_message_HeadUnitInfo;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_HeadUnitInfo_init_default {false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, ""}
#define aap_protobuf_service_control_message_HeadUnitInfo_init_zero {false, "", false, "", false, "", false, "", false, "", false, "", false, "", false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_HeadUnitInfo_make_tag 1
#define aap_protobuf_service_control_message_HeadUnitInfo_model_tag 2
#define aap_protobuf_service_control_message_HeadUnitInfo_year_tag 3
#define aap_protobuf_service_control_message_HeadUnitInfo_vehicle_id_tag 4
#define aap_protobuf_service_control_message_HeadUnitInfo_head_unit_make_tag 5
#define aap_protobuf_service_control_message_HeadUnitInfo_head_unit_model_tag 6
#define aap_protobuf_service_control_message_HeadUnitInfo_head_unit_software_build_tag 7
#define aap_protobuf_service_control_message_HeadUnitInfo_head_unit_software_version_tag 8

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_HeadUnitInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   make,              1) \
X(a, STATIC,   OPTIONAL, STRING,   model,             2) \
X(a, STATIC,   OPTIONAL, STRING,   year,              3) \
X(a, STATIC,   OPTIONAL, STRING,   vehicle_id,        4) \
X(a, STATIC,   OPTIONAL, STRING,   head_unit_make,    5) \
X(a, STATIC,   OPTIONAL, STRING,   head_unit_model,   6) \
X(a, STATIC,   OPTIONAL, STRING,   head_unit_software_build,   7) \
X(a, STATIC,   OPTIONAL, STRING,   head_unit_software_version,   8)
#define aap_protobuf_service_control_message_HeadUnitInfo_CALLBACK NULL
#define aap_protobuf_service_control_message_HeadUnitInfo_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_control_message_HeadUnitInfo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_HeadUnitInfo_fields &aap_protobuf_service_control_message_HeadUnitInfo_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_HEADUNITINFO_PB_H_MAX_SIZE aap_protobuf_service_control_message_HeadUnitInfo_size
#define aap_protobuf_service_control_message_HeadUnitInfo_size 520

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
