/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_NAVFOCUSREQUESTNOTIFICATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_NAVFOCUSREQUESTNOTIFICATION_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/control/message/NavFocusType.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_NavFocusRequestNotification {
    bool has_focus_type;
    aap_protobuf_service_control_message_NavFocusType focus_type;
} aap_protobuf_service_control_message_NavFocusRequestNotification;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_NavFocusRequestNotification_init_default {false, _aap_protobuf_service_control_message_NavFocusType_MIN}
#define aap_protobuf_service_control_message_NavFocusRequestNotification_init_zero {false, _aap_protobuf_service_control_message_NavFocusType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_NavFocusRequestNotification_focus_type_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_NavFocusRequestNotification_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    focus_type,        1)
#define aap_protobuf_service_control_message_NavFocusRequestNotification_CALLBACK NULL
#define aap_protobuf_service_control_message_NavFocusRequestNotification_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_control_message_NavFocusRequestNotification_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_NavFocusRequestNotification_fields &aap_protobuf_service_control_message_NavFocusRequestNotification_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_NAVFOCUSREQUESTNOTIFICATION_PB_H_MAX_SIZE aap_protobuf_service_control_message_NavFocusRequestNotification_size
#define aap_protobuf_service_control_message_NavFocusRequestNotification_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
