/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_NAVFOCUSTYPE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_NAVFOCUSTYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_control_message_NavFocusType {
    aap_protobuf_service_control_message_NavFocusType_NAV_FOCUS_NATIVE = 1,
    aap_protobuf_service_control_message_NavFocusType_NAV_FOCUS_PROJECTED = 2
} aap_protobuf_service_control_message_NavFocusType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_control_message_NavFocusType_MIN aap_protobuf_service_control_message_NavFocusType_NAV_FOCUS_NATIVE
#define _aap_protobuf_service_control_message_NavFocusType_MAX aap_protobuf_service_control_message_NavFocusType_NAV_FOCUS_PROJECTED
#define _aap_protobuf_service_control_message_NavFocusType_ARRAYSIZE ((aap_protobuf_service_control_message_NavFocusType)(aap_protobuf_service_control_message_NavFocusType_NAV_FOCUS_PROJECTED+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
