/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_PINGRESPONSE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_PINGRESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_control_message_PingResponse_data_t;
typedef struct _aap_protobuf_service_control_message_PingResponse {
    int64_t timestamp;
    bool has_data;
    aap_protobuf_service_control_message_PingResponse_data_t data;
} aap_protobuf_service_control_message_PingResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_PingResponse_init_default {0, false, {0, {0}}}
#define aap_protobuf_service_control_message_PingResponse_init_zero {0, false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_PingResponse_timestamp_tag 1
#define aap_protobuf_service_control_message_PingResponse_data_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_PingResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT64,    timestamp,         1) \
X(a, STATIC,   OPTIONAL, BYTES,    data,              2)
#define aap_protobuf_service_control_message_PingResponse_CALLBACK NULL
#define aap_protobuf_service_control_message_PingResponse_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_control_message_PingResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_PingResponse_fields &aap_protobuf_service_control_message_PingResponse_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_PINGRESPONSE_PB_H_MAX_SIZE aap_protobuf_service_control_message_PingResponse_size
#define aap_protobuf_service_control_message_PingResponse_size 77

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
