/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_PINGREQUEST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_PINGREQUEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_control_message_PingRequest_data_t;
typedef struct _aap_protobuf_service_control_message_PingRequest {
    int64_t timestamp;
    bool has_bug_report;
    bool bug_report;
    bool has_data;
    aap_protobuf_service_control_message_PingRequest_data_t data;
} aap_protobuf_service_control_message_PingRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_PingRequest_init_default {0, false, 0, false, {0, {0}}}
#define aap_protobuf_service_control_message_PingRequest_init_zero {0, false, 0, false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_PingRequest_timestamp_tag 1
#define aap_protobuf_service_control_message_PingRequest_bug_report_tag 2
#define aap_protobuf_service_control_message_PingRequest_data_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_PingRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT64,    timestamp,         1) \
X(a, STATIC,   OPTIONAL, BOOL,     bug_report,        2) \
X(a, STATIC,   OPTIONAL, BYTES,    data,              3)
#define aap_protobuf_service_control_message_PingRequest_CALLBACK NULL
#define aap_protobuf_service_control_message_PingRequest_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_control_message_PingRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_PingRequest_fields &aap_protobuf_service_control_message_PingRequest_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_PINGREQUEST_PB_H_MAX_SIZE aap_protobuf_service_control_message_PingRequest_size
#define aap_protobuf_service_control_message_PingRequest_size 79

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
