/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_SERVICEDISCOVERYREQUEST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_SERVICEDISCOVERYREQUEST_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/shared/PhoneInfo.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_control_message_ServiceDiscoveryRequest_small_icon_t;
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_control_message_ServiceDiscoveryRequest_medium_icon_t;
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_control_message_ServiceDiscoveryRequest_large_icon_t;
typedef struct _aap_protobuf_service_control_message_ServiceDiscoveryRequest {
    bool has_small_icon;
    aap_protobuf_service_control_message_ServiceDiscoveryRequest_small_icon_t small_icon;
    bool has_medium_icon;
    aap_protobuf_service_control_message_ServiceDiscoveryRequest_medium_icon_t medium_icon;
    bool has_large_icon;
    aap_protobuf_service_control_message_ServiceDiscoveryRequest_large_icon_t large_icon;
    bool has_label_text;
    char label_text[64];
    bool has_device_name;
    char device_name[64];
    bool has_phone_info;
    aap_protobuf_shared_PhoneInfo phone_info;
} aap_protobuf_service_control_message_ServiceDiscoveryRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_init_default {false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, "", false, "", false, aap_protobuf_shared_PhoneInfo_init_default}
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_init_zero {false, {0, {0}}, false, {0, {0}}, false, {0, {0}}, false, "", false, "", false, aap_protobuf_shared_PhoneInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_small_icon_tag 1
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_medium_icon_tag 2
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_large_icon_tag 3
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_label_text_tag 4
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_device_name_tag 5
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_phone_info_tag 6

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BYTES,    small_icon,        1) \
X(a, STATIC,   OPTIONAL, BYTES,    medium_icon,       2) \
X(a, STATIC,   OPTIONAL, BYTES,    large_icon,        3) \
X(a, STATIC,   OPTIONAL, STRING,   label_text,        4) \
X(a, STATIC,   OPTIONAL, STRING,   device_name,       5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  phone_info,        6)
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_CALLBACK NULL
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_DEFAULT NULL
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_phone_info_MSGTYPE aap_protobuf_shared_PhoneInfo

extern const pb_msgdesc_t aap_protobuf_service_control_message_ServiceDiscoveryRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_fields &aap_protobuf_service_control_message_ServiceDiscoveryRequest_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_SERVICEDISCOVERYREQUEST_PB_H_MAX_SIZE aap_protobuf_service_control_message_ServiceDiscoveryRequest_size
#define aap_protobuf_service_control_message_ServiceDiscoveryRequest_size 461

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
