/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_SERVICEDISCOVERYUPDATE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_SERVICEDISCOVERYUPDATE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/Service.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_ServiceDiscoveryUpdate {
    bool has_service;
    aap_protobuf_service_Service service;
} aap_protobuf_service_control_message_ServiceDiscoveryUpdate;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_ServiceDiscoveryUpdate_init_default {false, aap_protobuf_service_Service_init_default}
#define aap_protobuf_service_control_message_ServiceDiscoveryUpdate_init_zero {false, aap_protobuf_service_Service_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_ServiceDiscoveryUpdate_service_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_ServiceDiscoveryUpdate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  service,           1)
#define aap_protobuf_service_control_message_ServiceDiscoveryUpdate_CALLBACK NULL
#define aap_protobuf_service_control_message_ServiceDiscoveryUpdate_DEFAULT NULL
#define aap_protobuf_service_control_message_ServiceDiscoveryUpdate_service_MSGTYPE aap_protobuf_service_Service

extern const pb_msgdesc_t aap_protobuf_service_control_message_ServiceDiscoveryUpdate_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_ServiceDiscoveryUpdate_fields &aap_protobuf_service_control_message_ServiceDiscoveryUpdate_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_SERVICEDISCOVERYUPDATE_PB_H_MAX_SIZE aap_protobuf_service_control_message_ServiceDiscoveryUpdate_size
#define aap_protobuf_service_control_message_ServiceDiscoveryUpdate_size 5808

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
