/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_UPDATEUICONFIGREPLY_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_UPDATEUICONFIGREPLY_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/media/shared/message/UiConfig.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_UpdateUiConfigReply {
    bool has_ui_config;
    aap_protobuf_service_media_shared_message_UiConfig ui_config;
} aap_protobuf_service_control_message_UpdateUiConfigReply;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_UpdateUiConfigReply_init_default {false, aap_protobuf_service_media_shared_message_UiConfig_init_default}
#define aap_protobuf_service_control_message_UpdateUiConfigReply_init_zero {false, aap_protobuf_service_media_shared_message_UiConfig_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_UpdateUiConfigReply_ui_config_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_UpdateUiConfigReply_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ui_config,         1)
#define aap_protobuf_service_control_message_UpdateUiConfigReply_CALLBACK NULL
#define aap_protobuf_service_control_message_UpdateUiConfigReply_DEFAULT NULL
#define aap_protobuf_service_control_message_UpdateUiConfigReply_ui_config_MSGTYPE aap_protobuf_service_media_shared_message_UiConfig

extern const pb_msgdesc_t aap_protobuf_service_control_message_UpdateUiConfigReply_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_UpdateUiConfigReply_fields &aap_protobuf_service_control_message_UpdateUiConfigReply_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_UPDATEUICONFIGREPLY_PB_H_MAX_SIZE aap_protobuf_service_control_message_UpdateUiConfigReply_size
#define aap_protobuf_service_control_message_UpdateUiConfigReply_size 82

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
