/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_USERSWITCHREQUEST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_USERSWITCHREQUEST_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/control/message/ConnectedDevice.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_UserSwitchRequest {
    bool has_selected_device;
    aap_protobuf_service_control_message_ConnectedDevice selected_device;
} aap_protobuf_service_control_message_UserSwitchRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_UserSwitchRequest_init_default {false, aap_protobuf_service_control_message_ConnectedDevice_init_default}
#define aap_protobuf_service_control_message_UserSwitchRequest_init_zero {false, aap_protobuf_service_control_message_ConnectedDevice_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_UserSwitchRequest_selected_device_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_UserSwitchRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  selected_device,   1)
#define aap_protobuf_service_control_message_UserSwitchRequest_CALLBACK NULL
#define aap_protobuf_service_control_message_UserSwitchRequest_DEFAULT NULL
#define aap_protobuf_service_control_message_UserSwitchRequest_selected_device_MSGTYPE aap_protobuf_service_control_message_ConnectedDevice

extern const pb_msgdesc_t aap_protobuf_service_control_message_UserSwitchRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_UserSwitchRequest_fields &aap_protobuf_service_control_message_UserSwitchRequest_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_USERSWITCHREQUEST_PB_H_MAX_SIZE aap_protobuf_service_control_message_UserSwitchRequest_size
#define aap_protobuf_service_control_message_UserSwitchRequest_size 78

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
