/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_CHANNEL_CONTROL_VERSION_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_VERSIONREQUESTOPTIONS_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_CHANNEL_CONTROL_VERSION_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_VERSIONREQUESTOPTIONS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_channel_control_version_VersionRequestOptions {
    bool has_snapshot_version;
    int64_t snapshot_version;
} aap_protobuf_channel_control_version_VersionRequestOptions;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_channel_control_version_VersionRequestOptions_init_default {false, 0}
#define aap_protobuf_channel_control_version_VersionRequestOptions_init_zero {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_channel_control_version_VersionRequestOptions_snapshot_version_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_channel_control_version_VersionRequestOptions_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT64,    snapshot_version,   1)
#define aap_protobuf_channel_control_version_VersionRequestOptions_CALLBACK NULL
#define aap_protobuf_channel_control_version_VersionRequestOptions_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_channel_control_version_VersionRequestOptions_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_channel_control_version_VersionRequestOptions_fields &aap_protobuf_channel_control_version_VersionRequestOptions_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_CHANNEL_CONTROL_VERSION_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_VERSIONREQUESTOPTIONS_PB_H_MAX_SIZE aap_protobuf_channel_control_version_VersionRequestOptions_size
#define aap_protobuf_channel_control_version_VersionRequestOptions_size 11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
