/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_VOICESESSIONNOTIFICATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_VOICESESSIONNOTIFICATION_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/control/message/VoiceSessionStatus.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_VoiceSessionNotification {
    bool has_status;
    aap_protobuf_service_control_message_VoiceSessionStatus status;
} aap_protobuf_service_control_message_VoiceSessionNotification;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_VoiceSessionNotification_init_default {false, _aap_protobuf_service_control_message_VoiceSessionStatus_MIN}
#define aap_protobuf_service_control_message_VoiceSessionNotification_init_zero {false, _aap_protobuf_service_control_message_VoiceSessionStatus_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_VoiceSessionNotification_status_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_VoiceSessionNotification_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    status,            1)
#define aap_protobuf_service_control_message_VoiceSessionNotification_CALLBACK NULL
#define aap_protobuf_service_control_message_VoiceSessionNotification_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_control_message_VoiceSessionNotification_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_VoiceSessionNotification_fields &aap_protobuf_service_control_message_VoiceSessionNotification_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_VOICESESSIONNOTIFICATION_PB_H_MAX_SIZE aap_protobuf_service_control_message_VoiceSessionNotification_size
#define aap_protobuf_service_control_message_VoiceSessionNotification_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
