/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_VOICESESSIONSTATUS_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_VOICESESSIONSTATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_control_message_VoiceSessionStatus {
    aap_protobuf_service_control_message_VoiceSessionStatus_VOICE_SESSION_START = 1,
    aap_protobuf_service_control_message_VoiceSessionStatus_VOICE_SESSION_END = 2
} aap_protobuf_service_control_message_VoiceSessionStatus;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_control_message_VoiceSessionStatus_MIN aap_protobuf_service_control_message_VoiceSessionStatus_VOICE_SESSION_START
#define _aap_protobuf_service_control_message_VoiceSessionStatus_MAX aap_protobuf_service_control_message_VoiceSessionStatus_VOICE_SESSION_END
#define _aap_protobuf_service_control_message_VoiceSessionStatus_ARRAYSIZE ((aap_protobuf_service_control_message_VoiceSessionStatus)(aap_protobuf_service_control_message_VoiceSessionStatus_VOICE_SESSION_END+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
