/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_WIRELESSTCPCONFIGURATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_WIRELESSTCPCONFIGURATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_WirelessTcpConfiguration {
    bool has_socket_receive_buffer_size_kb;
    uint32_t socket_receive_buffer_size_kb;
    bool has_socket_send_buffer_size_kb;
    uint32_t socket_send_buffer_size_kb;
    bool has_socket_read_timeout_ms;
    uint32_t socket_read_timeout_ms;
} aap_protobuf_service_control_message_WirelessTcpConfiguration;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_WirelessTcpConfiguration_init_default {false, 0, false, 0, false, 0}
#define aap_protobuf_service_control_message_WirelessTcpConfiguration_init_zero {false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_WirelessTcpConfiguration_socket_receive_buffer_size_kb_tag 1
#define aap_protobuf_service_control_message_WirelessTcpConfiguration_socket_send_buffer_size_kb_tag 2
#define aap_protobuf_service_control_message_WirelessTcpConfiguration_socket_read_timeout_ms_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_WirelessTcpConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   socket_receive_buffer_size_kb,   1) \
X(a, STATIC,   OPTIONAL, UINT32,   socket_send_buffer_size_kb,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   socket_read_timeout_ms,   3)
#define aap_protobuf_service_control_message_WirelessTcpConfiguration_CALLBACK NULL
#define aap_protobuf_service_control_message_WirelessTcpConfiguration_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_control_message_WirelessTcpConfiguration_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_WirelessTcpConfiguration_fields &aap_protobuf_service_control_message_WirelessTcpConfiguration_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_WIRELESSTCPCONFIGURATION_PB_H_MAX_SIZE aap_protobuf_service_control_message_WirelessTcpConfiguration_size
#define aap_protobuf_service_control_message_WirelessTcpConfiguration_size 18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
