/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_CONTROLMESSAGETYPE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_SERVICE_CONTROL_CONTROLMESSAGETYPE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_control_message_ControlMessageType {
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_VERSION_REQUEST = 1,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_VERSION_RESPONSE = 2,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_ENCAPSULATED_SSL = 3,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_AUTH_COMPLETE = 4,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_SERVICE_DISCOVERY_REQUEST = 5,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_SERVICE_DISCOVERY_RESPONSE = 6,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_CHANNEL_OPEN_REQUEST = 7,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_CHANNEL_OPEN_RESPONSE = 8,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_CHANNEL_CLOSE_NOTIFICATION = 9,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_PING_REQUEST = 11,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_PING_RESPONSE = 12,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_NAV_FOCUS_REQUEST = 13,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_NAV_FOCUS_NOTIFICATION = 14,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_BYEBYE_REQUEST = 15,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_BYEBYE_RESPONSE = 16,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_VOICE_SESSION_NOTIFICATION = 17,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_AUDIO_FOCUS_REQUEST = 18,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_AUDIO_FOCUS_NOTIFICATION = 19,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_CAR_CONNECTED_DEVICES_REQUEST = 20,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_CAR_CONNECTED_DEVICES_RESPONSE = 21,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_USER_SWITCH_REQUEST = 22,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_BATTERY_STATUS_NOTIFICATION = 23,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_CALL_AVAILABILITY_STATUS = 24,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_USER_SWITCH_RESPONSE = 25,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_SERVICE_DISCOVERY_UPDATE = 26,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_UNEXPECTED_MESSAGE = 255,
    aap_protobuf_service_control_message_ControlMessageType_MESSAGE_FRAMING_ERROR = 65535
} aap_protobuf_service_control_message_ControlMessageType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_control_message_ControlMessageType_MIN aap_protobuf_service_control_message_ControlMessageType_MESSAGE_VERSION_REQUEST
#define _aap_protobuf_service_control_message_ControlMessageType_MAX aap_protobuf_service_control_message_ControlMessageType_MESSAGE_FRAMING_ERROR
#define _aap_protobuf_service_control_message_ControlMessageType_ARRAYSIZE ((aap_protobuf_service_control_message_ControlMessageType)(aap_protobuf_service_control_message_ControlMessageType_MESSAGE_FRAMING_ERROR+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
