/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_VIDEO_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_VIDEO_MESSAGE_VIDEOFOCUSMODE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_VIDEO_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_VIDEO_MESSAGE_VIDEOFOCUSMODE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_media_video_message_VideoFocusMode {
    aap_protobuf_service_media_video_message_VideoFocusMode_VIDEO_FOCUS_PROJECTED = 1,
    aap_protobuf_service_media_video_message_VideoFocusMode_VIDEO_FOCUS_NATIVE = 2,
    aap_protobuf_service_media_video_message_VideoFocusMode_VIDEO_FOCUS_NATIVE_TRANSIENT = 3,
    aap_protobuf_service_media_video_message_VideoFocusMode_VIDEO_FOCUS_PROJECTED_NO_INPUT_FOCUS = 4
} aap_protobuf_service_media_video_message_VideoFocusMode;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_media_video_message_VideoFocusMode_MIN aap_protobuf_service_media_video_message_VideoFocusMode_VIDEO_FOCUS_PROJECTED
#define _aap_protobuf_service_media_video_message_VideoFocusMode_MAX aap_protobuf_service_media_video_message_VideoFocusMode_VIDEO_FOCUS_PROJECTED_NO_INPUT_FOCUS
#define _aap_protobuf_service_media_video_message_VideoFocusMode_ARRAYSIZE ((aap_protobuf_service_media_video_message_VideoFocusMode)(aap_protobuf_service_media_video_message_VideoFocusMode_VIDEO_FOCUS_PROJECTED_NO_INPUT_FOCUS+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
