/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_VIDEO_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_VIDEO_MESSAGE_VIDEOFOCUSREQUESTNOTIFICATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_VIDEO_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_VIDEO_MESSAGE_VIDEOFOCUSREQUESTNOTIFICATION_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/media/video/message/VideoFocusMode.pb.h"
#include "aap_protobuf/service/media/video/message/VideoFocusReason.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_media_video_message_VideoFocusRequestNotification {
    bool has_disp_channel_id;
    int32_t disp_channel_id;
    bool has_mode;
    aap_protobuf_service_media_video_message_VideoFocusMode mode;
    bool has_reason;
    aap_protobuf_service_media_video_message_VideoFocusReason reason;
} aap_protobuf_service_media_video_message_VideoFocusRequestNotification;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_media_video_message_VideoFocusRequestNotification_init_default {false, 0, false, _aap_protobuf_service_media_video_message_VideoFocusMode_MIN, false, _aap_protobuf_service_media_video_message_VideoFocusReason_MIN}
#define aap_protobuf_service_media_video_message_VideoFocusRequestNotification_init_zero {false, 0, false, _aap_protobuf_service_media_video_message_VideoFocusMode_MIN, false, _aap_protobuf_service_media_video_message_VideoFocusReason_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_media_video_message_VideoFocusRequestNotification_disp_channel_id_tag 1
#define aap_protobuf_service_media_video_message_VideoFocusRequestNotification_mode_tag 2
#define aap_protobuf_service_media_video_message_VideoFocusRequestNotification_reason_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_media_video_message_VideoFocusRequestNotification_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    disp_channel_id,   1) \
X(a, STATIC,   OPTIONAL, UENUM,    mode,              2) \
X(a, STATIC,   OPTIONAL, UENUM,    reason,            3)
#define aap_protobuf_service_media_video_message_VideoFocusRequestNotification_CALLBACK NULL
#define aap_protobuf_service_media_video_message_VideoFocusRequestNotification_DEFAULT (const pb_byte_t*)"\x10\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_media_video_message_VideoFocusRequestNotification_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_media_video_message_VideoFocusRequestNotification_fields &aap_protobuf_service_media_video_message_VideoFocusRequestNotification_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIA_VIDEO_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_VIDEO_MESSAGE_VIDEOFOCUSREQUESTNOTIFICATION_PB_H_MAX_SIZE aap_protobuf_service_media_video_message_VideoFocusRequestNotification_size
#define aap_protobuf_service_media_video_message_VideoFocusRequestNotification_size 15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
