/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_AAP_PROTOBUF_SERVICE_SERVICE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_AAP_PROTOBUF_SERVICE_SERVICE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/sensorsource/SensorSourceService.pb.h"
#include "aap_protobuf/service/media/sink/MediaSinkService.pb.h"
#include "aap_protobuf/service/inputsource/InputSourceService.pb.h"
#include "aap_protobuf/service/media/source/MediaSourceService.pb.h"
#include "aap_protobuf/service/bluetooth/BluetoothService.pb.h"
#include "aap_protobuf/service/navigationstatus/NavigationStatusService.pb.h"
#include "aap_protobuf/service/vendorextension/VendorExtensionService.pb.h"
#include "aap_protobuf/service/wifiprojection/WifiProjectionService.pb.h"
#include "aap_protobuf/service/mediabrowser/MediaBrowserService.pb.h"
#include "aap_protobuf/service/genericnotification/GenericNotificationService.pb.h"
#include "aap_protobuf/service/phonestatus/PhoneStatusService.pb.h"
#include "aap_protobuf/service/mediaplayback/MediaPlaybackStatusService.pb.h"
#include "aap_protobuf/service/radio/RadioService.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_Service {
    int32_t id;
    bool has_sensor_source_service;
    aap_protobuf_service_sensorsource_SensorSourceService sensor_source_service;
    bool has_media_sink_service;
    aap_protobuf_service_media_sink_MediaSinkService media_sink_service;
    bool has_input_source_service;
    aap_protobuf_service_inputsource_InputSourceService input_source_service;
    bool has_media_source_service;
    aap_protobuf_service_media_source_MediaSourceService media_source_service;
    bool has_bluetooth_service;
    aap_protobuf_service_bluetooth_BluetoothService bluetooth_service;
    bool has_radio_service;
    aap_protobuf_service_radio_RadioService radio_service;
    bool has_navigation_status_service;
    aap_protobuf_service_navigationstatus_NavigationStatusService navigation_status_service;
    bool has_media_playback_service;
    aap_protobuf_service_mediaplayback_MediaPlaybackStatusService media_playback_service;
    bool has_phone_status_service;
    aap_protobuf_service_phonestatus_PhoneStatusService phone_status_service;
    bool has_media_browser_service;
    aap_protobuf_service_mediabrowser_MediaBrowserService media_browser_service;
    bool has_vendor_extension_service;
    aap_protobuf_service_vendorextension_VendorExtensionService vendor_extension_service;
    bool has_generic_notification_service;
    aap_protobuf_service_genericnotification_GenericNotificationService generic_notification_service;
    bool has_wifi_projection_service;
    aap_protobuf_service_wifiprojection_WifiProjectionService wifi_projection_service;
} aap_protobuf_service_Service;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_Service_init_default {0, false, aap_protobuf_service_sensorsource_SensorSourceService_init_default, false, aap_protobuf_service_media_sink_MediaSinkService_init_default, false, aap_protobuf_service_inputsource_InputSourceService_init_default, false, aap_protobuf_service_media_source_MediaSourceService_init_default, false, aap_protobuf_service_bluetooth_BluetoothService_init_default, false, aap_protobuf_service_radio_RadioService_init_default, false, aap_protobuf_service_navigationstatus_NavigationStatusService_init_default, false, aap_protobuf_service_mediaplayback_MediaPlaybackStatusService_init_default, false, aap_protobuf_service_phonestatus_PhoneStatusService_init_default, false, aap_protobuf_service_mediabrowser_MediaBrowserService_init_default, false, aap_protobuf_service_vendorextension_VendorExtensionService_init_default, false, aap_protobuf_service_genericnotification_GenericNotificationService_init_default, false, aap_protobuf_service_wifiprojection_WifiProjectionService_init_default}
#define aap_protobuf_service_Service_init_zero   {0, false, aap_protobuf_service_sensorsource_SensorSourceService_init_zero, false, aap_protobuf_service_media_sink_MediaSinkService_init_zero, false, aap_protobuf_service_inputsource_InputSourceService_init_zero, false, aap_protobuf_service_media_source_MediaSourceService_init_zero, false, aap_protobuf_service_bluetooth_BluetoothService_init_zero, false, aap_protobuf_service_radio_RadioService_init_zero, false, aap_protobuf_service_navigationstatus_NavigationStatusService_init_zero, false, aap_protobuf_service_mediaplayback_MediaPlaybackStatusService_init_zero, false, aap_protobuf_service_phonestatus_PhoneStatusService_init_zero, false, aap_protobuf_service_mediabrowser_MediaBrowserService_init_zero, false, aap_protobuf_service_vendorextension_VendorExtensionService_init_zero, false, aap_protobuf_service_genericnotification_GenericNotificationService_init_zero, false, aap_protobuf_service_wifiprojection_WifiProjectionService_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_Service_id_tag      1
#define aap_protobuf_service_Service_sensor_source_service_tag 2
#define aap_protobuf_service_Service_media_sink_service_tag 3
#define aap_protobuf_service_Service_input_source_service_tag 4
#define aap_protobuf_service_Service_media_source_service_tag 5
#define aap_protobuf_service_Service_bluetooth_service_tag 6
#define aap_protobuf_service_Service_radio_service_tag 7
#define aap_protobuf_service_Service_navigation_status_service_tag 8
#define aap_protobuf_service_Service_media_playback_service_tag 9
#define aap_protobuf_service_Service_phone_status_service_tag 10
#define aap_protobuf_service_Service_media_browser_service_tag 11
#define aap_protobuf_service_Service_vendor_extension_service_tag 12
#define aap_protobuf_service_Service_generic_notification_service_tag 13
#define aap_protobuf_service_Service_wifi_projection_service_tag 14

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_Service_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sensor_source_service,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  media_sink_service,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  input_source_service,   4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  media_source_service,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bluetooth_service,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  radio_service,     7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  navigation_status_service,   8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  media_playback_service,   9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  phone_status_service,  10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  media_browser_service,  11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vendor_extension_service,  12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  generic_notification_service,  13) \
X(a, STATIC,   OPTIONAL, MESSAGE,  wifi_projection_service,  14)
#define aap_protobuf_service_Service_CALLBACK NULL
#define aap_protobuf_service_Service_DEFAULT NULL
#define aap_protobuf_service_Service_sensor_source_service_MSGTYPE aap_protobuf_service_sensorsource_SensorSourceService
#define aap_protobuf_service_Service_media_sink_service_MSGTYPE aap_protobuf_service_media_sink_MediaSinkService
#define aap_protobuf_service_Service_input_source_service_MSGTYPE aap_protobuf_service_inputsource_InputSourceService
#define aap_protobuf_service_Service_media_source_service_MSGTYPE aap_protobuf_service_media_source_MediaSourceService
#define aap_protobuf_service_Service_bluetooth_service_MSGTYPE aap_protobuf_service_bluetooth_BluetoothService
#define aap_protobuf_service_Service_radio_service_MSGTYPE aap_protobuf_service_radio_RadioService
#define aap_protobuf_service_Service_navigation_status_service_MSGTYPE aap_protobuf_service_navigationstatus_NavigationStatusService
#define aap_protobuf_service_Service_media_playback_service_MSGTYPE aap_protobuf_service_mediaplayback_MediaPlaybackStatusService
#define aap_protobuf_service_Service_phone_status_service_MSGTYPE aap_protobuf_service_phonestatus_PhoneStatusService
#define aap_protobuf_service_Service_media_browser_service_MSGTYPE aap_protobuf_service_mediabrowser_MediaBrowserService
#define aap_protobuf_service_Service_vendor_extension_service_MSGTYPE aap_protobuf_service_vendorextension_VendorExtensionService
#define aap_protobuf_service_Service_generic_notification_service_MSGTYPE aap_protobuf_service_genericnotification_GenericNotificationService
#define aap_protobuf_service_Service_wifi_projection_service_MSGTYPE aap_protobuf_service_wifiprojection_WifiProjectionService

extern const pb_msgdesc_t aap_protobuf_service_Service_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_Service_fields &aap_protobuf_service_Service_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_AAP_PROTOBUF_SERVICE_SERVICE_PB_H_MAX_SIZE aap_protobuf_service_Service_size
#define aap_protobuf_service_Service_size        5805

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
