[BlueTooth]
DeviceName=Ksmart
PairCode=0000
AutoConnect=1
[General]
AutoStartCarLink=1
AndroidLinkType=6
IphoneLinkType=3
EnableAvin=0
ReversingVolumeCut=0
FactoryPassword=8818
SettingItemTypes="0x83,0x84,0x85,0x93,0x94,0x80,0x81,0x82"
CarSetDefValue="0x83=2","0x93=1","0x94=1"
CarTrackImgMaxAngle=20
TouchCalibrateAction=0
#ListItemFocusLoopMode=0
VehicleName="HOLDEN"
HomeIconLabel="HOLDEN"
EnableMirroring=1
DoorPrompt=0
AutoStartMedia=1
MirroringLinkType=2
LinkFullScreen=1
EnableAircondition=1
Language=4096 
#DisableAAutoBluetooth=1 
DisablePhoneLinkAudio=1
IgnoreMediaKey=1
#EnableMusic=0
#EnableVideo=0
#AECDelay=150
Volume=32 

KeyMaps-16="0"
KeyMaps-17="0"
Knob-20="0=0,0=0"
Knob-22="0=0,0=0"
Knob-23="0=0,0=0"
 
[Sound]
SysChannel=0
BTChannel=2