/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_GENERICNOTIFICATION_MESSAGE_AAP_PROTOBUF_SERVICE_GENERICNOTIFICATION_MESSAGE_GENERICNOTIFICATIONACK_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_GENERICNOTIFICATION_MESSAGE_AAP_PROTOBUF_SERVICE_GENERICNOTIFICATION_MESSAGE_GENERICNOTIFICATIONACK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_genericnotification_message_GenericNotificationAck {
    bool has_id;
    char id[64];
    bool has_handled;
    bool handled;
} aap_protobuf_service_genericnotification_message_GenericNotificationAck;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_genericnotification_message_GenericNotificationAck_init_default {false, "", false, 0}
#define aap_protobuf_service_genericnotification_message_GenericNotificationAck_init_zero {false, "", false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_genericnotification_message_GenericNotificationAck_id_tag 1
#define aap_protobuf_service_genericnotification_message_GenericNotificationAck_handled_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_genericnotification_message_GenericNotificationAck_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   id,                1) \
X(a, STATIC,   OPTIONAL, BOOL,     handled,           2)
#define aap_protobuf_service_genericnotification_message_GenericNotificationAck_CALLBACK NULL
#define aap_protobuf_service_genericnotification_message_GenericNotificationAck_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_genericnotification_message_GenericNotificationAck_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_genericnotification_message_GenericNotificationAck_fields &aap_protobuf_service_genericnotification_message_GenericNotificationAck_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_GENERICNOTIFICATION_MESSAGE_AAP_PROTOBUF_SERVICE_GENERICNOTIFICATION_MESSAGE_GENERICNOTIFICATIONACK_PB_H_MAX_SIZE aap_protobuf_service_genericnotification_message_GenericNotificationAck_size
#define aap_protobuf_service_genericnotification_message_GenericNotificationAck_size 67

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
