/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_GENERICNOTIFICATION_MESSAGE_AAP_PROTOBUF_SERVICE_GENERICNOTIFICATION_MESSAGE_GENERICNOTIFICATIONMESSAGE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_GENERICNOTIFICATION_MESSAGE_AAP_PROTOBUF_SERVICE_GENERICNOTIFICATION_MESSAGE_GENERICNOTIFICATIONMESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_genericnotification_message_GenericNotificationMessage_icon_t;
typedef struct _aap_protobuf_service_genericnotification_message_GenericNotificationMessage {
    bool has_id;
    char id[64];
    bool has_text;
    char text[64];
    bool has_icon;
    aap_protobuf_service_genericnotification_message_GenericNotificationMessage_icon_t icon;
} aap_protobuf_service_genericnotification_message_GenericNotificationMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_genericnotification_message_GenericNotificationMessage_init_default {false, "", false, "", false, {0, {0}}}
#define aap_protobuf_service_genericnotification_message_GenericNotificationMessage_init_zero {false, "", false, "", false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_genericnotification_message_GenericNotificationMessage_id_tag 1
#define aap_protobuf_service_genericnotification_message_GenericNotificationMessage_text_tag 2
#define aap_protobuf_service_genericnotification_message_GenericNotificationMessage_icon_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_genericnotification_message_GenericNotificationMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   id,                1) \
X(a, STATIC,   OPTIONAL, STRING,   text,              2) \
X(a, STATIC,   OPTIONAL, BYTES,    icon,              3)
#define aap_protobuf_service_genericnotification_message_GenericNotificationMessage_CALLBACK NULL
#define aap_protobuf_service_genericnotification_message_GenericNotificationMessage_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_genericnotification_message_GenericNotificationMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_genericnotification_message_GenericNotificationMessage_fields &aap_protobuf_service_genericnotification_message_GenericNotificationMessage_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_GENERICNOTIFICATION_MESSAGE_AAP_PROTOBUF_SERVICE_GENERICNOTIFICATION_MESSAGE_GENERICNOTIFICATIONMESSAGE_PB_H_MAX_SIZE aap_protobuf_service_genericnotification_message_GenericNotificationMessage_size
#define aap_protobuf_service_genericnotification_message_GenericNotificationMessage_size 196

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
