;-----------------------------------------------------------------
; ScreenType  | RGB565:1   RGB888:2   LVDS  :4  VGA   :8         |
;             | CVBS  :16  YPBPR :32  ITU656:64 ITU601:128       |
; Format      | RGB565:0   BGR565:1   RGB666:2  BGR666:3         |
;             | RGB888:7   BGR888:8                              |
; RgbMode     | BGR: 0     RGB: 5                                |
; TvoutType   | NTSC_M:1 NTSC_J:2 NTSC_443:3 PAL_BDGHI:4 PAL_M:5 |
;             | PAL_N:6 PAL_NC:7 PAL_60:8 SECAM:9 480P:10        |
;             | 576P:11 720P_50HZ:12 720P_60HZ:13 1080I_50HZ:14  |
;             | 1080I_60HZ:15 1080P_50HZ:16 1080P_60HZ:17        |
;-----------------------------------------------------------------

[DISPLAY_INTERFACE]
ScreenId=0
ScreenType=2
Format=7
RgbMode=5
TvoutType=12
FrameRate=0
interlace=0
PadUnset=0

[LCD_TIMMING]
Width=800
Height=480
VBP=3
VFP=1
VSW=31
HBP=20
HFP=153
HSW=73
IHS=1
IVS=1
IOE=0

[LCD_CLK]
CLKSource=1
CLKFreq=330000000
CLKDIV1=11
CLKDIV2=1
CLKPolarity=0

[VP]
Hue=50
Saturation=50
Brightness=50
Contrast=50
