/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_FEEDBACKEVENT_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_FEEDBACKEVENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_inputsource_message_FeedbackEvent {
    aap_protobuf_service_inputsource_message_FeedbackEvent_FEEDBACK_SELECT = 1,
    aap_protobuf_service_inputsource_message_FeedbackEvent_FEEDBACK_FOCUS_CHANGE = 2,
    aap_protobuf_service_inputsource_message_FeedbackEvent_FEEDBACK_DRAG_SELECT = 3,
    aap_protobuf_service_inputsource_message_FeedbackEvent_FEEDBACK_DRAG_START = 4,
    aap_protobuf_service_inputsource_message_FeedbackEvent_FEEDBACK_DRAG_END = 5
} aap_protobuf_service_inputsource_message_FeedbackEvent;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN aap_protobuf_service_inputsource_message_FeedbackEvent_FEEDBACK_SELECT
#define _aap_protobuf_service_inputsource_message_FeedbackEvent_MAX aap_protobuf_service_inputsource_message_FeedbackEvent_FEEDBACK_DRAG_END
#define _aap_protobuf_service_inputsource_message_FeedbackEvent_ARRAYSIZE ((aap_protobuf_service_inputsource_message_FeedbackEvent)(aap_protobuf_service_inputsource_message_FeedbackEvent_FEEDBACK_DRAG_END+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
