/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_INPUTFEEDBACK_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_INPUTFEEDBACK_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/inputsource/message/FeedbackEvent.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_inputsource_message_InputFeedback {
    bool has_event;
    aap_protobuf_service_inputsource_message_FeedbackEvent event;
} aap_protobuf_service_inputsource_message_InputFeedback;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_inputsource_message_InputFeedback_init_default {false, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN}
#define aap_protobuf_service_inputsource_message_InputFeedback_init_zero {false, _aap_protobuf_service_inputsource_message_FeedbackEvent_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_inputsource_message_InputFeedback_event_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_inputsource_message_InputFeedback_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    event,             1)
#define aap_protobuf_service_inputsource_message_InputFeedback_CALLBACK NULL
#define aap_protobuf_service_inputsource_message_InputFeedback_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_inputsource_message_InputFeedback_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_inputsource_message_InputFeedback_fields &aap_protobuf_service_inputsource_message_InputFeedback_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_INPUTFEEDBACK_PB_H_MAX_SIZE aap_protobuf_service_inputsource_message_InputFeedback_size
#define aap_protobuf_service_inputsource_message_InputFeedback_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
