/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_INPUTREPORT_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_INPUTREPORT_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/inputsource/message/TouchEvent.pb.h"
#include "aap_protobuf/service/inputsource/message/AbsoluteEvent.pb.h"
#include "aap_protobuf/service/inputsource/message/RelativeEvent.pb.h"
#include "aap_protobuf/service/inputsource/message/KeyEvent.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_inputsource_message_InputReport {
    uint64_t timestamp;
    bool has_disp_channel_id;
    int32_t disp_channel_id;
    bool has_touch_event;
    aap_protobuf_service_inputsource_message_TouchEvent touch_event;
    bool has_key_event;
    aap_protobuf_service_inputsource_message_KeyEvent key_event;
    bool has_absolute_event;
    aap_protobuf_service_inputsource_message_AbsoluteEvent absolute_event;
    bool has_relative_event;
    aap_protobuf_service_inputsource_message_RelativeEvent relative_event;
    bool has_touchpad_event;
    aap_protobuf_service_inputsource_message_TouchEvent touchpad_event;
} aap_protobuf_service_inputsource_message_InputReport;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_inputsource_message_InputReport_init_default {0, false, 0, false, aap_protobuf_service_inputsource_message_TouchEvent_init_default, false, aap_protobuf_service_inputsource_message_KeyEvent_init_default, false, aap_protobuf_service_inputsource_message_AbsoluteEvent_init_default, false, aap_protobuf_service_inputsource_message_RelativeEvent_init_default, false, aap_protobuf_service_inputsource_message_TouchEvent_init_default}
#define aap_protobuf_service_inputsource_message_InputReport_init_zero {0, false, 0, false, aap_protobuf_service_inputsource_message_TouchEvent_init_zero, false, aap_protobuf_service_inputsource_message_KeyEvent_init_zero, false, aap_protobuf_service_inputsource_message_AbsoluteEvent_init_zero, false, aap_protobuf_service_inputsource_message_RelativeEvent_init_zero, false, aap_protobuf_service_inputsource_message_TouchEvent_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_inputsource_message_InputReport_timestamp_tag 1
#define aap_protobuf_service_inputsource_message_InputReport_disp_channel_id_tag 2
#define aap_protobuf_service_inputsource_message_InputReport_touch_event_tag 3
#define aap_protobuf_service_inputsource_message_InputReport_key_event_tag 4
#define aap_protobuf_service_inputsource_message_InputReport_absolute_event_tag 5
#define aap_protobuf_service_inputsource_message_InputReport_relative_event_tag 6
#define aap_protobuf_service_inputsource_message_InputReport_touchpad_event_tag 7

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_inputsource_message_InputReport_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   OPTIONAL, INT32,    disp_channel_id,   2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  touch_event,       3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  key_event,         4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  absolute_event,    5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  relative_event,    6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  touchpad_event,    7)
#define aap_protobuf_service_inputsource_message_InputReport_CALLBACK NULL
#define aap_protobuf_service_inputsource_message_InputReport_DEFAULT NULL
#define aap_protobuf_service_inputsource_message_InputReport_touch_event_MSGTYPE aap_protobuf_service_inputsource_message_TouchEvent
#define aap_protobuf_service_inputsource_message_InputReport_key_event_MSGTYPE aap_protobuf_service_inputsource_message_KeyEvent
#define aap_protobuf_service_inputsource_message_InputReport_absolute_event_MSGTYPE aap_protobuf_service_inputsource_message_AbsoluteEvent
#define aap_protobuf_service_inputsource_message_InputReport_relative_event_MSGTYPE aap_protobuf_service_inputsource_message_RelativeEvent
#define aap_protobuf_service_inputsource_message_InputReport_touchpad_event_MSGTYPE aap_protobuf_service_inputsource_message_TouchEvent

extern const pb_msgdesc_t aap_protobuf_service_inputsource_message_InputReport_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_inputsource_message_InputReport_fields &aap_protobuf_service_inputsource_message_InputReport_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_INPUTREPORT_PB_H_MAX_SIZE aap_protobuf_service_inputsource_message_InputReport_size
#define aap_protobuf_service_inputsource_message_InputReport_size 821

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
