/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "aap_protobuf/service/inputsource/message/KeyEvent.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aap_protobuf_service_inputsource_message_KeyEvent, aap_protobuf_service_inputsource_message_KeyEvent, AUTO)


PB_BIND(aap_protobuf_service_inputsource_message_KeyEvent_Key, aap_protobuf_service_inputsource_message_KeyEvent_Key, AUTO)



