/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_KEYEVENT_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_KEYEVENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_inputsource_message_KeyEvent_Key {
    uint32_t keycode;
    bool down;
    uint32_t metastate;
    bool has_longpress;
    bool longpress;
} aap_protobuf_service_inputsource_message_KeyEvent_Key;

typedef struct _aap_protobuf_service_inputsource_message_KeyEvent {
    pb_size_t keys_count;
    aap_protobuf_service_inputsource_message_KeyEvent_Key keys[8];
} aap_protobuf_service_inputsource_message_KeyEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_inputsource_message_KeyEvent_init_default {0, {aap_protobuf_service_inputsource_message_KeyEvent_Key_init_default, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_default, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_default, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_default, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_default, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_default, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_default, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_default}}
#define aap_protobuf_service_inputsource_message_KeyEvent_Key_init_default {0, 0, 0, false, 0}
#define aap_protobuf_service_inputsource_message_KeyEvent_init_zero {0, {aap_protobuf_service_inputsource_message_KeyEvent_Key_init_zero, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_zero, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_zero, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_zero, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_zero, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_zero, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_zero, aap_protobuf_service_inputsource_message_KeyEvent_Key_init_zero}}
#define aap_protobuf_service_inputsource_message_KeyEvent_Key_init_zero {0, 0, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_inputsource_message_KeyEvent_Key_keycode_tag 1
#define aap_protobuf_service_inputsource_message_KeyEvent_Key_down_tag 2
#define aap_protobuf_service_inputsource_message_KeyEvent_Key_metastate_tag 3
#define aap_protobuf_service_inputsource_message_KeyEvent_Key_longpress_tag 4
#define aap_protobuf_service_inputsource_message_KeyEvent_keys_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_inputsource_message_KeyEvent_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  keys,              1)
#define aap_protobuf_service_inputsource_message_KeyEvent_CALLBACK NULL
#define aap_protobuf_service_inputsource_message_KeyEvent_DEFAULT NULL
#define aap_protobuf_service_inputsource_message_KeyEvent_keys_MSGTYPE aap_protobuf_service_inputsource_message_KeyEvent_Key

#define aap_protobuf_service_inputsource_message_KeyEvent_Key_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   keycode,           1) \
X(a, STATIC,   REQUIRED, BOOL,     down,              2) \
X(a, STATIC,   REQUIRED, UINT32,   metastate,         3) \
X(a, STATIC,   OPTIONAL, BOOL,     longpress,         4)
#define aap_protobuf_service_inputsource_message_KeyEvent_Key_CALLBACK NULL
#define aap_protobuf_service_inputsource_message_KeyEvent_Key_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_inputsource_message_KeyEvent_msg;
extern const pb_msgdesc_t aap_protobuf_service_inputsource_message_KeyEvent_Key_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_inputsource_message_KeyEvent_fields &aap_protobuf_service_inputsource_message_KeyEvent_msg
#define aap_protobuf_service_inputsource_message_KeyEvent_Key_fields &aap_protobuf_service_inputsource_message_KeyEvent_Key_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_KEYEVENT_PB_H_MAX_SIZE aap_protobuf_service_inputsource_message_KeyEvent_size
#define aap_protobuf_service_inputsource_message_KeyEvent_Key_size 16
#define aap_protobuf_service_inputsource_message_KeyEvent_size 144

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
