/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_POINTERACTION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_POINTERACTION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_inputsource_message_PointerAction {
    aap_protobuf_service_inputsource_message_PointerAction_ACTION_DOWN = 0,
    aap_protobuf_service_inputsource_message_PointerAction_ACTION_UP = 1,
    aap_protobuf_service_inputsource_message_PointerAction_ACTION_MOVED = 2,
    aap_protobuf_service_inputsource_message_PointerAction_ACTION_POINTER_DOWN = 5,
    aap_protobuf_service_inputsource_message_PointerAction_ACTION_POINTER_UP = 6
} aap_protobuf_service_inputsource_message_PointerAction;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_inputsource_message_PointerAction_MIN aap_protobuf_service_inputsource_message_PointerAction_ACTION_DOWN
#define _aap_protobuf_service_inputsource_message_PointerAction_MAX aap_protobuf_service_inputsource_message_PointerAction_ACTION_POINTER_UP
#define _aap_protobuf_service_inputsource_message_PointerAction_ARRAYSIZE ((aap_protobuf_service_inputsource_message_PointerAction)(aap_protobuf_service_inputsource_message_PointerAction_ACTION_POINTER_UP+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
