/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_RELATIVEEVENT_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_RELATIVEEVENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_inputsource_message_RelativeEvent_Rel {
    uint32_t keycode;
    int32_t delta;
} aap_protobuf_service_inputsource_message_RelativeEvent_Rel;

typedef struct _aap_protobuf_service_inputsource_message_RelativeEvent {
    pb_size_t data_count;
    aap_protobuf_service_inputsource_message_RelativeEvent_Rel data[8];
} aap_protobuf_service_inputsource_message_RelativeEvent;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_inputsource_message_RelativeEvent_init_default {0, {aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_default, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_default, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_default, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_default, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_default, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_default, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_default, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_default}}
#define aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_default {0, 0}
#define aap_protobuf_service_inputsource_message_RelativeEvent_init_zero {0, {aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_zero, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_zero, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_zero, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_zero, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_zero, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_zero, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_zero, aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_zero}}
#define aap_protobuf_service_inputsource_message_RelativeEvent_Rel_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_inputsource_message_RelativeEvent_Rel_keycode_tag 1
#define aap_protobuf_service_inputsource_message_RelativeEvent_Rel_delta_tag 2
#define aap_protobuf_service_inputsource_message_RelativeEvent_data_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_inputsource_message_RelativeEvent_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  data,              1)
#define aap_protobuf_service_inputsource_message_RelativeEvent_CALLBACK NULL
#define aap_protobuf_service_inputsource_message_RelativeEvent_DEFAULT NULL
#define aap_protobuf_service_inputsource_message_RelativeEvent_data_MSGTYPE aap_protobuf_service_inputsource_message_RelativeEvent_Rel

#define aap_protobuf_service_inputsource_message_RelativeEvent_Rel_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   keycode,           1) \
X(a, STATIC,   REQUIRED, INT32,    delta,             2)
#define aap_protobuf_service_inputsource_message_RelativeEvent_Rel_CALLBACK NULL
#define aap_protobuf_service_inputsource_message_RelativeEvent_Rel_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_inputsource_message_RelativeEvent_msg;
extern const pb_msgdesc_t aap_protobuf_service_inputsource_message_RelativeEvent_Rel_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_inputsource_message_RelativeEvent_fields &aap_protobuf_service_inputsource_message_RelativeEvent_msg
#define aap_protobuf_service_inputsource_message_RelativeEvent_Rel_fields &aap_protobuf_service_inputsource_message_RelativeEvent_Rel_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_AAP_PROTOBUF_SERVICE_INPUTSOURCE_MESSAGE_RELATIVEEVENT_PB_H_MAX_SIZE aap_protobuf_service_inputsource_message_RelativeEvent_size
#define aap_protobuf_service_inputsource_message_RelativeEvent_Rel_size 17
#define aap_protobuf_service_inputsource_message_RelativeEvent_size 152

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
