/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIAPLAYBACK_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIAPLAYBACK_MESSAGE_MEDIAPLAYBACKMETADATA_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIAPLAYBACK_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIAPLAYBACK_MESSAGE_MEDIAPLAYBACKMETADATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_album_art_t;
typedef struct _aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata {
    bool has_song;
    char song[64];
    bool has_artist;
    char artist[64];
    bool has_album;
    char album[64];
    bool has_album_art;
    aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_album_art_t album_art;
    bool has_playlist;
    char playlist[64];
    bool has_duration_seconds;
    uint32_t duration_seconds;
    bool has_rating;
    int32_t rating;
} aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_init_default {false, "", false, "", false, "", false, {0, {0}}, false, "", false, 0, false, 0}
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_init_zero {false, "", false, "", false, "", false, {0, {0}}, false, "", false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_song_tag 1
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_artist_tag 2
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_album_tag 3
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_album_art_tag 4
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_playlist_tag 5
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_duration_seconds_tag 6
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_rating_tag 7

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   song,              1) \
X(a, STATIC,   OPTIONAL, STRING,   artist,            2) \
X(a, STATIC,   OPTIONAL, STRING,   album,             3) \
X(a, STATIC,   OPTIONAL, BYTES,    album_art,         4) \
X(a, STATIC,   OPTIONAL, STRING,   playlist,          5) \
X(a, STATIC,   OPTIONAL, UINT32,   duration_seconds,   6) \
X(a, STATIC,   OPTIONAL, INT32,    rating,            7)
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_CALLBACK NULL
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_fields &aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIAPLAYBACK_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIAPLAYBACK_MESSAGE_MEDIAPLAYBACKMETADATA_PB_H_MAX_SIZE aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_size
#define aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata_size 343

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
