/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "aap_protobuf/service/mediaplayback/message/MediaPlaybackMetadata.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata, aap_protobuf_service_mediaplayback_message_MediaPlaybackMetadata, 2)



