/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_WIFIPROJECTIONMESSAGEID_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_AAP_PROTOBUF_SERVICE_WIFIPROJECTION_WIFIPROJECTIONMESSAGEID_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_wifiprojection_WifiProjectionMessageId {
    aap_protobuf_service_wifiprojection_WifiProjectionMessageId_WIFI_MESSAGE_CREDENTIALS_REQUEST = 32769,
    aap_protobuf_service_wifiprojection_WifiProjectionMessageId_WIFI_MESSAGE_CREDENTIALS_RESPONSE = 32770
} aap_protobuf_service_wifiprojection_WifiProjectionMessageId;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_wifiprojection_WifiProjectionMessageId_MIN aap_protobuf_service_wifiprojection_WifiProjectionMessageId_WIFI_MESSAGE_CREDENTIALS_REQUEST
#define _aap_protobuf_service_wifiprojection_WifiProjectionMessageId_MAX aap_protobuf_service_wifiprojection_WifiProjectionMessageId_WIFI_MESSAGE_CREDENTIALS_RESPONSE
#define _aap_protobuf_service_wifiprojection_WifiProjectionMessageId_ARRAYSIZE ((aap_protobuf_service_wifiprojection_WifiProjectionMessageId)(aap_protobuf_service_wifiprojection_WifiProjectionMessageId_WIFI_MESSAGE_CREDENTIALS_RESPONSE+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
