/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_PHONESTATUS_AAP_PROTOBUF_SERVICE_PHONESTATUS_PHONESTATUSMESSAGEID_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_PHONESTATUS_AAP_PROTOBUF_SERVICE_PHONESTATUS_PHONESTATUSMESSAGEID_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_phonestatus_PhoneStatusMessageId {
    aap_protobuf_service_phonestatus_PhoneStatusMessageId_PHONE_STATUS = 32769,
    aap_protobuf_service_phonestatus_PhoneStatusMessageId_PHONE_STATUS_INPUT = 32770
} aap_protobuf_service_phonestatus_PhoneStatusMessageId;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_phonestatus_PhoneStatusMessageId_MIN aap_protobuf_service_phonestatus_PhoneStatusMessageId_PHONE_STATUS
#define _aap_protobuf_service_phonestatus_PhoneStatusMessageId_MAX aap_protobuf_service_phonestatus_PhoneStatusMessageId_PHONE_STATUS_INPUT
#define _aap_protobuf_service_phonestatus_PhoneStatusMessageId_ARRAYSIZE ((aap_protobuf_service_phonestatus_PhoneStatusMessageId)(aap_protobuf_service_phonestatus_PhoneStatusMessageId_PHONE_STATUS_INPUT+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
