/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_BLUETOOTH_MESSAGE_AAP_PROTOBUF_SERVICE_BLUETOOTH_MESSAGE_BLUETOOTHPAIRINGREQUEST_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_BLUETOOTH_MESSAGE_AAP_PROTOBUF_SERVICE_BLUETOOTH_MESSAGE_BLUETOOTHPAIRINGREQUEST_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/bluetooth/message/BluetoothPairingMethod.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_bluetooth_message_BluetoothPairingRequest {
    char phone_address[64];
    aap_protobuf_service_bluetooth_message_BluetoothPairingMethod pairing_method;
} aap_protobuf_service_bluetooth_message_BluetoothPairingRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_bluetooth_message_BluetoothPairingRequest_init_default {"", _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN}
#define aap_protobuf_service_bluetooth_message_BluetoothPairingRequest_init_zero {"", _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_bluetooth_message_BluetoothPairingRequest_phone_address_tag 1
#define aap_protobuf_service_bluetooth_message_BluetoothPairingRequest_pairing_method_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_bluetooth_message_BluetoothPairingRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   phone_address,     1) \
X(a, STATIC,   REQUIRED, ENUM,     pairing_method,    2)
#define aap_protobuf_service_bluetooth_message_BluetoothPairingRequest_CALLBACK NULL
#define aap_protobuf_service_bluetooth_message_BluetoothPairingRequest_DEFAULT (const pb_byte_t*)"\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_bluetooth_message_BluetoothPairingRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_bluetooth_message_BluetoothPairingRequest_fields &aap_protobuf_service_bluetooth_message_BluetoothPairingRequest_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_BLUETOOTH_MESSAGE_AAP_PROTOBUF_SERVICE_BLUETOOTH_MESSAGE_BLUETOOTHPAIRINGREQUEST_PB_H_MAX_SIZE aap_protobuf_service_bluetooth_message_BluetoothPairingRequest_size
#define aap_protobuf_service_bluetooth_message_BluetoothPairingRequest_size 76

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
