/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_BLUETOOTH_MESSAGE_AAP_PROTOBUF_SERVICE_BLUETOOTH_MESSAGE_BLUETOOTHPAIRINGMETHOD_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_BLUETOOTH_MESSAGE_AAP_PROTOBUF_SERVICE_BLUETOOTH_MESSAGE_BLUETOOTHPAIRINGMETHOD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod {
    aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_BLUETOOTH_PAIRING_UNAVAILABLE = -1,
    aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_BLUETOOTH_PAIRING_OOB = 1,
    aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_BLUETOOTH_PAIRING_NUMERIC_COMPARISON = 2,
    aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_BLUETOOTH_PAIRING_PASSKEY_ENTRY = 3,
    aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_BLUETOOTH_PAIRING_PIN = 4
} aap_protobuf_service_bluetooth_message_BluetoothPairingMethod;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_BLUETOOTH_PAIRING_UNAVAILABLE
#define _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MAX aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_BLUETOOTH_PAIRING_PIN
#define _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_ARRAYSIZE ((aap_protobuf_service_bluetooth_message_BluetoothPairingMethod)(aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_BLUETOOTH_PAIRING_PIN+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
