/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALCONSTANTS_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALCONSTANTS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_control_message_GalConstants {
    aap_protobuf_service_control_message_GalConstants_WIFI_PORT = 30515,
    aap_protobuf_service_control_message_GalConstants_PROTOCOL_MAJOR_VERSION = 1,
    aap_protobuf_service_control_message_GalConstants_PROTOCOL_MINOR_VERSION = 6
} aap_protobuf_service_control_message_GalConstants;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_control_message_GalConstants_MIN aap_protobuf_service_control_message_GalConstants_PROTOCOL_MAJOR_VERSION
#define _aap_protobuf_service_control_message_GalConstants_MAX aap_protobuf_service_control_message_GalConstants_WIFI_PORT
#define _aap_protobuf_service_control_message_GalConstants_ARRAYSIZE ((aap_protobuf_service_control_message_GalConstants)(aap_protobuf_service_control_message_GalConstants_WIFI_PORT+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
