/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONSCREENCAPTURERESPONSE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONSCREENCAPTURERESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse_screen_capture_t;
typedef struct _aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse {
    aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse_screen_capture_t screen_capture;
} aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse_init_default {{0, {0}}}
#define aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse_init_zero {{0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse_screen_capture_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BYTES,    screen_capture,    1)
#define aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse_CALLBACK NULL
#define aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse_fields &aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONSCREENCAPTURERESPONSE_PB_H_MAX_SIZE aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse_size
#define aap_protobuf_service_control_message_GalVerificationScreenCaptureResponse_size 66

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
