/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONVIDEOFOCUS_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONVIDEOFOCUS_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/media/video/message/VideoFocusMode.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_GalVerificationVideoFocus {
    aap_protobuf_service_media_video_message_VideoFocusMode video_focus_mode;
    bool has_deny;
    bool deny;
    bool has_unsolicited;
    bool unsolicited;
} aap_protobuf_service_control_message_GalVerificationVideoFocus;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_GalVerificationVideoFocus_init_default {_aap_protobuf_service_media_video_message_VideoFocusMode_MIN, false, 0, false, 0}
#define aap_protobuf_service_control_message_GalVerificationVideoFocus_init_zero {_aap_protobuf_service_media_video_message_VideoFocusMode_MIN, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_GalVerificationVideoFocus_video_focus_mode_tag 1
#define aap_protobuf_service_control_message_GalVerificationVideoFocus_deny_tag 2
#define aap_protobuf_service_control_message_GalVerificationVideoFocus_unsolicited_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_GalVerificationVideoFocus_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    video_focus_mode,   1) \
X(a, STATIC,   OPTIONAL, BOOL,     deny,              2) \
X(a, STATIC,   OPTIONAL, BOOL,     unsolicited,       3)
#define aap_protobuf_service_control_message_GalVerificationVideoFocus_CALLBACK NULL
#define aap_protobuf_service_control_message_GalVerificationVideoFocus_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_control_message_GalVerificationVideoFocus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_GalVerificationVideoFocus_fields &aap_protobuf_service_control_message_GalVerificationVideoFocus_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONVIDEOFOCUS_PB_H_MAX_SIZE aap_protobuf_service_control_message_GalVerificationVideoFocus_size
#define aap_protobuf_service_control_message_GalVerificationVideoFocus_size 6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
