/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONDISPLAYINFORMATIONRESPONSE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONDISPLAYINFORMATIONRESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse {
    int32_t native_width;
    int32_t native_height;
} aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse_init_default {0, 0}
#define aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse_native_width_tag 1
#define aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse_native_height_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    native_width,      1) \
X(a, STATIC,   REQUIRED, INT32,    native_height,     2)
#define aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse_CALLBACK NULL
#define aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse_fields &aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONDISPLAYINFORMATIONRESPONSE_PB_H_MAX_SIZE aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse_size
#define aap_protobuf_service_control_message_GalVerificationDisplayInformationResponse_size 22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
