/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONINJECTINPUT_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONINJECTINPUT_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/inputsource/message/InputReport.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_GalVerificationInjectInput {
    aap_protobuf_service_inputsource_message_InputReport input;
} aap_protobuf_service_control_message_GalVerificationInjectInput;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_GalVerificationInjectInput_init_default {aap_protobuf_service_inputsource_message_InputReport_init_default}
#define aap_protobuf_service_control_message_GalVerificationInjectInput_init_zero {aap_protobuf_service_inputsource_message_InputReport_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_GalVerificationInjectInput_input_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_GalVerificationInjectInput_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  input,             1)
#define aap_protobuf_service_control_message_GalVerificationInjectInput_CALLBACK NULL
#define aap_protobuf_service_control_message_GalVerificationInjectInput_DEFAULT NULL
#define aap_protobuf_service_control_message_GalVerificationInjectInput_input_MSGTYPE aap_protobuf_service_inputsource_message_InputReport

extern const pb_msgdesc_t aap_protobuf_service_control_message_GalVerificationInjectInput_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_GalVerificationInjectInput_fields &aap_protobuf_service_control_message_GalVerificationInjectInput_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONINJECTINPUT_PB_H_MAX_SIZE aap_protobuf_service_control_message_GalVerificationInjectInput_size
#define aap_protobuf_service_control_message_GalVerificationInjectInput_size 824

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
