/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONBUGREPORTRESPONSE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONBUGREPORTRESPONSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_GalVerificationBugReportResponse {
    char bug_report[64];
} aap_protobuf_service_control_message_GalVerificationBugReportResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_GalVerificationBugReportResponse_init_default {""}
#define aap_protobuf_service_control_message_GalVerificationBugReportResponse_init_zero {""}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_GalVerificationBugReportResponse_bug_report_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_GalVerificationBugReportResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   bug_report,        1)
#define aap_protobuf_service_control_message_GalVerificationBugReportResponse_CALLBACK NULL
#define aap_protobuf_service_control_message_GalVerificationBugReportResponse_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_control_message_GalVerificationBugReportResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_GalVerificationBugReportResponse_fields &aap_protobuf_service_control_message_GalVerificationBugReportResponse_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONBUGREPORTRESPONSE_PB_H_MAX_SIZE aap_protobuf_service_control_message_GalVerificationBugReportResponse_size
#define aap_protobuf_service_control_message_GalVerificationBugReportResponse_size 65

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
