/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "aap_protobuf/channel/control/GalVerificationSetSensor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aap_protobuf_service_control_message_GalVerificationSetSensor, aap_protobuf_service_control_message_GalVerificationSetSensor, 4)



