/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONAUDIOFOCUS_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONAUDIOFOCUS_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/control/message/AudioFocusStateType.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_control_message_GalVerificationAudioFocus {
    aap_protobuf_service_control_message_AudioFocusStateType audio_focus_state;
    int32_t channel;
    bool has_unsolicited;
    bool unsolicited;
} aap_protobuf_service_control_message_GalVerificationAudioFocus;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_control_message_GalVerificationAudioFocus_init_default {_aap_protobuf_service_control_message_AudioFocusStateType_MIN, 0, false, 0}
#define aap_protobuf_service_control_message_GalVerificationAudioFocus_init_zero {_aap_protobuf_service_control_message_AudioFocusStateType_MIN, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_control_message_GalVerificationAudioFocus_audio_focus_state_tag 1
#define aap_protobuf_service_control_message_GalVerificationAudioFocus_channel_tag 2
#define aap_protobuf_service_control_message_GalVerificationAudioFocus_unsolicited_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_control_message_GalVerificationAudioFocus_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    audio_focus_state,   1) \
X(a, STATIC,   REQUIRED, INT32,    channel,           2) \
X(a, STATIC,   OPTIONAL, BOOL,     unsolicited,       3)
#define aap_protobuf_service_control_message_GalVerificationAudioFocus_CALLBACK NULL
#define aap_protobuf_service_control_message_GalVerificationAudioFocus_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_control_message_GalVerificationAudioFocus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_control_message_GalVerificationAudioFocus_fields &aap_protobuf_service_control_message_GalVerificationAudioFocus_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_CONTROL_MESSAGE_AAP_PROTOBUF_CHANNEL_CONTROL_GALVERIFICATIONAUDIOFOCUS_PB_H_MAX_SIZE aap_protobuf_service_control_message_GalVerificationAudioFocus_size
#define aap_protobuf_service_control_message_GalVerificationAudioFocus_size 15

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
