/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_CHANNEL_CONTROL_GOOGLEDIAGNOSTICSVENDOREXTENSIONMESSAGEID_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_CHANNEL_CONTROL_GOOGLEDIAGNOSTICSVENDOREXTENSIONMESSAGEID_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _GoogleDiagnosticsVendorExtensionMessageId {
    GoogleDiagnosticsVendorExtensionMessageId_DIAGNOSTICS_BUG_REPORT_REQUEST = 1,
    GoogleDiagnosticsVendorExtensionMessageId_DIAGNOSTICS_BUG_REPORT_RESPONSE = 2
} GoogleDiagnosticsVendorExtensionMessageId;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _GoogleDiagnosticsVendorExtensionMessageId_MIN GoogleDiagnosticsVendorExtensionMessageId_DIAGNOSTICS_BUG_REPORT_REQUEST
#define _GoogleDiagnosticsVendorExtensionMessageId_MAX GoogleDiagnosticsVendorExtensionMessageId_DIAGNOSTICS_BUG_REPORT_RESPONSE
#define _GoogleDiagnosticsVendorExtensionMessageId_ARRAYSIZE ((GoogleDiagnosticsVendorExtensionMessageId)(GoogleDiagnosticsVendorExtensionMessageId_DIAGNOSTICS_BUG_REPORT_RESPONSE+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
