/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SHARED_AAP_PROTOBUF_CHANNEL_CONTROL_LOCATIONCHARACTERIZATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SHARED_AAP_PROTOBUF_CHANNEL_CONTROL_LOCATIONCHARACTERIZATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_shared_LocationCharacterization {
    aap_protobuf_shared_LocationCharacterization_PRIOR_LOCATIONS = 1,
    aap_protobuf_shared_LocationCharacterization_GYROSCOPE_FUSION = 2,
    aap_protobuf_shared_LocationCharacterization_ACCELEROMETER_FUSION = 4,
    aap_protobuf_shared_LocationCharacterization_COMPASS_FUSION = 8,
    aap_protobuf_shared_LocationCharacterization_WHEEL_SPEED_FUSION = 16,
    aap_protobuf_shared_LocationCharacterization_STEERING_ANGLE_FUSION = 32,
    aap_protobuf_shared_LocationCharacterization_CAR_SPEED_FUSION = 64,
    aap_protobuf_shared_LocationCharacterization_DEAD_RECKONED = 128,
    aap_protobuf_shared_LocationCharacterization_RAW_GPS_ONLY = 256
} aap_protobuf_shared_LocationCharacterization;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_shared_LocationCharacterization_MIN aap_protobuf_shared_LocationCharacterization_PRIOR_LOCATIONS
#define _aap_protobuf_shared_LocationCharacterization_MAX aap_protobuf_shared_LocationCharacterization_RAW_GPS_ONLY
#define _aap_protobuf_shared_LocationCharacterization_ARRAYSIZE ((aap_protobuf_shared_LocationCharacterization)(aap_protobuf_shared_LocationCharacterization_RAW_GPS_ONLY+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
