/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SHARED_AAP_PROTOBUF_CHANNEL_CONTROL_SESSIONCONFIGURATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SHARED_AAP_PROTOBUF_CHANNEL_CONTROL_SESSIONCONFIGURATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_shared_SessionConfiguration {
    aap_protobuf_shared_SessionConfiguration_UI_CONFIG_HIDE_CLOCK = 1,
    aap_protobuf_shared_SessionConfiguration_UI_CONFIG_HIDE_PHONE_SIGNAL = 2,
    aap_protobuf_shared_SessionConfiguration_UI_CONFIG_HIDE_BATTERY_LEVEL = 4,
    aap_protobuf_shared_SessionConfiguration_CAN_PLAY_NATIVE_MEDIA_DURING_VR = 8
} aap_protobuf_shared_SessionConfiguration;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_shared_SessionConfiguration_MIN aap_protobuf_shared_SessionConfiguration_UI_CONFIG_HIDE_CLOCK
#define _aap_protobuf_shared_SessionConfiguration_MAX aap_protobuf_shared_SessionConfiguration_CAN_PLAY_NATIVE_MEDIA_DURING_VR
#define _aap_protobuf_shared_SessionConfiguration_ARRAYSIZE ((aap_protobuf_shared_SessionConfiguration)(aap_protobuf_shared_SessionConfiguration_CAN_PLAY_NATIVE_MEDIA_DURING_VR+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
