/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_VENDOREXTENSION_AAP_PROTOBUF_SERVICE_VENDOREXTENSION_VENDOREXTENSIONSERVICE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_VENDOREXTENSION_AAP_PROTOBUF_SERVICE_VENDOREXTENSION_VENDOREXTENSIONSERVICE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_vendorextension_VendorExtensionService_data_t;
typedef struct _aap_protobuf_service_vendorextension_VendorExtensionService {
    char name[64];
    pb_size_t package_white_list_count;
    char package_white_list[8][64];
    bool has_data;
    aap_protobuf_service_vendorextension_VendorExtensionService_data_t data;
} aap_protobuf_service_vendorextension_VendorExtensionService;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_vendorextension_VendorExtensionService_init_default {"", 0, {"", "", "", "", "", "", "", ""}, false, {0, {0}}}
#define aap_protobuf_service_vendorextension_VendorExtensionService_init_zero {"", 0, {"", "", "", "", "", "", "", ""}, false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_vendorextension_VendorExtensionService_name_tag 1
#define aap_protobuf_service_vendorextension_VendorExtensionService_package_white_list_tag 2
#define aap_protobuf_service_vendorextension_VendorExtensionService_data_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_vendorextension_VendorExtensionService_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   name,              1) \
X(a, STATIC,   REPEATED, STRING,   package_white_list,   2) \
X(a, STATIC,   OPTIONAL, BYTES,    data,              3)
#define aap_protobuf_service_vendorextension_VendorExtensionService_CALLBACK NULL
#define aap_protobuf_service_vendorextension_VendorExtensionService_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_vendorextension_VendorExtensionService_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_vendorextension_VendorExtensionService_fields &aap_protobuf_service_vendorextension_VendorExtensionService_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_VENDOREXTENSION_AAP_PROTOBUF_SERVICE_VENDOREXTENSION_VENDOREXTENSIONSERVICE_PB_H_MAX_SIZE aap_protobuf_service_vendorextension_VendorExtensionService_size
#define aap_protobuf_service_vendorextension_VendorExtensionService_size 651

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
