/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AUDIOCONFIGURATION_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AUDIOCONFIGURATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_media_shared_message_AudioConfiguration {
    uint32_t sampling_rate;
    uint32_t number_of_bits;
    uint32_t number_of_channels;
} aap_protobuf_service_media_shared_message_AudioConfiguration;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_media_shared_message_AudioConfiguration_init_default {0, 0, 0}
#define aap_protobuf_service_media_shared_message_AudioConfiguration_init_zero {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_media_shared_message_AudioConfiguration_sampling_rate_tag 1
#define aap_protobuf_service_media_shared_message_AudioConfiguration_number_of_bits_tag 2
#define aap_protobuf_service_media_shared_message_AudioConfiguration_number_of_channels_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_media_shared_message_AudioConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   sampling_rate,     1) \
X(a, STATIC,   REQUIRED, UINT32,   number_of_bits,    2) \
X(a, STATIC,   REQUIRED, UINT32,   number_of_channels,   3)
#define aap_protobuf_service_media_shared_message_AudioConfiguration_CALLBACK NULL
#define aap_protobuf_service_media_shared_message_AudioConfiguration_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_media_shared_message_AudioConfiguration_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_media_shared_message_AudioConfiguration_fields &aap_protobuf_service_media_shared_message_AudioConfiguration_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AUDIOCONFIGURATION_PB_H_MAX_SIZE aap_protobuf_service_media_shared_message_AudioConfiguration_size
#define aap_protobuf_service_media_shared_message_AudioConfiguration_size 18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
