/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_CONFIG_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_CONFIG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_media_shared_message_Config_Status {
    aap_protobuf_service_media_shared_message_Config_Status_STATUS_WAIT = 1,
    aap_protobuf_service_media_shared_message_Config_Status_STATUS_READY = 2
} aap_protobuf_service_media_shared_message_Config_Status;

/* Struct definitions */
typedef struct _aap_protobuf_service_media_shared_message_Config {
    aap_protobuf_service_media_shared_message_Config_Status status;
    bool has_max_unacked;
    uint32_t max_unacked;
    pb_size_t configuration_indices_count;
    uint32_t configuration_indices[8];
} aap_protobuf_service_media_shared_message_Config;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_media_shared_message_Config_Status_MIN aap_protobuf_service_media_shared_message_Config_Status_STATUS_WAIT
#define _aap_protobuf_service_media_shared_message_Config_Status_MAX aap_protobuf_service_media_shared_message_Config_Status_STATUS_READY
#define _aap_protobuf_service_media_shared_message_Config_Status_ARRAYSIZE ((aap_protobuf_service_media_shared_message_Config_Status)(aap_protobuf_service_media_shared_message_Config_Status_STATUS_READY+1))

#define aap_protobuf_service_media_shared_message_Config_status_ENUMTYPE aap_protobuf_service_media_shared_message_Config_Status


/* Initializer values for message structs */
#define aap_protobuf_service_media_shared_message_Config_init_default {_aap_protobuf_service_media_shared_message_Config_Status_MIN, false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define aap_protobuf_service_media_shared_message_Config_init_zero {_aap_protobuf_service_media_shared_message_Config_Status_MIN, false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_media_shared_message_Config_status_tag 1
#define aap_protobuf_service_media_shared_message_Config_max_unacked_tag 2
#define aap_protobuf_service_media_shared_message_Config_configuration_indices_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_media_shared_message_Config_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    status,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   max_unacked,       2) \
X(a, STATIC,   REPEATED, UINT32,   configuration_indices,   3)
#define aap_protobuf_service_media_shared_message_Config_CALLBACK NULL
#define aap_protobuf_service_media_shared_message_Config_DEFAULT (const pb_byte_t*)"\x08\x01\x00"

extern const pb_msgdesc_t aap_protobuf_service_media_shared_message_Config_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_media_shared_message_Config_fields &aap_protobuf_service_media_shared_message_Config_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_CONFIG_PB_H_MAX_SIZE aap_protobuf_service_media_shared_message_Config_size
#define aap_protobuf_service_media_shared_message_Config_size 56

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
