/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_START_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_START_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_media_shared_message_Start {
    int32_t session_id;
    uint32_t configuration_index;
} aap_protobuf_service_media_shared_message_Start;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_media_shared_message_Start_init_default {0, 0}
#define aap_protobuf_service_media_shared_message_Start_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_media_shared_message_Start_session_id_tag 1
#define aap_protobuf_service_media_shared_message_Start_configuration_index_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_media_shared_message_Start_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    session_id,        1) \
X(a, STATIC,   REQUIRED, UINT32,   configuration_index,   2)
#define aap_protobuf_service_media_shared_message_Start_CALLBACK NULL
#define aap_protobuf_service_media_shared_message_Start_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_media_shared_message_Start_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_media_shared_message_Start_fields &aap_protobuf_service_media_shared_message_Start_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_START_PB_H_MAX_SIZE aap_protobuf_service_media_shared_message_Start_size
#define aap_protobuf_service_media_shared_message_Start_size 17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
