/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_UICONFIG_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_UICONFIG_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/media/shared/message/UiTheme.pb.h"
#include "aap_protobuf/service/media/shared/message/Insets.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_media_shared_message_UiConfig {
    bool has_margins;
    aap_protobuf_service_media_shared_message_Insets margins;
    bool has_content_insets;
    aap_protobuf_service_media_shared_message_Insets content_insets;
    bool has_stable_content_insets;
    aap_protobuf_service_media_shared_message_Insets stable_content_insets;
    bool has_ui_theme;
    aap_protobuf_service_media_shared_message_UiTheme ui_theme;
} aap_protobuf_service_media_shared_message_UiConfig;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_media_shared_message_UiConfig_init_default {false, aap_protobuf_service_media_shared_message_Insets_init_default, false, aap_protobuf_service_media_shared_message_Insets_init_default, false, aap_protobuf_service_media_shared_message_Insets_init_default, false, _aap_protobuf_service_media_shared_message_UiTheme_MIN}
#define aap_protobuf_service_media_shared_message_UiConfig_init_zero {false, aap_protobuf_service_media_shared_message_Insets_init_zero, false, aap_protobuf_service_media_shared_message_Insets_init_zero, false, aap_protobuf_service_media_shared_message_Insets_init_zero, false, _aap_protobuf_service_media_shared_message_UiTheme_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_media_shared_message_UiConfig_margins_tag 1
#define aap_protobuf_service_media_shared_message_UiConfig_content_insets_tag 2
#define aap_protobuf_service_media_shared_message_UiConfig_stable_content_insets_tag 3
#define aap_protobuf_service_media_shared_message_UiConfig_ui_theme_tag 4

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_media_shared_message_UiConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  margins,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  content_insets,    2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stable_content_insets,   3) \
X(a, STATIC,   OPTIONAL, UENUM,    ui_theme,          4)
#define aap_protobuf_service_media_shared_message_UiConfig_CALLBACK NULL
#define aap_protobuf_service_media_shared_message_UiConfig_DEFAULT NULL
#define aap_protobuf_service_media_shared_message_UiConfig_margins_MSGTYPE aap_protobuf_service_media_shared_message_Insets
#define aap_protobuf_service_media_shared_message_UiConfig_content_insets_MSGTYPE aap_protobuf_service_media_shared_message_Insets
#define aap_protobuf_service_media_shared_message_UiConfig_stable_content_insets_MSGTYPE aap_protobuf_service_media_shared_message_Insets

extern const pb_msgdesc_t aap_protobuf_service_media_shared_message_UiConfig_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_media_shared_message_UiConfig_fields &aap_protobuf_service_media_shared_message_UiConfig_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_UICONFIG_PB_H_MAX_SIZE aap_protobuf_service_media_shared_message_UiConfig_size
#define aap_protobuf_service_media_shared_message_UiConfig_size 80

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
