/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_UITHEME_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_AAP_PROTOBUF_SERVICE_MEDIA_SHARED_MESSAGE_UITHEME_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_media_shared_message_UiTheme {
    aap_protobuf_service_media_shared_message_UiTheme_UI_THEME_AUTOMATIC = 0,
    aap_protobuf_service_media_shared_message_UiTheme_UI_THEME_LIGHT = 1,
    aap_protobuf_service_media_shared_message_UiTheme_UI_THEME_DARK = 2
} aap_protobuf_service_media_shared_message_UiTheme;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_media_shared_message_UiTheme_MIN aap_protobuf_service_media_shared_message_UiTheme_UI_THEME_AUTOMATIC
#define _aap_protobuf_service_media_shared_message_UiTheme_MAX aap_protobuf_service_media_shared_message_UiTheme_UI_THEME_DARK
#define _aap_protobuf_service_media_shared_message_UiTheme_ARRAYSIZE ((aap_protobuf_service_media_shared_message_UiTheme)(aap_protobuf_service_media_shared_message_UiTheme_UI_THEME_DARK+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
