/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_BLUETOOTH_AAP_PROTOBUF_SERVICE_BLUETOOTH_BLUETOOTHMESSAGEID_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_BLUETOOTH_AAP_PROTOBUF_SERVICE_BLUETOOTH_BLUETOOTHMESSAGEID_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_bluetooth_BluetoothMessageId {
    aap_protobuf_service_bluetooth_BluetoothMessageId_BLUETOOTH_MESSAGE_PAIRING_REQUEST = 32769,
    aap_protobuf_service_bluetooth_BluetoothMessageId_BLUETOOTH_MESSAGE_PAIRING_RESPONSE = 32770,
    aap_protobuf_service_bluetooth_BluetoothMessageId_BLUETOOTH_MESSAGE_AUTHENTICATION_DATA = 32771,
    aap_protobuf_service_bluetooth_BluetoothMessageId_BLUETOOTH_MESSAGE_AUTHENTICATION_RESULT = 32772
} aap_protobuf_service_bluetooth_BluetoothMessageId;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_bluetooth_BluetoothMessageId_MIN aap_protobuf_service_bluetooth_BluetoothMessageId_BLUETOOTH_MESSAGE_PAIRING_REQUEST
#define _aap_protobuf_service_bluetooth_BluetoothMessageId_MAX aap_protobuf_service_bluetooth_BluetoothMessageId_BLUETOOTH_MESSAGE_AUTHENTICATION_RESULT
#define _aap_protobuf_service_bluetooth_BluetoothMessageId_ARRAYSIZE ((aap_protobuf_service_bluetooth_BluetoothMessageId)(aap_protobuf_service_bluetooth_BluetoothMessageId_BLUETOOTH_MESSAGE_AUTHENTICATION_RESULT+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
