/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_BLUETOOTH_AAP_PROTOBUF_SERVICE_BLUETOOTH_BLUETOOTHSERVICE_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_BLUETOOTH_AAP_PROTOBUF_SERVICE_BLUETOOTH_BLUETOOTHSERVICE_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/service/bluetooth/message/BluetoothPairingMethod.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_bluetooth_BluetoothService {
    char car_address[64];
    pb_size_t supported_pairing_methods_count;
    aap_protobuf_service_bluetooth_message_BluetoothPairingMethod supported_pairing_methods[8];
} aap_protobuf_service_bluetooth_BluetoothService;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_bluetooth_BluetoothService_init_default {"", 0, {_aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN}}
#define aap_protobuf_service_bluetooth_BluetoothService_init_zero {"", 0, {_aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN, _aap_protobuf_service_bluetooth_message_BluetoothPairingMethod_MIN}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_bluetooth_BluetoothService_car_address_tag 1
#define aap_protobuf_service_bluetooth_BluetoothService_supported_pairing_methods_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_bluetooth_BluetoothService_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   car_address,       1) \
X(a, STATIC,   REPEATED, ENUM,     supported_pairing_methods,   2)
#define aap_protobuf_service_bluetooth_BluetoothService_CALLBACK NULL
#define aap_protobuf_service_bluetooth_BluetoothService_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_bluetooth_BluetoothService_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_bluetooth_BluetoothService_fields &aap_protobuf_service_bluetooth_BluetoothService_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_BLUETOOTH_AAP_PROTOBUF_SERVICE_BLUETOOTH_BLUETOOTHSERVICE_PB_H_MAX_SIZE aap_protobuf_service_bluetooth_BluetoothService_size
#define aap_protobuf_service_bluetooth_BluetoothService_size 153

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
