/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "aap_protobuf/service/phonestatus/message/PhoneStatus.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aap_protobuf_service_phonestatus_message_PhoneStatus, aap_protobuf_service_phonestatus_message_PhoneStatus, 2)


PB_BIND(aap_protobuf_service_phonestatus_message_PhoneStatus_Call, aap_protobuf_service_phonestatus_message_PhoneStatus_Call, 2)





