/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_PHONESTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_PHONESTATUS_MESSAGE_PHONESTATUS_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_PHONESTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_PHONESTATUS_MESSAGE_PHONESTATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_phonestatus_message_PhoneStatus_State {
    aap_protobuf_service_phonestatus_message_PhoneStatus_State_UNKNOWN = 0,
    aap_protobuf_service_phonestatus_message_PhoneStatus_State_IN_CALL = 1,
    aap_protobuf_service_phonestatus_message_PhoneStatus_State_ON_HOLD = 2,
    aap_protobuf_service_phonestatus_message_PhoneStatus_State_INACTIVE = 3,
    aap_protobuf_service_phonestatus_message_PhoneStatus_State_INCOMING = 4,
    aap_protobuf_service_phonestatus_message_PhoneStatus_State_CONFERENCED = 5,
    aap_protobuf_service_phonestatus_message_PhoneStatus_State_MUTED = 6
} aap_protobuf_service_phonestatus_message_PhoneStatus_State;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) aap_protobuf_service_phonestatus_message_PhoneStatus_Call_caller_thumbnail_t;
typedef struct _aap_protobuf_service_phonestatus_message_PhoneStatus_Call {
    aap_protobuf_service_phonestatus_message_PhoneStatus_State phone_state;
    uint32_t call_duration_seconds;
    bool has_caller_number;
    char caller_number[64];
    bool has_caller_id;
    char caller_id[64];
    bool has_caller_number_type;
    char caller_number_type[64];
    bool has_caller_thumbnail;
    aap_protobuf_service_phonestatus_message_PhoneStatus_Call_caller_thumbnail_t caller_thumbnail;
} aap_protobuf_service_phonestatus_message_PhoneStatus_Call;

typedef struct _aap_protobuf_service_phonestatus_message_PhoneStatus {
    pb_size_t calls_count;
    aap_protobuf_service_phonestatus_message_PhoneStatus_Call calls[8];
    bool has_signal_strength;
    uint32_t signal_strength;
} aap_protobuf_service_phonestatus_message_PhoneStatus;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_phonestatus_message_PhoneStatus_State_MIN aap_protobuf_service_phonestatus_message_PhoneStatus_State_UNKNOWN
#define _aap_protobuf_service_phonestatus_message_PhoneStatus_State_MAX aap_protobuf_service_phonestatus_message_PhoneStatus_State_MUTED
#define _aap_protobuf_service_phonestatus_message_PhoneStatus_State_ARRAYSIZE ((aap_protobuf_service_phonestatus_message_PhoneStatus_State)(aap_protobuf_service_phonestatus_message_PhoneStatus_State_MUTED+1))


#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_phone_state_ENUMTYPE aap_protobuf_service_phonestatus_message_PhoneStatus_State


/* Initializer values for message structs */
#define aap_protobuf_service_phonestatus_message_PhoneStatus_init_default {0, {aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_default, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_default, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_default, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_default, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_default, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_default, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_default, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_default}, false, 0}
#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_default {_aap_protobuf_service_phonestatus_message_PhoneStatus_State_MIN, 0, false, "", false, "", false, "", false, {0, {0}}}
#define aap_protobuf_service_phonestatus_message_PhoneStatus_init_zero {0, {aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_zero, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_zero, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_zero, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_zero, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_zero, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_zero, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_zero, aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_zero}, false, 0}
#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_init_zero {_aap_protobuf_service_phonestatus_message_PhoneStatus_State_MIN, 0, false, "", false, "", false, "", false, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_phone_state_tag 1
#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_call_duration_seconds_tag 2
#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_caller_number_tag 3
#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_caller_id_tag 4
#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_caller_number_type_tag 5
#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_caller_thumbnail_tag 6
#define aap_protobuf_service_phonestatus_message_PhoneStatus_calls_tag 1
#define aap_protobuf_service_phonestatus_message_PhoneStatus_signal_strength_tag 2

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_phonestatus_message_PhoneStatus_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  calls,             1) \
X(a, STATIC,   OPTIONAL, UINT32,   signal_strength,   2)
#define aap_protobuf_service_phonestatus_message_PhoneStatus_CALLBACK NULL
#define aap_protobuf_service_phonestatus_message_PhoneStatus_DEFAULT NULL
#define aap_protobuf_service_phonestatus_message_PhoneStatus_calls_MSGTYPE aap_protobuf_service_phonestatus_message_PhoneStatus_Call

#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    phone_state,       1) \
X(a, STATIC,   REQUIRED, UINT32,   call_duration_seconds,   2) \
X(a, STATIC,   OPTIONAL, STRING,   caller_number,     3) \
X(a, STATIC,   OPTIONAL, STRING,   caller_id,         4) \
X(a, STATIC,   OPTIONAL, STRING,   caller_number_type,   5) \
X(a, STATIC,   OPTIONAL, BYTES,    caller_thumbnail,   6)
#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_CALLBACK NULL
#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_service_phonestatus_message_PhoneStatus_msg;
extern const pb_msgdesc_t aap_protobuf_service_phonestatus_message_PhoneStatus_Call_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_phonestatus_message_PhoneStatus_fields &aap_protobuf_service_phonestatus_message_PhoneStatus_msg
#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_fields &aap_protobuf_service_phonestatus_message_PhoneStatus_Call_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_PHONESTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_PHONESTATUS_MESSAGE_PHONESTATUS_PB_H_MAX_SIZE aap_protobuf_service_phonestatus_message_PhoneStatus_size
#define aap_protobuf_service_phonestatus_message_PhoneStatus_Call_size 269
#define aap_protobuf_service_phonestatus_message_PhoneStatus_size 2182

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
