/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_PHONESTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_PHONESTATUS_MESSAGE_PHONESTATUSINPUT_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_PHONESTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_PHONESTATUS_MESSAGE_PHONESTATUSINPUT_PB_H_INCLUDED
#include <pb.h>
#include "aap_protobuf/shared/InstrumentClusterInput.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _aap_protobuf_service_phonestatus_message_PhoneStatusInput {
    aap_protobuf_shared_InstrumentClusterInput input;
    bool has_caller_number;
    char caller_number[64];
    bool has_caller_id;
    char caller_id[64];
} aap_protobuf_service_phonestatus_message_PhoneStatusInput;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define aap_protobuf_service_phonestatus_message_PhoneStatusInput_init_default {aap_protobuf_shared_InstrumentClusterInput_init_default, false, "", false, ""}
#define aap_protobuf_service_phonestatus_message_PhoneStatusInput_init_zero {aap_protobuf_shared_InstrumentClusterInput_init_zero, false, "", false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_service_phonestatus_message_PhoneStatusInput_input_tag 1
#define aap_protobuf_service_phonestatus_message_PhoneStatusInput_caller_number_tag 2
#define aap_protobuf_service_phonestatus_message_PhoneStatusInput_caller_id_tag 3

/* Struct field encoding specification for nanopb */
#define aap_protobuf_service_phonestatus_message_PhoneStatusInput_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  input,             1) \
X(a, STATIC,   OPTIONAL, STRING,   caller_number,     2) \
X(a, STATIC,   OPTIONAL, STRING,   caller_id,         3)
#define aap_protobuf_service_phonestatus_message_PhoneStatusInput_CALLBACK NULL
#define aap_protobuf_service_phonestatus_message_PhoneStatusInput_DEFAULT NULL
#define aap_protobuf_service_phonestatus_message_PhoneStatusInput_input_MSGTYPE aap_protobuf_shared_InstrumentClusterInput

extern const pb_msgdesc_t aap_protobuf_service_phonestatus_message_PhoneStatusInput_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_service_phonestatus_message_PhoneStatusInput_fields &aap_protobuf_service_phonestatus_message_PhoneStatusInput_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SERVICE_PHONESTATUS_MESSAGE_AAP_PROTOBUF_SERVICE_PHONESTATUS_MESSAGE_PHONESTATUSINPUT_PB_H_MAX_SIZE aap_protobuf_service_phonestatus_message_PhoneStatusInput_size
#define aap_protobuf_service_phonestatus_message_PhoneStatusInput_size 134

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
