/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SHARED_AAP_PROTOBUF_SHARED_INSTRUMENTCLUSTERINPUT_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SHARED_AAP_PROTOBUF_SHARED_INSTRUMENTCLUSTERINPUT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction {
    aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_UNKNOWN = 0,
    aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_UP = 1,
    aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_DOWN = 2,
    aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_LEFT = 3,
    aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_RIGHT = 4,
    aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_ENTER = 5,
    aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_BACK = 6,
    aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_CALL = 7
} aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction;

/* Struct definitions */
typedef struct _aap_protobuf_shared_InstrumentClusterInput {
    aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction action;
} aap_protobuf_shared_InstrumentClusterInput;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_MIN aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_UNKNOWN
#define _aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_MAX aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_CALL
#define _aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_ARRAYSIZE ((aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction)(aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_CALL+1))

#define aap_protobuf_shared_InstrumentClusterInput_action_ENUMTYPE aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction


/* Initializer values for message structs */
#define aap_protobuf_shared_InstrumentClusterInput_init_default {_aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_MIN}
#define aap_protobuf_shared_InstrumentClusterInput_init_zero {_aap_protobuf_shared_InstrumentClusterInput_InstrumentClusterAction_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define aap_protobuf_shared_InstrumentClusterInput_action_tag 1

/* Struct field encoding specification for nanopb */
#define aap_protobuf_shared_InstrumentClusterInput_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    action,            1)
#define aap_protobuf_shared_InstrumentClusterInput_CALLBACK NULL
#define aap_protobuf_shared_InstrumentClusterInput_DEFAULT NULL

extern const pb_msgdesc_t aap_protobuf_shared_InstrumentClusterInput_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aap_protobuf_shared_InstrumentClusterInput_fields &aap_protobuf_shared_InstrumentClusterInput_msg

/* Maximum encoded size of messages (where known) */
#define AAP_PROTOBUF_SHARED_AAP_PROTOBUF_SHARED_INSTRUMENTCLUSTERINPUT_PB_H_MAX_SIZE aap_protobuf_shared_InstrumentClusterInput_size
#define aap_protobuf_shared_InstrumentClusterInput_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
