/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SHARED_AAP_PROTOBUF_SHARED_MESSAGESTATUS_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SHARED_AAP_PROTOBUF_SHARED_MESSAGESTATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_shared_MessageStatus {
    aap_protobuf_shared_MessageStatus_STATUS_UNSOLICITED_MESSAGE = 1,
    aap_protobuf_shared_MessageStatus_STATUS_SUCCESS = 0,
    aap_protobuf_shared_MessageStatus_STATUS_NO_COMPATIBLE_VERSION = -1,
    aap_protobuf_shared_MessageStatus_STATUS_CERTIFICATE_ERROR = -2,
    aap_protobuf_shared_MessageStatus_STATUS_AUTHENTICATION_FAILURE = -3,
    aap_protobuf_shared_MessageStatus_STATUS_INVALID_SERVICE = -4,
    aap_protobuf_shared_MessageStatus_STATUS_INVALID_CHANNEL = -5,
    aap_protobuf_shared_MessageStatus_STATUS_INVALID_PRIORITY = -6,
    aap_protobuf_shared_MessageStatus_STATUS_INTERNAL_ERROR = -7,
    aap_protobuf_shared_MessageStatus_STATUS_MEDIA_CONFIG_MISMATCH = -8,
    aap_protobuf_shared_MessageStatus_STATUS_INVALID_SENSOR = -9,
    aap_protobuf_shared_MessageStatus_STATUS_BLUETOOTH_PAIRING_DELAYED = -10,
    aap_protobuf_shared_MessageStatus_STATUS_BLUETOOTH_UNAVAILABLE = -11,
    aap_protobuf_shared_MessageStatus_STATUS_BLUETOOTH_INVALID_ADDRESS = -12,
    aap_protobuf_shared_MessageStatus_STATUS_BLUETOOTH_INVALID_PAIRING_METHOD = -13,
    aap_protobuf_shared_MessageStatus_STATUS_BLUETOOTH_INVALID_AUTH_DATA = -14,
    aap_protobuf_shared_MessageStatus_STATUS_BLUETOOTH_AUTH_DATA_MISMATCH = -15,
    aap_protobuf_shared_MessageStatus_STATUS_BLUETOOTH_HFP_ANOTHER_CONNECTION = -16,
    aap_protobuf_shared_MessageStatus_STATUS_BLUETOOTH_HFP_CONNECTION_FAILURE = -17,
    aap_protobuf_shared_MessageStatus_STATUS_KEYCODE_NOT_BOUND = -18,
    aap_protobuf_shared_MessageStatus_STATUS_RADIO_INVALID_STATION = -19,
    aap_protobuf_shared_MessageStatus_STATUS_INVALID_INPUT = -20,
    aap_protobuf_shared_MessageStatus_STATUS_RADIO_STATION_PRESETS_NOT_SUPPORTED = -21,
    aap_protobuf_shared_MessageStatus_STATUS_RADIO_COMM_ERROR = -22,
    aap_protobuf_shared_MessageStatus_STATUS_AUTHENTICATION_FAILURE_CERT_NOT_YET_VALID = -23,
    aap_protobuf_shared_MessageStatus_STATUS_AUTHENTICATION_FAILURE_CERT_EXPIRED = -24,
    aap_protobuf_shared_MessageStatus_STATUS_PING_TIMEOUT = -25,
    aap_protobuf_shared_MessageStatus_STATUS_COMMAND_NOT_SUPPORTED = -250,
    aap_protobuf_shared_MessageStatus_STATUS_FRAMING_ERROR = -251,
    aap_protobuf_shared_MessageStatus_STATUS_UNEXPECTED_MESSAGE = -253,
    aap_protobuf_shared_MessageStatus_STATUS_BUSY = -254,
    aap_protobuf_shared_MessageStatus_STATUS_OUT_OF_MEMORY = -255
} aap_protobuf_shared_MessageStatus;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_shared_MessageStatus_MIN aap_protobuf_shared_MessageStatus_STATUS_OUT_OF_MEMORY
#define _aap_protobuf_shared_MessageStatus_MAX aap_protobuf_shared_MessageStatus_STATUS_UNSOLICITED_MESSAGE
#define _aap_protobuf_shared_MessageStatus_ARRAYSIZE ((aap_protobuf_shared_MessageStatus)(aap_protobuf_shared_MessageStatus_STATUS_UNSOLICITED_MESSAGE+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
