/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AAP_PROTOBUF_SERVICE_RADIO_AAP_PROTOBUF_SERVICE_RADIO_RADIOMESSAGEID_PB_H_INCLUDED
#define PB_AAP_PROTOBUF_SERVICE_RADIO_AAP_PROTOBUF_SERVICE_RADIO_RADIOMESSAGEID_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aap_protobuf_service_radio_RadioMessageId {
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_ACTIVE_RADIO_NOTIFICATION = 32769,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_SELECT_ACTIVE_RADIO_REQUEST = 32770,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_STEP_CHANNEL_REQUEST = 32771,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_STEP_CHANNEL_RESPONSE = 32772,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_SEEK_STATION_REQUEST = 32773,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_SEEK_STATION_RESPONSE = 32774,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_SCAN_STATIONS_REQUEST = 32775,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_SCAN_STATIONS_RESPONSE = 32776,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_TUNE_TO_STATION_REQUEST = 32777,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_TUNE_TO_STATION_RESPONSE = 32778,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_GET_PROGRAM_LIST_REQUEST = 32779,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_GET_PROGRAM_LIST_RESPONSE = 32780,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_STATION_PRESETS_NOTIFICATION = 32781,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_CANCEL_OPERATIONS_REQUEST = 32782,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_CANCEL_OPERATIONS_RESPONSE = 32783,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_CONFIGURE_CHANNEL_SPACING_REQUEST = 32784,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_CONFIGURE_CHANNEL_SPACING_RESPONSE = 32785,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_RADIO_STATION_INFO_NOTIFICATION = 32786,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_MUTE_RADIO_REQUEST = 32787,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_MUTE_RADIO_RESPONSE = 32788,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_GET_TRAFFIC_UPDATE_REQUEST = 32789,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_GET_TRAFFIC_UPDATE_RESPONSE = 32790,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_RADIO_SOURCE_REQUEST = 32791,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_RADIO_SOURCE_RESPONSE = 32792,
    aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_STATE_NOTIFICATION = 32793
} aap_protobuf_service_radio_RadioMessageId;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aap_protobuf_service_radio_RadioMessageId_MIN aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_ACTIVE_RADIO_NOTIFICATION
#define _aap_protobuf_service_radio_RadioMessageId_MAX aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_STATE_NOTIFICATION
#define _aap_protobuf_service_radio_RadioMessageId_ARRAYSIZE ((aap_protobuf_service_radio_RadioMessageId)(aap_protobuf_service_radio_RadioMessageId_RADIO_MESSAGE_STATE_NOTIFICATION+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
